MilestoneRFAFullSandBox/src/objects/Financial_Constant__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Constant</label>
    <nameField>
        <displayFormat>TAX-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Constant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Constants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Estimated_Cost_Accommodation__c</fullName>
        <description>Travel Expense</description>
        <label>Estimated Cost - Accommodation (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Cost_Transportation__c</fullName>
        <description>Travel Expense</description>
        <label>Estimated Cost - Transportation (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Payment_1__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Entertainment</description>
        <label>Estimated Costs (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Payment_2__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Entertainment</description>
        <label>Estimated Costs (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Payment_3__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Entertainment</description>
        <label>Estimated Costs (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_ConsumptionTax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FC_ConsumptionTax</label>
        <referenceTo>Financial_Constant__c</referenceTo>
        <relationshipLabel>RFA (FC_ConsumptionTax)</relationshipLabel>
        <relationshipName>RFAConsumptionTax</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CM02/src/classes/RFA_TriggerHandler_Helper_TravelEnter.cls
public without sharing class RFA_TriggerHandler_Helper_TravelEnter {

	/*
		============ isBefore & isInsert ============ 
	*/

	public static void processTravelAndEntertainmentRFAs(List<RFA__c> listNewRFAs) {       		
		
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Travel_Expenses_REQUEST)
			) {
				//system.debug('------- rfa.Estimated_Cost_Transportation__c: ' + rfa.Estimated_Cost_Transportation__c);				
				rfa.RequestAmountFunctionalCurrency__c = 
					Utility_Helper_String.removeNullInput(rfa.Estimated_Cost_Transportation__c) 
					+ Utility_Helper_String.removeNullInput(rfa.Estimated_Cost_Accommodation__c);
			}
			
			if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Entertainment_REQUEST)
			) {
				
				rfa.RequestAmountFunctionalCurrency__c = 
					Utility_Helper_String.removeNullInput(rfa.Estimated_Payment_1__c) 
					+ Utility_Helper_String.removeNullInput(rfa.Estimated_Payment_2__c) 
					+ Utility_Helper_String.removeNullInput(rfa.Estimated_Payment_3__c);
					
					/*					
                    rfa.FC_ConsumptionTax__c = [
                    	Select Id, Name from Financial_Constant__c 
                    	where isActive__c = true 
                    		And RecordTypeId =: RFAConstants.getRecordType(
                    			RFAConstants.FinancialConstant_RT_ConsumptionTax, 'Financial_Constant__c')
                    	Order By CreatedDate Desc limit 1].Id;		
                    */
                    rfa.FC_ConsumptionTax__c = RFA_TriggerHandler_Helper.sobjConsumptionTax.Id;	   
                                     							
			}						
		}
	}	
	
	/*
		============ isAfter & isInsert ============ 
	*/


	
	/*
		============ isBefore & isUpdate ============ 
	*/

	
	
	/*
		============ isAfter & isUpdate ============ 
	*/

	
	
	/*
		============ isBefore & isDelete ============ 
	*/

	
	
	/*
		============ isAfter & isDelete ============ 
	*/



	/*
		============ isAfter & isUnDelete ============ 
	*/	
	
}