MilestoneRFA_CM01/src/objects/Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BOD_Meeting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BOD Meeting</label>
        <referenceTo>BOD_Meeting__c</referenceTo>
        <relationshipName>Agenda_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Language__c</fullName>
        <label>Document Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>議題</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

CM01_05/src/objects/Agenda_Item_Members__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <label>Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipLabel>Agenda Item Members</relationshipLabel>
        <relationshipName>Agenda_Item_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agenda Item Members</label>
    <nameField>
        <displayFormat>AgendaMember-{00000000}</displayFormat>
        <label>Agenda Item Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>BOD_Admin</fullName>
        <active>true</active>
        <label>BOD Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>BOD_Guest</fullName>
        <active>true</active>
        <label>BOD Guest</label>
    </recordTypes>
    <recordTypes>
        <fullName>BOD_Member</fullName>
        <active>true</active>
        <label>BOD Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>BOD_Secretary</fullName>
        <active>true</active>
        <label>BOD Secretary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/BOD_Meeting__c.object
<CustomObject>
    <label>取締役会</label>
    <nameField>
        <label>Name (EN)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/BOD_Members__c.object
<CustomObject>
    <fields>
        <fullName>BOD_Meeting__c</fullName>
        <label>BOD Meeting</label>
        <referenceTo>BOD_Meeting__c</referenceTo>
        <relationshipLabel>BOD Members</relationshipLabel>
        <relationshipName>BOD_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>取締役会メンバー</label>
    <nameField>
        <displayFormat>BODMember-{00000000}</displayFormat>
        <label>BOD Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>Admin_of_BOD</fullName>
        <active>true</active>
        <label>BOD Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>BOD_Guest</fullName>
        <active>true</active>
        <label>BOD Guest</label>
    </recordTypes>
    <recordTypes>
        <fullName>BOD_Member</fullName>
        <active>true</active>
        <label>BOD Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>Secretary_of_BOD</fullName>
        <active>true</active>
        <label>BOD Secretary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/classes/BOD_Constants.cls
public without sharing class BOD_Constants {



	/*
		Public Group
	*/
	public static final String PublicGroupName_BODMember = 'BOD_Member';
	public static final String PublicGroupName_BODAdmin = 'BOD_Admin';
	public static final String PublicGroupName_BODSecretary = 'BOD_Secretary';



	/*
		Label	取締役会	
		Object Name	BOD_Meeting	
		API Name	BOD_Meeting__c
	*/
	
	public static final String BODMeeting_RowCause_Member = 'Member__c';	
	public static final String BODMeeting_RowCause_Admin = 'Admin__c';
	public static final String BODMeeting_RowCause_Secretary = 'Secretary__c';
	public static final String BODMeeting_RowCause_Guest = 'Guest__c';

	/*
		Label	取締役会メンバー	
		Object Name	BOD_Members	
		API Name	BOD_Members__c	
	*/
	public static final String BODMembersObj_APIName = 'BOD_Members__c';	
	
	public static final String BODMembersRT_BODMember_DevName = 'BOD_Member';
	public static final String BODMembersRT_BODAdmin_DevName = 'Admin_of_BOD';
	public static final String BODMembersRT_BODSecretary_DevName = 'Secretary_of_BOD';
	public static final String BODMembersRT_BODGuest_DevName = 'BOD_Guest';

	/*
		Label	議題	
		Object Name	Agenda_Item	
		API Name	Agenda_Item__c
	*/
	
	public static final String AgendaItem_RowCause_Member = 'Member__c';	
	public static final String AgendaItem_RowCause_Admin = 'Admin__c';
	public static final String AgendaItem_RowCause_Secretary = 'Secretary__c';
	public static final String AgendaItem_RowCause_Guest = 'Guest__c';	
	
	public static final String AgendaItemType_ToBeResolved = 'Proposal to be Resolved';
	public static final String AgendaItemType_ToBeReported = 'Item to be Reported';
	
	/*
		Field Label	Approval Status	
		Field Name	Approval_Status	
		API Name	Approval_Status__c	
		Data Type	Picklist
	*/
	public static String AgendaItem_ApprovalStatus_NotSubmitted = 'Not Submitted';
	public static String AgendaItem_ApprovalStatus_Submitted = 'Submitted';	
	public static String AgendaItem_ApprovalStatus_Approved = 'Approved';
	public static String AgendaItem_ApprovalStatus_Rejected = 'Rejected';
	public static String AgendaItem_ApprovalStatus_Recalled = 'Recalled';
	
	public static List<String> AgendaItem_Status_In_Approval = 
		new String[]{
			AgendaItem_ApprovalStatus_Submitted, 
			AgendaItem_ApprovalStatus_Approved, 
			AgendaItem_ApprovalStatus_Rejected
		};

	
	/*
		Field Label	Document Language	
		Field Name	Document_Language	
		API Name	Document_Language__c
		Data Type	Picklist
	*/
	public static String AgendaItem_DocLang_English = 'English';
	public static String AgendaItem_DocLang_Japanese = 'Japanese';	
	
	
	/*
		Label	Agenda Item Members	 
		Object Name	Agenda_Item_Members	
		API Name	Agenda_Item_Members__c
	*/
	public static final String AgendaItemMembersObj_APIName = 'Agenda_Item_Members__c';	
	
	public static final String AgendaItemMembersRT_BODMember_DevName = 'BOD_Member';
	public static final String AgendaItemMembersRT_BODAdmin_DevName = 'BOD_Admin';
	public static final String AgendaItemMembersRT_BODSecretary_DevName = 'BOD_Secretary';	
	public static final String AgendaItemMembersRT_BODGuest_DevName = 'BOD_Guest';
	
	
	
	

}