MilestoneRFA_CM01/src/objects/Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item_Type__c</fullName>
        <label>Agenda Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal to be Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Item to be Reported</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BOD_Meeting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BOD Meeting</label>
        <referenceTo>BOD_Meeting__c</referenceTo>
        <relationshipName>Agenda_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>/*
Parent without Doc, Parent with Doc, Child without Doc, Child with Doc
*/
IF(Related_Agenda_Item__c == null &amp;&amp; Version_Count__c == 0, &apos;Parent without Doc&apos;,   

 IF(Related_Agenda_Item__c == null &amp;&amp; Version_Count__c &gt; 0, &apos;Parent with Doc&apos;,  

   IF(Related_Agenda_Item__c != null &amp;&amp; Version_Count__c == 0, &apos;Child without Doc&apos;,  

     IF(Related_Agenda_Item__c != null &amp;&amp; Version_Count__c &gt;= 0, &apos;Child with Doc&apos;,   
       &apos;None&apos;
     ) 
   
   ) 

 ) 

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>議題</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/BOD_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper Resolution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>取締役会</label>
    <nameField>
        <label>Name (EN)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/BOD_Members__c.object
<CustomObject>
    <fields>
        <fullName>BOD_Meeting__c</fullName>
        <label>BOD Meeting</label>
        <referenceTo>BOD_Meeting__c</referenceTo>
        <relationshipLabel>BOD Members</relationshipLabel>
        <relationshipName>BOD_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BOD_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>取締役会メンバー</label>
    <nameField>
        <displayFormat>BODMember-{00000000}</displayFormat>
        <label>BOD Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>BOD_Guest</fullName>
        <active>true</active>
        <label>BOD Guest</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

本番環境バックアップ/src/classes/BOD_TestData.cls
@isTest(SeeAllData=false) 
public with sharing class BOD_TestData {
	
	private static testMethod void testBOD1() { 
		BOD_Meeting__c meeting = new BOD_Meeting__c();
		meeting.Name = 'New Meeting 1';
		meeting.Type__c = 'Online';
		meeting.Start_Time__c = System.now();
		
		insert meeting;
		
		Agenda_Item__c agenda = new Agenda_Item__c();
		agenda.Name = 'Agenda Name';
		agenda.BOD_Meeting__c = meeting.Id;
		agenda.Agenda_Item_Type__c = 'Proposal to be Resolved';
		
		insert agenda;
		
		Attachment attch = uploadAttachment(agenda.Id);
		
		//ID idBODGuest = BOD_Utility.getRecordType('BOD_Guest', 'BOD_Members__c');		
		//BOD_Members__c member = new BOD_Members__c();
		//member.BOD_Meeting__c = meeting.Id;
		//member.Username__c = Userinfo.getUserId();
		//member.RecordTypeId = idBODGuest;
		//insert member;
	}
	
    public static Attachment uploadAttachment(Id ParentId) {
        Attachment attach = new Attachment();
        Blob body = Blob.valueOf('Some Text');
        attach.Body = body;
        // add the user entered name
        attach.Name = 'RFA_Attachment.pdf';
        attach.ContentType = 'application/pdf';
        attach.IsPrivate = false;
        // attach the pdf to the account
        attach.ParentId = ParentId;        
        insert attach;
        return attach;
    }	
    

}