MilestoneRFA_CM01/src/objects/CM_RequestDetails__c.object
<CustomObject>
    <description>Commercial RFA Type.B request detail.</description>
    <fields>
        <fullName>CM_CHIRASHI__c</fullName>
        <label>CHIRASHI</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Contract_term_from__c</fullName>
        <inlineHelpText>単発時はfrom/toを同じ年月日入力します。</inlineHelpText>
        <label>Contract term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Contract_term_to__c</fullName>
        <label>Contract term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Delivery_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Delivery term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Delivery_term_to__c</fullName>
        <label>Delivery term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Input__c</fullName>
        <description>フリーフォーマット</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CM_Order_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Order term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Order_term_to__c</fullName>
        <label>Order term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Other_payment_methods__c</fullName>
        <label>Other payment methods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Payment_amount_Tax_exclusive_price__c</fullName>
        <inlineHelpText>Enter the total amount.</inlineHelpText>
        <label>Payment amount（tax-exclusive price）</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CM_Payment_method__c</fullName>
        <label>Payment method</label>
        <picklist>
            <picklistValues>
                <fullName>Prepayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Payment_timing__c</fullName>
        <label>Payment timing</label>
        <picklist>
            <picklistValues>
                <fullName>One time payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bimonthly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_RFA__c</fullName>
        <label>RFA No.</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>CM_RFA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CM_Special_sales_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Special sales term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Special_sales_term_to__c</fullName>
        <label>Special sales term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Target_Dealer__c</fullName>
        <label>Target Dealer</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Several</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA申請詳細</label>
    <nameField>
        <displayFormat>RFA#-D{000000000}</displayFormat>
        <label>Request details No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/CM_RFA__c.object
<CustomObject>
    <description>Commercial RFA承認申請用のオブジェクト</description>
    <label>CM-RFA承認申請</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>起案No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/classes/RFA_CM_VFC01_RequestDetailListController.cls
public with sharing class RFA_CM_VFC01_RequestDetailListController {


    private RFA__c target ;
    
    public List<CM_RequestDetails__c> requestDetailsList { get; set; }
    
    public RFA_CM_VFC01_RequestDetailListController(ApexPages.StandardController controller) {
        target = (RFA__c)controller.getRecord();
    }

    public void Initialization() {

       requestDetailsList =  [ Select c.SystemModstamp, c.RecordTypeId, c.Name, c.LastModifiedDate, c.LastModifiedById, 
                                               c.IsDeleted, c.Id, c.CreatedDate, c.CreatedById, c.CM_Target_Dealer__c, c.CM_Special_sales_term_to__c, 
                                               c.CM_Special_sales_term_from__c, c.CM_RFA__c, c.CM_Payment_timing__c, c.CM_Payment_method__c, 
                                               c.CM_Payment_amount_Tax_exclusive_price__c, c.CM_Payment_DueDate__c, c.CM_Other_payment_methods__c, 
                                               c.CM_Order_term_to__c, c.CM_Order_term_from__c, c.CM_Input__c, c.CM_Delivery_term_to__c, 
                                               c.CM_Delivery_term_from__c, c.CM_Contract_term_to__c, c.CM_Contract_term_from__c, c.CM_Contract_Condition_Price__c, 
                                               c.CM_CHIRASHI__c From CM_RequestDetails__c c
                                            where c.CM_RFA__c =: target.id];   
    }
    
    //public List<CM_RequestDetails__c> getRequestDetails() {
    //    return requestDetailsList; 
    //}
}