MilestoneRFA_CM01/src/objects/CM_RequestDetails__c.object
<CustomObject>
    <description>Commercial RFA Type.B request detail.</description>
    <fields>
        <fullName>CM_Automatic_Renewed__c</fullName>
        <label>Automatic renewed</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_CHIRASHI__c</fullName>
        <label>CHIRASHI</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Can_Stand__c</fullName>
        <label>Can</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Chanel_Of_Price_Guidelines__c</fullName>
        <description>Channel of price guidelines</description>
        <label>Channel of price guidelines</label>
        <picklist>
            <picklistValues>
                <fullName>R-Institutional SAKAYA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-E&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-OtherOTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L-Institutional SAKAYA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L-E&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L-OtherOTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L-CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Contract_Condition_Price_Description__c</fullName>
        <label>Contract condition（Price) / Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CM_Contract_term_from__c</fullName>
        <inlineHelpText>単発時はfrom/toを同じ年月日入力します。</inlineHelpText>
        <label>Contract term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Contract_term_to__c</fullName>
        <label>Contract term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Contractor__c</fullName>
        <label>Constractor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Cooler_Stand__c</fullName>
        <label>Cooler</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Cup_Stand__c</fullName>
        <label>Cup</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Delivery_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Delivery term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Delivery_term_to__c</fullName>
        <label>Delivery term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CM_Dispenser_Stand__c</fullName>
        <label>Dis</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Execution_due_date__c</fullName>
        <label>Execution due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Existing_Equipment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Existing equipment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CM_Input__c</fullName>
        <description>フリーフォーマット</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CM_Model_Name__c</fullName>
        <inlineHelpText>If there is more than one described in the detailed description.</inlineHelpText>
        <label>Model name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Monthly_amount_Tax_exclusive_price__c</fullName>
        <label>Monthly amount（tax-exclusive price）</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CM_New_Equipment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Equipment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CM_Number_of_SampleCase__c</fullName>
        <label>Number of Sample cases</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Order_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Order term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Order_term_to__c</fullName>
        <label>Order term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Other_Stand__c</fullName>
        <label>Ohter</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Other_payment_methods__c</fullName>
        <label>Other payment methods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Part_Name__c</fullName>
        <inlineHelpText>If there is more than one described in the detailed description.</inlineHelpText>
        <label>Part name</label>
        <picklist>
            <picklistValues>
                <fullName>Battery for disaster countermeasure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cashless(single RW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card reader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key switch for free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-theft parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wattmeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Payment_amount_Tax_exclusive_price__c</fullName>
        <inlineHelpText>Enter the total amount.</inlineHelpText>
        <label>Payment amount（tax-exclusive price）</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CM_Payment_due_date__c</fullName>
        <label>Payment due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Payment_method__c</fullName>
        <label>Payment method</label>
        <picklist>
            <picklistValues>
                <fullName>Prepayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Payment_timing__c</fullName>
        <label>Payment timing</label>
        <picklist>
            <picklistValues>
                <fullName>One time payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bimonthly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_RFA__c</fullName>
        <label>RFA No.</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>CM_RFA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CM_RecordType_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Special_sales_term_from__c</fullName>
        <inlineHelpText>単発時はfrom toを同じ年月日入力</inlineHelpText>
        <label>Special sales term (from)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Special_sales_term_to__c</fullName>
        <label>Special sales term (to)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Target_Dealer__c</fullName>
        <label>Target Dealer</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Several</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CM_Used_Equipment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Old Equipment</label>
        <type>Checkbox</type>
    </fields>
    <label>RFA申請詳細</label>
    <nameField>
        <displayFormat>RFA#-D{000000000}</displayFormat>
        <label>Request details No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/CM_RFA__c.object
<CustomObject>
    <description>Commercial RFA承認申請用のオブジェクト</description>
    <label>CM-RFA承認申請</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>起案No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

本番20140705/src/classes/CM_VFC01_RequestDetailListController.cls
/*  
 *  Class            : CM_RFA_VFC01_RequestDetailListController
 *  Author           : Pasona-Tquila
 *  Version History  : 1.0
 *  Creation         : 2014/05/20
 *  Assumptions      : N/A
 *  Description      : Class for CM_RFA_VFP01_RequestDetailList page controller   
 *
 *  Updated by Yoshinari from 2014/06/19                                    
 */
public with sharing class CM_VFC01_RequestDetailListController {
    
    // Variable declaration
    private RFA__c target ; // RFA Object
    private List<CM_RequestDetails__c> requestDetailsList ; // RFA Request Detail List

     // RecordType DeveloperName getter / value of RFA_Utility_Constants
    public String RECORDTYPE_Detail_Constract_unit_price  
        { get 
            { return  RFA_Utility_Constants.RECORDTYPE_Detail_Constract_unit_price;}
        }
    public String RECORDTYPE_Detail_Special_price_promotion_discount 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Special_price_promotion_discount;}
        }   
    public String RECORDTYPE_Detail_FS_selling_price 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_FS_selling_price;}
        }    
    public String RECORDTYPE_Detail_FS_commission_Variable 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_FS_Commission_Variable;}
        }
    public String RECORDTYPE_Detail_FS_commission_Fixed 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_FS_commission_Fixed;}
        }  
    public String RECORDTYPE_Detail_KeyMoney_Rebate_Spot_Other 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_KeyMoney_Rebate_Spot_Other;}
        }   
    public String RECORDTYPE_Detail_Only_in_the_case_of_Rebate 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Only_in_the_case_of_Rebate;}
        } 
    public String RECORDTYPE_Detail_Other_support 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Other_support;}
        }  
    public String RECORDTYPE_Detail_Promotion_OtherExpense 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Promotion_OtherExpense;}
        }   
    public String RECORDTYPE_Detail_Promotion_CooperationSample_Sampling 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Promotion_CooperationSample_Sampling;}
        }   
    public String RECORDTYPE_Detail_NonStandard_Equipment 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_NonStandard_Equipment;}
        } 
    public String RECORDTYPE_Detail_VendingEquipmentParts 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_VendingEquipmentParts;}
        } 
    public String RECORDTYPE_Detail_IncidentalWork 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_IncidentalWork;}
        }    
    public String RECORDTYPE_Detail_VendingEquipmentLease 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_VendingEquipmentLease;}
        } 
    public String RECORDTYPE_Detail_Equipment_retirement 
        { get 
            { return RFA_Utility_Constants.RECORDTYPE_Detail_Equipment_retirement;}
        }
    
    /*
     * Constructor
     */
    public CM_VFC01_RequestDetailListController(ApexPages.StandardController controller) {
        target = (RFA__c)controller.getRecord();
    }

    /*
     * Initialization
     */
    public void Initialization() 
    {
        // Soql RFA_RequestDetails__c
        requestDetailsList =  [ Select c.SystemModstamp, c.RecordType.Description, c.RecordType.DeveloperName, toLabel(c.RecordType.Name), 
                                    c.RecordTypeId, c.Name, c.LastModifiedDate, c.LastModifiedById, 
                                    c.IsDeleted, c.Id,  c.CreatedDate, c.CreatedById, c.CM_Used_Equipment__c, 
                                    c.CM_Target_Dealer__c, c.CM_Special_sales_term_to__c, c.CM_Special_sales_term_from__c, 
                                    c.CM_RecordType_Name__c, c.CM_RFA__c, c.CM_Payment_timing__c, c.CM_Payment_method__c, 
                                    c.CM_Payment_due_date__c, c.CM_Payment_amount_Tax_exclusive_price__c, c.CM_Part_Name__c, 
                                    c.CM_Other_payment_methods__c, c.CM_Other_Stand__c, c.CM_Order_term_to__c, c.CM_Order_term_from__c, 
                                    c.CM_Number_of_SampleCase__c, c.CM_New_Equipment__c, c.CM_Monthly_amount_Tax_exclusive_price__c, 
                                    c.CM_Model_Name__c, c.CM_Input__c, c.CM_Existing_Equipment__c, c.CM_Execution_due_date__c, 
                                    c.CM_Dispenser_Stand__c, c.CM_Delivery_term_to__c, c.CM_Delivery_term_from__c, c.CM_Cup_Stand__c, 
                                    c.CM_Cooler_Stand__c, c.CM_Contractor__c, c.CM_Contract_term_to__c, c.CM_Contract_term_from__c, 
                                    c.CM_Contract_Condition_Price_Description__c, 
                                    c.CM_Chanel_Of_Price_Guidelines__c, c.CM_Can_Stand__c, c.CM_CHIRASHI__c, c.CM_Automatic_Renewed__c , c.CM_Description__c
                                From CM_RequestDetails__c c 
                                where CM_RFA__c = :target.id
                                order By c.RecordType.Name];
        //setRecordTypeMap();
    }
    
    /**
     * getRequestDetailList()
     * return List<CM_RequestDetails__c>
     */
    public List<CM_RequestDetails__c> getRequestDetailList() {
        return requestDetailsList;
    }
    
    /**
     * Attachment Data class
     * add by yoshinari 2014.06.19 
     */
    public class AttachmentData {
    	public id fileId { get; set; } // object id
    	public string filename { get; set; }	// file name
    	public string lastModifiedBy { get; set; } // last modified by User
    	public Integer fileSize { get; set; } // KB
 		
 		/* 
 		 * constructor
 		 */
    	public AttachmentData(Attachment pAttachment) {
    		this.fileId = pAttachment.id;
    		this.filename = pAttachment.name;
    		this.lastModifiedBy = pAttachment.LastModifiedBy.Name;
    		this.fileSize = fileSizeConversion(pAttachment.BodyLength);
    	}
    	
    	/*
    	 * file SizeBbyte->KByte
    	 */
    	private Integer fileSizeConversion(Integer pSize) {
    		return pSize/1000; // Byte -> KByte
    	}
    }
    /**
     * getAttachments() 
     * return List<Attachment>
     */
    public List<Attachment> getAttachments() {
        return [Select a.SystemModstamp, a.ParentId, a.OwnerId, a.Name, a.LastModifiedDate, 
                    a.LastModifiedById, a.LastModifiedBy.Name, a.IsPrivate, a.IsDeleted, a.Id, a.Description, 
                    a.CreatedDate, a.CreatedById, a.ContentType, a.BodyLength, a.Body 
                From Attachment a 
                where parentid=:target.id];
    }

    /**
     * getAttachments() 
     * return List<Attachment>
     * Add by yoshinari 2014.06.19 
     */
    public List<AttachmentData> getAttachmentData() {
    	List<AttachmentData> attachmentDataList = new List<AttachmentData>();
        for (Attachment att : [Select a.SystemModstamp, a.ParentId, a.OwnerId, a.Name, a.LastModifiedDate, 
                    a.LastModifiedById, a.LastModifiedBy.Name, a.IsPrivate, a.IsDeleted, a.Id, a.Description, 
                    a.CreatedDate, a.CreatedById, a.ContentType, a.BodyLength, a.Body 
                From Attachment a 
                where parentid=:target.id])
         {
         	attachmentDataList.add(new AttachmentData(att));
         }
         return attachmentDataList;
    }
}