MilestoneRFA_CM01/src/objects/COA__c.object
<CustomObject>
    <description>Chart of Authority</description>
    <fields>
        <fullName>PrimaryCOACategory__c</fullName>
        <inlineHelpText>This field allows the RFA Creator to select up to 3 COA Categories that apply to the requested transaction.</inlineHelpText>
        <label>Primary COA Category</label>
        <picklist>
            <picklistValues>
                <fullName>I. Purchase, Disposal, Revaluation or Write-off of Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II. Leases and Rental Contracts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III. Pricing / Operating Revenues / Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV. Operating Expenses and Purchases (not covered by General Threshold)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V. Treasury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI. Personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII. Other Transactions / Activities / Contracts and Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIII. Corporate Structures and Mergers and Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IX. Board of Directors Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A. Approval of Pricing Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B. Approval of Customer Terms and Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C. Price promotion for Marketing &amp; Commercial leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D. Credit Terms / Policies</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>COA</label>
    <nameField>
        <label>COA No.</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>COA_Appendix_3_B_1_To_B_7</fullName>
        <active>true</active>
        <label>COA Appendix Ⅲ. B. 1. - B. 7.</label>
    </recordTypes>
    <recordTypes>
        <fullName>COA_Appendix_3_C</fullName>
        <active>true</active>
        <description>COA Appendix Ⅲ. C. Price promotion for Marketing &amp; Commercial leadership</description>
        <label>COA Appendix Ⅲ. C.</label>
    </recordTypes>
    <recordTypes>
        <fullName>COA_Appendix_B_1_B_7_B_8</fullName>
        <active>true</active>
        <label>COA Appendix Ⅲ. (B. 1. - B. 7.) + B. 8.</label>
    </recordTypes>
    <recordTypes>
        <fullName>COA_Matrix</fullName>
        <active>true</active>
        <description>Matrix - Specific Business Transaction</description>
        <label>COA Matrix</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/COA__c.object
    <recordTypes>
        <fullName>COA_Appendix_3_D</fullName>
        <active>true</active>
        <label>COA Appendix Ⅲ. D.</label>
    </recordTypes>

MilestoneRFAFullSandBox/src/objects/Cost_Center__c.object
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/Financial_Constant__c.object
<CustomObject>
    <label>Financial Constant</label>
    <nameField>
        <displayFormat>TAX-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Constant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Constants</pluralLabel>
    <recordTypes>
        <fullName>Consumption_Tax</fullName>
        <active>true</active>
        <description>消費税</description>
        <label>Consumption Tax</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax_Rate</fullName>
        <active>true</active>
        <label>Tax Rate</label>
    </recordTypes>
    <recordTypes>
        <fullName>WACC</fullName>
        <active>true</active>
        <label>WACC</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CokeOne</fullName>
        <active>true</active>
        <description>CokeOne専用</description>
        <label>CokeOne</label>
    </recordTypes>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General　User</description>
        <label>General</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>PrimaryCOACategory__c</fullName>
        <inlineHelpText>This field allows the RFA Creator to select up to 3 COA Categories that apply to the requested transaction.</inlineHelpText>
        <label>Primary COA Category</label>
        <picklist>
            <picklistValues>
                <fullName>I. Purchase, Disposal, Revaluation or Write-off of Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II. Leases and Rental Contracts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III. Pricing / Operating Revenues / Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV. Operating Expenses and Purchases (not covered by General Threshold)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V. Treasury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI. Personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII. Other Transactions / Activities / Contracts and Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIII. Corporate Structures and Mergers and Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IX. Board of Directors Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A. Approval of Pricing Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B. Approval of Customer Terms and Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C. Price promotion for Marketing &amp; Commercial leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D. Credit Terms / Policies</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <recordTypes>
        <fullName>A_Approval_of_Pricing_Policy</fullName>
        <active>true</active>
        <description>A. 価格方針の承認。Approval of Pricing Policy.</description>
        <label>A. Approval of Pricing Policy</label>
    </recordTypes>
    <recordTypes>
        <fullName>B_Approval_of_Customer_Terms_Conditions</fullName>
        <active>true</active>
        <description>B. 顧客取引条件の承認。Approval of Customer Terms and Conditions.</description>
        <label>B. Approval of Customer Terms &amp; Conditions</label>
    </recordTypes>
    <recordTypes>
        <fullName>C_Price_Promotion_for_Marketing_Commercial_Leadership</fullName>
        <active>true</active>
        <description>C. 全社プロモーション価格の承認および、マーケティング＆コマーシャルリーダーシップ起案の販売促進費の承認。Price Promotion for Marketing &amp; Commercial leadership.</description>
        <label>C. Price Promotion for Marketing &amp; Commercial Leadership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Capital_Budget_Initial_Request</fullName>
        <active>true</active>
        <description>次年度のCAPEX（設備投資）予算を確保するための事前申請。BP策定時のみ使用              The in-advance application for securing the CAPEX (capital investment) budget for next year. It is used only at the time of BP decision.</description>
        <label>04. Capital Budget Initial Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>D_Credit_Terms_Policies</fullName>
        <active>true</active>
        <description>D. クレジットポリシー。Credit Terms / Policies.</description>
        <label>D. Credit Terms / Policies</label>
    </recordTypes>
    <recordTypes>
        <fullName>Entertainment_Request</fullName>
        <active>true</active>
        <description>CokeOneに関連する交際費。Request for Entertainment expenses related to CokeOne Project.</description>
        <label>Entertainment Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project_Charter_Request</fullName>
        <active>true</active>
        <description>プロジェクトを実行する為のリクエスト。期間／予算／マイルストン／メンバーが決まったら申請する。Project Charter Request</description>
        <label>02. Project Charter Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project_Close_Out_Request</fullName>
        <active>true</active>
        <description>プロジェクトが完了した場合のリクエスト。オーナー含め関係者にプロジェクトが完了した承認を頂く。Project Close-Out Request</description>
        <label>03. Project Close-Out Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project_Initiate_Request</fullName>
        <active>true</active>
        <description>プロジェクトを立ち上げる為のリクエスト。最初の承認。Project Initiate Request</description>
        <label>01. Project Initiate Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFA_CapitalProjectRequest</fullName>
        <active>true</active>
        <description>５千万円超の資本プロジェクトの申請。Capital Projects (individual asset purchase, capital investment or bulk purchase (e.g. aggregate cooler investment, total IT investment for a specific initiative, etc.)) with costs &gt; ¥50 MM.</description>
        <label>Capital Project Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFA_RFARequest</fullName>
        <active>true</active>
        <description>下記およびコマーシャル以外の申請。Any request for approval that is NOT a Capital or Medium or Small Project Request.</description>
        <label>General Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFA_SmallProjectRequest</fullName>
        <active>true</active>
        <description>２千５百万円以下の小規模プロジェクトの申請。Small Projects (individual asset purchase, capital investment or bulk purchase) with costs ≤ ¥25 MM, which are not part of a larger investment program, construction project and/or cash outlay.</description>
        <label>Small Project Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFA_Small_Project_Request</fullName>
        <active>true</active>
        <description>２千５百万円超５千万円以下の中規模プロジェクトの申請。Medium Projects (individual asset purchase, capital investment or bulk purchase) with costs &gt;¥25 MM and ≤  ¥50 MM, which are not part of a larger investment program, construction project and/or cash outlay.</description>
        <label>Medium Project Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Seal_Paperless_Request</fullName>
        <active>true</active>
        <description>社印・部署印の押印申請  / Request for Corporate seal and Function seal</description>
        <label>Seal Paperless Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Travel_Expenses_Request</fullName>
        <active>true</active>
        <description>CokeOneに関連する旅費。Request for Travel related to CokeOne Project.</description>
        <label>Travel Expenses Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <recordTypes>
        <fullName>RUR_Approver</fullName>
        <active>true</active>
        <description>本申請の承認者を割当てます</description>
        <label>Approver</label>
    </recordTypes>
    <recordTypes>
        <fullName>RUR_InfoCopyOnly</fullName>
        <active>true</active>
        <description>本申請の参照者を指定します</description>
        <label>Info Copy Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>RUR_PrimaryPointofContact</fullName>
        <active>true</active>
        <description>本申請の主担当者を指定します</description>
        <label>Primary Point of Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullSandCoke/src/classes/RFA_Utility_Constants.cls
/*  
 *  Class            : RFA_Utility_Constants
 *  Author           : Pasona-Tquila
 *  Version History  : 1.0
 *  Creation         : 2014/05/20
 *  Assumptions      : N/A
 *  Description      : Class for Constants used in RFA.                                  
 */
public with sharing class RFA_Utility_Constants {

    /*
        Custom Button Label
    */    
    public static final String Button_Send_To_Circulation = 'Send to Circulation'; 
    public static final String Button_Approval_Recommend = 'Submit Approval Recommendation';
    public static final String Button_Show_Approver = 'Show Approvers';
    public static final String Button_Close_RFA = 'Close RFA';
    //public static final String Button_Return_To_Requester = 'Return to Requester';
    
    /*
        RFA Object (API: RFA__c)
    */
    public static final String sObj_RFA_APIName = 'RFA__c'; 
      
    //previous name is Stage; Label: Status / API: Stage__c (Picklist)   
    public static final String RFA_STATUS_DRAFT = 'Draft'; 
    public static final String RFA_STATUS_ReturnToRequester = 'Return to Requester';   
     
    public static final String RFA_STATUS_CIRCULATION = 'Circulation'; 
    
    public static final String RFA_STATUS_APPROVED = 'Approved';  
    public static final String RFA_STATUS_REJECTED = 'Rejected';          
    public static final String RFA_STATUS_CLOSED = 'Closed';
    
    /* Record Type API Name  */   
    //RFA Record Type Value   //'Small Project Request ( < 25MM )';
    //Small Project Request B -> Small Project Request  by Jia Hu on 2013/12/02
    //RECORDTYPE_SMALL_PROJECT_REQUEST_LessThan25MM -> RECORDTYPE_SMALL_PROJECT_REQUEST
    public static final String RECORDTYPE_SMALL_PROJECT_REQUEST = 'RFA_SmallProjectRequest'; //'Small Project Request'; 
    //Small Project Request A -> Medium Project Request
    //RECORDTYPE_SMALL_PROJECT_REQUEST_A -> RECORDTYPE_Medium_PROJECT_REQUEST
    public static final String RECORDTYPE_Medium_PROJECT_REQUEST = 'RFA_Small_Project_Request'; //'Medium Project Request';   
    public static final String RECORDTYPE_CAPITAL_PROJECT_REQUEST = 'RFA_CapitalProjectRequest'; //'Capital Project Request';
    public static final String RECORDTYPE_General_PROJECT_REQUEST = 'RFA_RFARequest'; //'General Request';
    //CokeOne
    public static final String RECORDTYPE_Travel_Expenses_REQUEST = 'Travel_Expenses_Request';
    public static final String RECORDTYPE_Entertainment_REQUEST = 'Entertainment_Request';
    //Commercial
    public static final String RECORDTYPE_Commercial_A_REQUEST = 'A_Approval_of_Pricing_Policy';
    public static final String RECORDTYPE_Commercial_B_REQUEST = 'B_Approval_of_Customer_Terms_Conditions';
    public static final String RECORDTYPE_Commercial_C_REQUEST = 'C_Price_Promotion_for_Marketing_Commercial_Leadership'; 
    															//'C_Price_Promotion_for_Marketing_Commercial_Leadership';
    public static final String RECORDTYPE_Commercial_D_REQUEST = 'D_Credit_Terms_Policies';    
    //Paperless
    public static final String RECORDTYPE_Seal_Paperless_REQUEST = 'Seal_Paperless_Request'; 
    //Milestone
    public static final String RECORDTYPE_Project_Initiate_REQUEST = 'Project_Initiate_Request';    
    public static final String RECORDTYPE_Project_Charter_REQUEST = 'Project_Charter_Request';      
    public static final String RECORDTYPE_Project_Close_Out_REQUEST = 'Project_Close_Out_Request';    
    public static final String RECORDTYPE_Project_Budget_Initiate_REQUEST = 'Capital_Budget_Initial_Request';    
 
    // Commercial Request Detail 
    public static final String RECORDTYPE_Detail_Constract_unit_price           = 'CM_01_Contract_unit_price';
    public static final String RECORDTYPE_Detail_Special_price_promotion_discount = 'CM_02_Special_price_promotion_discount';
    public static final String RECORDTYPE_Detail_FS_selling_price               = 'CM_03_FS_selling_price';
    public static final String RECORDTYPE_Detail_FS_commission_Variable         = 'CM_04_FS_commission_Variable';
    public static final String RECORDTYPE_Detail_FS_commission_Fixed            = 'CM_05_FS_commission_Fixed';  
    public static final String RECORDTYPE_Detail_KeyMoney_Rebate_Spot_Other     = 'CM_06_KeyMoney_Rebate_Spot_Other';   
    public static final String RECORDTYPE_Detail_Only_in_the_case_of_Rebate     = 'CM_07_Only_in_the_case_of_Rebate'; 
    public static final String RECORDTYPE_Detail_Other_support                  = 'CM_08_Other_support';  
    public static final String RECORDTYPE_Detail_Promotion_OtherExpense         = 'CM_09_Promotion_OtherExpense';   
    public static final String RECORDTYPE_Detail_Promotion_CooperationSample_Sampling = 'CM_10_Promotion_CooperationSample_Sampling';   
    public static final String RECORDTYPE_Detail_NonStandard_Equipment          = 'CM_a_Nonstandard_Equipment'; 
    public static final String RECORDTYPE_Detail_VendingEquipmentParts          = 'CM_b_Vending_Equipment_parts'; 
    public static final String RECORDTYPE_Detail_IncidentalWork                 = 'CM_c_Incidental_work';    
    public static final String RECORDTYPE_Detail_VendingEquipmentLease          = 'CM_d_Vending_Equipment_Lease'; 
    public static final String RECORDTYPE_Detail_Equipment_retirement           = 'CM_e_Equipment_retirement';
 
 
    //Apex Sharing Reasons
    public static final String RowCause_Requestor = 'KORequestor__c'; //Label.RFA_CL076; //KORequestor
    public static final String RowCause_Approver = 'Approver__c';
    public static final String RowCause_PCReviewer = 'PCReviewer__c';
    public static final String RowCause_Reviewer = 'Reviewer__c';
    
    
    
    /*
        error msg of RFA object
    */
    //PrimaryCOACategory__c
    public static final String Primary_COA_Category_MandatoryMsg 
        = 'Select the Primary COA Category';
    

    /*
        RFA Approver/User Object (API: RFAUserRole__c)
    */
    public static final String sObj_RFAUserRole_APIName = 'RFAUserRole__c'; 
    
    public static final String RTLabel_RFAUserRole_Approver = 'Approver'; 
    public static final String RTLabel_RFAUserRole_PPOC = 'Primary Point of Contact'; 
    public static final String RTLabel_RFAUserRole_InfoOnly = 'Info Copy Only'; 
    
    public static final String RFAUserRole_RTAPIName_Approver = 'RUR_Approver'; 
    public static final String RFAUserRole_RTAPIName_PPOC = 'RUR_PrimaryPointofContact'; 
    public static final String RFAUserRole_RTAPIName_InfoOnly = 'RUR_InfoCopyOnly';     
    //will move this
    public static final String RFAUserRole_RTAPIName_InfoOnlyAfterApply = 'RM_Info_Copy_After_Apply';
    
    //Approval Recommendation (API: ApprovalRecommendation__c):Picklist
    public static final String ApproverRecommend_UnconditionalApproved = 'Unconditionally Approved / 承認（条件なし）'; 
    //public static final String ApproverRecommend_UnconditionalApproved_JP = '承認（条件なし）';
    public static final String ApproverRecommend_ConditionalApproved = 'Conditionally Approved / 承認（条件付き）'; 
    //public static final String ApproverRecommend_ConditionalApproved_JP = '承認（条件付き）';
    public static final String ApproverRecommend_Rejected = 'Rejected / 否認'; 
    //public static final String ApproverRecommend_Rejected_JP = '否認';
    public static final String ApproverRecommend_AwaitingApproval = 'Awaiting Approval / 承認待ち'; 
    //public static final String ApproverRecommend_AwaitingApproval_JP = '承認待ち';
    public static final String ApproverRecommend_ReturnToRequester = 'Return to Requester / 差し戻し'; 
    
    public static final String Approver_Source_COA = 'COA'; 
    public static final String Approver_Source_COA_Group = 'COA Group'; 
    public static final String Approver_Source_COA_Single = 'COA Single'; 
    public static final String Approver_Source_Manager = 'Manager'; 
    public static final String Approver_Source_CokeOneManager = 'CokeOne Manager'; 
    public static final String Approver_Source_Approver = 'Approver'; 
    public static final String Approver_Source_Requester = 'Requester'; 
    public static final String Approver_Source_CapitalMgmt = 'Capital Mgmt.';      
    public static final String Approver_Source_TreasuryMgr = 'Treasury Mgr'; 
    public static final String Approver_Source_FixAssetMgr = 'Fix Asset Mgr'; 
    public static final String Approver_Source_ELT = 'ELT'; 
    
    public static final String Approver_Source_InfoCopy = 'Info Copy';     
    public static final String Approver_Source_InfoCopy_Manager = 'Info Copy - Manager';  
    public static final String Approver_Source_InfoCopy_CorpAdmin = 'Info Copy - Corporate Administration';   
    public static final String Approver_Source_InfoCopy_BOD = 'Info Copy - BOD';  
    
    public static final String Approver_Source_CokeOne_ProjectFinance = 'CokeOne';
    public static final String Approver_Source_CokeOne_Gr2 = 'CokeOne Gr.2';

    //Milestone Request
    public static final String Approver_Source_Project = 'Project';
        
    //Seal Paperless Request
    public static final String Approver_Source_Seal = 'Seal';
    
    public static final String Approver_Source_Appendix3_B2 = 'Appendix 3.B.2';
    public static final String Approver_Source_Appendix3_D = 'Appendix 3.D';
    
    
    /*
        Approval Process Object (API: ApprovalProcess__c)
    */    
    public static final String ApprovalProcess_Not_Started = 'Not Started'; 
    public static final String ApprovalProcess_In_Progress = 'In Progress';
    public static final String ApprovalProcess_Completed = 'Completed';
    public static final String ApprovalProcess_Not_Completed = 'Not Completed';
    
    /*
        COA Object (API: COA__c)
    */      
    public static final String sObj_COA_APIName = 'COA__c'; 
    
    public static final String COA_RTAPIName_Matrix = 'COA_Matrix'; 
    public static final String COA_RTAPIName_Appendix3_B1ToB7 = 'COA_Appendix_3_B_1_To_B_7'; //'COA_Appendix_3_B_1_To_B_6';
    public static final String COA_RTAPIName_Appendix3_B1ToB7WithB8 = 'COA_Appendix_B_1_B_7_B_8';
    //public static final String COA_RTAPIName_Appendix3_B1 = 'COA_Appendix_3_B_1';     
    //public static final String COA_RTAPIName_Appendix3_B2 = 'COA_Appendix_3_B_2';  
    //public static final String COA_RTAPIName_Appendix3_B3 = 'COA_Appendix_3_B_3';      
    //public static final String COA_RTAPIName_Appendix3_B4 = 'COA_Appendix_3_B_4';      
    //public static final String COA_RTAPIName_Appendix3_B5 = 'COA_Appendix_3_B_5';     
    //public static final String COA_RTAPIName_Appendix3_B6 = 'COA_Appendix_3_B_6';     
    //public static final String COA_RTAPIName_Appendix3_B7 = 'COA_Appendix_3_B_7';         
    //public static final String COA_RTAPIName_Appendix3_B8 = 'COA_Appendix_3_B_8'; 
    public static final String COA_RTAPIName_Appendix3_C  = 'COA_Appendix_3_C';      
    public static final String COA_RTAPIName_Appendix3_D  = 'COA_Appendix_3_D';   
        
    public static final String Threshold_Type_All = 'All'; 
    public static final String Threshold_Type_Value = 'Value'; 
    public static final String Threshold_Type_ValueWithRT = 'Value with Record Type'; 
    public static final String Threshold_Type_Budgeted = 'Budgeted'; 
    
    public static final String Group1 = 'Gr.1'; 
    public static final String Group2 = 'Gr.2'; 
    public static final String Group3 = 'Gr.3'; 
    public static final String Group4 = 'Gr.4'; 
    public static final String Group5 = 'Gr.5'; 
    public static final String Group6 = 'Gr.6'; 
    public static final String Group7 = 'Gr.7'; 
    
    /*
        Profit Center Object (API: ProfitCenter__c)
    */  
    //Profit Center Name  API: ProfitCenterName__c / Text(100)
    
    public static final String ProfitCenter_Name_CCEJ = 'CCEJ'; 
    
    /*
        Profit Center User Role Object (API: ProfitCenterUserRole__c)
    */
    //User Type (UserType__c)
    //public static final String ProfitCenterUserRole_UserType_Coordinator = 'Coordinator';   
    public static final String ProfitCenterUserRole_UserType_Viewer = 'Viewer - All';   
    public static final String ProfitCenterUserRole_UserType_Capital = 'Viewer - Capital Only';     

    
    
    /*
        Cost Center Object (API: Cost_Center__c)
    */
    //Field Lable: Cost Center Number
    public static final String CostCenter_Name = '0001';    
    
    /*
        Old: RFA_TaxRate Object (API: RFA_TaxRate__c)
        New: Financial Constant (API: Financial_Constant__c)
        
    */
    //Field Lable: RFA_TaxRate Name 
    //public static final String TaxRate_Name = '0001';     
    
    public static final String sObj_FinancialConstant_APIName = 'Financial_Constant__c'; 
    
    public static final String FinancialConstant_RT_TaxRate = 'Tax_Rate';
    public static final String FinancialConstant_RT_WACC = 'WACC';
    public static final String FinancialConstant_RT_ConsumptionTax = 'Consumption_Tax';
    
    
    
    /*
        Related Document
    */
    public static final String Doc_Name_Investment_Category = 'Investment_Objective_Definition';        
    public static final String Doc_Name_Asset_Category = 'Asset_Category_Definition';
    
    
    /*
        =====================
            Config
        =====================
    */
    /*
        User Object
    */      
    public static final String SysAdminProfile  = 'System Administrator';
    public static final String SysAdminJPProfile  = 'システム管理者';
    
    public static final String RFASysAdminProfile = 'RFA - System Administrator';
    
    public static final String RFACapitalMgmtProfile = 'RFA - Capital Management Admin';
    public static final String RFAStandardProfile = 'RFA - Standard User';
    
    public static final String RFA_System_User = 'RFA System';
    
    
    /*
    	Public Group
    */
	public static final String PublicGroupName_SealAdminTeam = 'Company_Seals_Member'; //'Seal_Admin_Team';    
    
    /*
    	Projects Object (API:Milestone1_Project__c)
    */
    public static final String ApprovalSetp_InitiateApproved = 'Initiate Approved';
    public static final String ApprovalSetp_CharterApproved = 'Charter Approved';
    public static final String ApprovalSetp_CloseOutApproved = 'Close-Out Approved';
    
    
    /*
   		the mehtods below will be moved to other classes
    */
    
    public static Id getOrgWideEmailAddressId() {
        OrgWideEmailAddress[] owea = [select Id, IsAllowAllProfiles, DisplayName 
            from OrgWideEmailAddress where DisplayName =: RFA_System_User];
        system.debug('------ OrgWideEmailAddress[]: ' + owea);
        if(owea != null && owea.size() > 0) {
            return owea[0].Id;
        }
        return null;
    }
  
    public static boolean isRFAAdmin(String strProfileName)
    {       
        if(
            strProfileName == SysAdminProfile || // System Administrator
            strProfileName == SysAdminJPProfile  || //for Japanese
            strProfileName == RFASysAdminProfile // RFA - System Administrator           
          )
        { 
            return true; // user is a RFA system admin          
        }         
        return false;
    }    
    
    public static boolean evaluateIfAdmin(Id profileId)
    {
         boolean check = false;
         for(Profile profile : [
            Select Id From Profile 
                Where Name =: RFASysAdminProfile //'RFA - System Administrator' 
                    //OR Name = 'RFA - Capital Management Admin' 
                    OR Name =: SysAdminProfile //'System Administrator' 
                    OR Name =: SysAdminJPProfile //'システム管理者' 
                    ])
         {
             if(
                //UserInfo.getProfileId() 
                profileId == profile.Id) {
                check = true;
             }  
         }
         return check;
    }    
    
    public static Id getRFAStandardUserProfileId()
    {
        return [Select Id, Name FROM Profile where Name =: RFAStandardProfile LIMIT 1].Id;
    }   
    
    
    public static Id getRFACapitalMgmtProfileId()
    {
        return [Select Id, Name FROM Profile where Name =: RFACapitalMgmtProfile LIMIT 1].Id;
    }       
    
    /*
        RecordType Object: using label not API name
        Id approverRTId = RFAConstants.getRecordType('Approver', 'RFAUserRole__c');
        Record Type Label:  Approver
        Record Type Name:   RUR_Approver
    */  
    public static Id getRecordType(String pName, String sObjectType)
    {
        system.debug('------- getRecordType() RT Name: ' + pName + ' Object: ' + sObjectType);
        return [Select Id, Name FROM RecordType Where SObjectType =: sObjectType AND Name =: pName].Id;
    }   
  	
  	/* 
	 * getRecordType()
	 * parameter : Id RecordType.Id
	 *           : String SObjectType   'RFA__c' 
	 * return String RecordType.DeveloperName
	 * add by yoshinari 2014/05/23
	 */
    public static String getRecordType(Id pId, String sObjectType)
    {
        system.debug('------- getRecordType() RT Id: ' + pId + ' Object: ' + sObjectType);
        return [Select Id, Name, DeveloperName FROM RecordType Where SObjectType =: sObjectType AND Id =: pId].DeveloperName;
    }   
  
    
    public static boolean isBlank(String str) 
    {
        return str == null || str.trim() == null || str.trim().length() == 0;
    }    
    
}