MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>AgentsAssigned__c</fullName>
        <formula>IF( ISBLANK( Agent1__c) &amp;&amp;  ISBLANK( Agent2__c) &amp;&amp; ISBLANK( Agent3__c), &quot;No&quot;, &quot;Yes&quot;)</formula>
        <label>Agents Assigned?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <description>IF($RecordType.Name == &apos;Info Copy Only&apos;, &quot;Info Copy Only&quot;, &quot;&quot;)</description>
        <inlineHelpText>Add comment in both Japanese and English, if any non-Japanese recipient is involved in the approval process (either approver or info copy).</inlineHelpText>
        <label>Condition / Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Source__c</fullName>
        <label>Approver Source</label>
        <picklist>
            <picklistValues>
                <fullName>Requester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Mgmt.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treasury Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix Asset Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne Gr.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - BOD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>COA_Acronym__c</fullName>
        <formula>UserName__r.COA_Acronym__c</formula>
        <label>COA Acronym</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COA_Group__c</fullName>
        <formula>Text(UserName__r.COA_Group__c)</formula>
        <label>COA Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>COA_Acronym__c</fullName>
        <label>COA Acronym</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COA_Group__c</fullName>
        <label>COA Group</label>
        <picklist>
            <picklistValues>
                <fullName>Gr.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>L2_Function_E__c</fullName>
        <label>L2 Function E</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L3_Function_E__c</fullName>
        <label>L3 Function E</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L4_Function_E__c</fullName>
        <label>L4 Function E</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

CocaColaProjectBIDev/src/classes/RFA_VFC_ApproverListController.cls
/*
	Created by Jia Hu on 2013/11/29
	Reference: RFA_RF1_50_LocationCoordinator_V2
	Controller of VF page: RFA_Button_ApproverList
*/
public with sharing class RFA_VFC_ApproverListController {
	
	private integer counter = 0;  //keeps track of the offset
    private integer list_size = 100; //sets the page size or number of rows
    public integer total_size; //used to show user the total size of the list
    
  	public List<ProfitCenterUserRole__c> LocationCoordinators { 
  		get {return sortList(LocationCoordinators);} 
  		set; }		

  	public List<RFAUserRole__c> Approvers { 
  		get {return sortList(Approvers);} 
  		set; } 
  		
  	public String sortBy { get; set; }
  	public String sortDir { get; set; }
  	
  	// instance of RFA__c
    public RFA__c rfaObj{ get; set;}
    
    public RFA_VFC_ApproverListController(ApexPages.StandardController controller) {
    	this.rfaObj = (RFA__c)controller.getRecord();
        
        /*
        if(rfaObj.Id <> null) {
        	this.rfaObj = [
        		Select ProfitCenterNumber__c,ProfitCenterName__c,ProfitCenterNumber__r.name
                FROM RFA__c 
                WHERE Id =: rfaObj.id
            ];
        }*/
        
		//Approver: 01210000000QsJj
		Id approverRTId = RFAConstants.getRecordType(
			RFAConstants.RTLabel_RFAUserRole_Approver, 
			RFAConstants.Obj_RFAUserRole_APIName
			);
			
		//total_size = [select count() from RFAUserRole__c where RFA__c =: rfaObj.Id And RecordTypeId =: approverRTId 
			//'01210000000QsJj'
		//	];
		
		//LocationCoordinators = [
		Approvers = [
			Select UserName__c, 
				UserName__r.Name, UserName__r.Lastname, UserName__r.Firstname, 
				UserName__r.COA_Acronym__c, UserName__r.COA_Group__c,
				UserName__r.L2_Function_E__c, UserName__r.L3_Function_E__c, UserName__r.L4_Function_E__c,
				RecordType.Name, RecordTypeId, 
				ApprovalRecommendation__c, ApprovalComments__c,
				ApprovalOrder__c, Approver_Source__c, AgentsAssigned__c
			from RFAUserRole__c where RFA__c =: rfaObj.Id And RecordTypeId =: approverRTId 
			//'01210000000QsJj'
			order by ApprovalOrder__c ASC, UserName__r.Name ASC
			];
		
		if(Approvers != null && Approvers.size() > 0) {
			total_size = Approvers.size();
		} else {
			total_size = 0;
		}
		
		  
    }
	    
   	public PageReference empty() { return null; }

  
  	// The sorting function works on all SObjects sorting on all fields
  	public List<SObject> sortList(List<SObject> cleanList)
  	{
  		if (sortBy == null) { return cleanList; }
    	List<SObject> resultList = new List<SObject>();
    	Map<Object, List<SObject>> objectMap = new Map<Object, List<SObject>>();
    	for (SObject item : cleanList) {
      		if (objectMap.get(item.get(sortBy)) == null) {
        		objectMap.put(item.get(sortBy), new List<SObject>());
      	}
      	objectMap.get(item.get(sortBy)).add(item);
    	}
    	List<Object> keys = new List<Object>(objectMap.keySet());
    	keys.sort();
    	for(Object key : keys) {
      		resultList.addAll(objectMap.get(key));
    	}
    	cleanList.clear();
    if (sortDir == 'ASC') {
      for (SObject item : resultList) {
        cleanList.add(item);
      }
    } else {
      for (Integer i = resultList.size()-1; i >= 0; i--) {
        cleanList.add(resultList[i]);
      }
    }
  
    return cleanList;
  }   
  
    public PageReference Beginning() { //user clicked beginning
      counter = 0; 
      return null;
   }
 
   public PageReference Previous() { //user clicked previous button
      counter -= list_size; 
      return null;
   }
 
   public PageReference Next() { //user clicked next button
      counter += list_size; 
      return null;
   }
 
   public PageReference End() { //user clicked end
      counter = total_size - math.mod(total_size, list_size);
      return null;
   }
 
   public Boolean getDisablePrevious() { 
      //this will disable the previous and beginning buttons
      if (counter>0) return false; else return true;
   }
 
   public Boolean getDisableNext() { //this will disable the next and end buttons
      if (counter + list_size < total_size) return false; else return true;
   }
 
   public Integer getTotal_size() {
      return total_size;
   }
 
   public Integer getPageNumber() {
      return counter/list_size + 1;
   }
 
   public Integer getTotalPages() {
      if (math.mod(total_size, list_size) > 0) {
         return total_size/list_size + 1;
      } else {
         return (total_size/list_size);
      }
   }

}