MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ActiveInactive__c</fullName>
        <label>Active/Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NeedRecalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for recalculation of sharing model</description>
        <inlineHelpText>This field is used for recalculation of sharing model.</inlineHelpText>
        <label>Need Recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

CokeFull/src/classes/RFA_BC01_ReAlignment.cls
/**
* Class Name: RFA_BC01_ReAlignment
* Author: Accenture
* Date: 04-07-2012
* Project Name: Coke-RFA
 * Requirement Description: This is schedule batch which will call the RFA_AP09_Alignment class.
 
 **/
global class RFA_BC01_ReAlignment implements Schedulable{
    
    /**
     *  execute  method
     *  @param Crone Time
     *  @return null    
     */
    global void execute(SchedulableContext sc) {
        String Query = 'Select Id ,name from ProfitCenter__c where NeedRecalculation__c=true and ActiveInactive__c=\'Active\'';
        RFA_AP09_Realignment controller = new RFA_AP09_Realignment(Query) ;
        Integer batchSize = 200;
        database.executebatch(controller , batchSize);
   }

}