MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFA_Agent_1__c</fullName>
        <label>RFA Agent 1</label>
        <relationshipName>RFA_Agent_1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

RFA_MilestoneRM01/src/classes/RFA_VFC12_EditAgentsController_Test.cls
/**
	updated by Jia Hu on 2013/11/12
 */
@isTest(SeeAllData=false) 
private class RFA_VFC12_EditAgentsController_Test {

    /*
     * Scenario 1: Test updating Agents as a user which is not a location coordinator (error output)
     * Scenario 2: Test updating Agents as a user which is a location coordinator
     * Scenario 3: Test as Admin, assign user as agent (error output)
     * Scenario 4: Test as Admin, set required field, email address, to null to invoke an error (error output)
    */ 
    static testMethod void myUnitTest1() 
    { 
        string profile = RFAConstants.getRFAStandardUserProfileId();
        RFATestData RTData = new RFATestData();
        
        //RTData.buildProfitCenter();
        RFA__c testRFA = RFATestData.buildRFACapital();
        
        // Obtain a Location Coordinator
        ProfitCenterUserRole__c profitCenterUser = [
        	Select UserName__c From ProfitCenterUserRole__c 
        	where ProfitCenter__c = :RFATestData.testProfitCenter.id LIMIT 1];
        	
        User lcUser;
        
        if (profitCenterUser != null)
            lcUser = new User(id = profitCenterUser.UserName__c);
        
        User notLCUser = RTData.createUser(profile, 'NotLCUsr', 'NotLCUser');
        
        User grUser = RTData.createUser(profile, 'TestUser', 'grlastt');
        
        PageReference pageRef = Page.RFA_RF1_22_EditAgents;
        Test.setCurrentPage(pageRef); 
        System.currentPageReference().getParameters().put('id', grUser.id); 
        ApexPages.Standardcontroller stdController1 = new ApexPages.Standardcontroller(grUser);
        RFA_VFC12_EditAgentsController controller1 = new RFA_VFC12_EditAgentsController(stdController1); 
        
        // Test as a user which is not a Location Coordinator
        System.runAs(notLCUser)
        {
            controller1.userobj.RFA_Agent_1__c = notLCUser.id;
            controller1.updateUserAgents();
        }
        
        // Test as Location Coordinator
        /*
        if (lcUser != null)
        {
            // Reset pcAssociatedUsers static list variable on the RFA_WS07_CheckRFAUser class
            RFA_WS07_CheckRFAUser.pcAssociatedUsers = null;
            
            System.runAs(lcUser)
            {
                controller1.userobj.RFA_Agent_1__c = lcUser.id;
                controller1.updateUserAgents();
            }
        }*/
        
        // Test Failed Scenarios
        controller1.userobj.RFA_Agent_1__c = grUser.Id;
        controller1.updateUserAgents();
        
        controller1.userobj.RFA_Agent_1__c = null;
        controller1.userobj.email = null;
        controller1.updateUserAgents();
    }
    
}