MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>BottlerDiscPaybackPeriodYears__c</fullName>
        <inlineHelpText>The number of years it takes the bottler to break-even between the investment and the return using the bottler&apos;s WACC rate.</inlineHelpText>
        <label>Bottler Disc. Payback Period-Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BottlerIRR__c</fullName>
        <inlineHelpText>Internal Rate of Return of the bottler included in the transaction.</inlineHelpText>
        <label>Bottler IRR (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BottlerInvestmentDepreciationYears__c</fullName>
        <label>Bottler Investment Depreciation Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BottlerLocalEffectiveTaxRate__c</fullName>
        <inlineHelpText>Effective tax rate of the bottler involved in the transaction.</inlineHelpText>
        <label>Bottler Local Effective Tax Rate (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BottlerParticipationAmountUSD__c</fullName>
        <formula>BottlerParticipationAmountFC__c 
/*
BottlerParticipationAmountFC__c * ARERate__c
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The bottler&apos;s portion of the cost, as opposed to the Company.</inlineHelpText>
        <label>Bottler Participation Amount (USD $)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BottlerParticipation__c</fullName>
        <inlineHelpText>The bottler&apos;s percentage portion of the cost, as opposed to the Company.</inlineHelpText>
        <label>Bottler Participation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BottlerWACC__c</fullName>
        <inlineHelpText>Weighted average cost of capital for the bottler use for comparative purposes.</inlineHelpText>
        <label>Bottler WACC (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BudgetType__c</fullName>
        <inlineHelpText>&quot;Initial&quot; is used for projects that are still in the preliminary stages of planning and evaluation when details are not complete,&quot;Formal&quot; is used for projects for which implementation plans and cost assumptions are final or nearly final.</inlineHelpText>
        <label>Budget Type</label>
        <picklist>
            <picklistValues>
                <fullName>Formal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CashflowAnalysisYears__c</fullName>
        <inlineHelpText>The number of years used in the cash flow analysis.</inlineHelpText>
        <label>Cashflow Analysis Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompanyDiscountPaybackPeriodYears__c</fullName>
        <inlineHelpText>The number of years it takes to break-even between the investment and the return using a the Company&apos;s WACC rate.</inlineHelpText>
        <label>Company Discount Payback Period (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompanyIRR__c</fullName>
        <inlineHelpText>Internal Rate of Return calculated when analyzing the return of an investment.</inlineHelpText>
        <label>Company IRR (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CompanyInvestmentAmortizationYears__c</fullName>
        <label>Company Investment Amortization Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompanyLocalEffectiveTaxRate__c</fullName>
        <inlineHelpText>Effective tax rate provided by the Corporate Tax used in financial analysis.</inlineHelpText>
        <label>Company Local Effective Tax Rate (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CompanyParticipationAmountUSD__c</fullName>
        <formula>CompanyParticipationAmountFC__c 
/*
CompanyParticipationAmountFC__c * ARERate__c
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Company&apos;s portion of the cost, as opposed to the bottler.</inlineHelpText>
        <label>Company Participation Amount (USD $)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompanyParticipation__c</fullName>
        <inlineHelpText>The Company&apos;s percentage portion of the cost, as opposed to the bottler.</inlineHelpText>
        <label>Company Participation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CompanyWACC__c</fullName>
        <inlineHelpText>Weighted average cost of capital provided by Treasury to be used in the financial analysis.</inlineHelpText>
        <label>Company WACC (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EquipmentPlacementPeriodYears__c</fullName>
        <inlineHelpText>The number of year equipment placement will occur.</inlineHelpText>
        <label>Equipment Placement Period (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpectedCommitmentDate__c</fullName>
        <inlineHelpText>The date of the Commitment, as defined by CCEJ&apos;s COA, is expected to be made. For example, an agreement to be signed Feb. 1, but with an effective date of 3 months later, the Expected Commitment Date is February 1.</inlineHelpText>
        <label>Expected Commitment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsthisanAnnualCapitalPlanrequest__c</fullName>
        <inlineHelpText>Used to flag annual capital plan requests for reporting purposes.</inlineHelpText>
        <label>Is this an Annual Capital Plan request?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NumberofUnitsofEquipment__c</fullName>
        <inlineHelpText>The number of units covered in the CAPPrs agreement.</inlineHelpText>
        <label>Number of Units of Equipment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PerformanceReportingPeriodMonths__c</fullName>
        <inlineHelpText>The number of performance months covered by the CAPPrs agreement.</inlineHelpText>
        <label>Performance Reporting Period (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermoftheAgreementYears__c</fullName>
        <inlineHelpText>The length of the CAPPrs agreement.</inlineHelpText>
        <label>Term of the Agreement (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecievedDateTime__c</fullName>
        <label>ApprovalRecieved DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TECH_IsComplete__c</fullName>
        <formula>/*
updated by Jia Hu on 2013/12/03
*/
/*
IF(
  AND(
    NOT( OR (
      ISPICKVAL(ApprovalRecommendation__c, &quot;Awaiting Approval&quot;)
      ,
      ISPICKVAL(ApprovalRecommendation__c, &quot;承認待ち&quot;)
      )
    ),   
    NOT(
      ISPICKVAL(ApprovalRecommendation__c, &quot;&quot;)
    )
  ), 
  &quot;true&quot;, 
  &quot;false&quot;
)
*/

IF(
  AND(
    NOT(
      ISPICKVAL(ApprovalRecommendation__c, &quot;Awaiting Approval / 承認待ち&quot;)
    )
    ,   
    NOT(
      ISPICKVAL(ApprovalRecommendation__c, &quot;&quot;)
    )
  ), 
  &quot;true&quot;, 
  &quot;false&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complete</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CocacolaProject/src/classes/RFA_Util_ObjectQuery.cls
/*
    Author           : Accenture
    Date Created  : 05/15/2012
    Description     : This class determines the logged in user's access level on the RFA.
                           This class is extended by the Other classes to inherit the security of the logged in user to perform actions.
    Version History: 1.0
    
    updated by Jia Hu on 2013/11/08
*/
public class RFA_Util_ObjectQuery
{
    /* @Method <This method return the details of an Attchment given the SFDC Id of attachment as Input>
        @param <Id - SFDC Id of the Atatchment> 
        @return Attachment - Return data of sObjetc type Attachment
        @Called from - <RFA_WS05>
    */
    public Attachment getAttachment(Id attId)
    {
         return [SELECT Id, Name, BodyLength, Body, ContentType, Description 
         	FROM Attachment where Id=:attId Limit 1];
    }
    
    /* @Method <This method return the details of an RFA__c along with related Child records given the SFDC Id of RFA as Input>
        @param <Id - SFDC Id of the RFA> 
        @return Attachment - Return data of sObjetc type RFA__c along with childs Three Year Cash Spend, Attachments, RFA User Role
        @Called from - 
    */
    public RFA__c getRFAwChilds(Id rfaId)
    {
        return [Select Id,
               //PrimaryReportingUnitName__c, PrimaryReportingUnitNumber__r.Name, PrimaryReportingUnitNumber__c,
               //ThirdReportingUnitName__c, ThirdReportingUnitNumber__r.Name, ThirdReportingUnitNumber__c ,SecondReportingUnitName__c, 
               //SecondReportingUnitNumber__r.Name, SecondReportingUnitNumber__c,
               CreatedDate, CreatedById, CreatedBy.Name,
               //CreatedBy.FederationIdentifier, 
               CreatedBy.Email,
               //Level__c,
               BudgetType__c,RecordType.name, RequestTitle__c ,
               //ControlNumber__c ,
               RequestAmountFunctionalCurrency__c ,
               //RequestAmountUSD__c ,
               ProfitCenterName__c,ProfitCenterNumber__c, ProfitCenterNumber__r.Name ,
               //ExecutiveSummary__c , 
               //Group__c, 
               IsthisanAnnualCapitalPlanrequest__c ,
               //BusinessCase__c ,
               //PrimaryDOACategorySubCategory__c,
               //SecondDOACategorySubCategory__c, ThirdDOACategorySubCategory__c,
               Owner.Name, ExpectedCommitmentDate__c,
               //Functional_Currency__r.Name, 
               NumberofUnitsofEquipment__c, TermoftheAgreementYears__c, PerformanceReportingPeriodMonths__c, EquipmentPlacementPeriodYears__c, 
               BottlerParticipation__c, BottlerParticipationAmountUSD__c, BottlerIRR__c, 
               //BottlerNPVUSD__c, 
               BottlerDiscPaybackPeriodYears__c, BottlerInvestmentDepreciationYears__c, 
               BottlerWACC__c, BottlerLocalEffectiveTaxRate__c, 
               //BottlerROINPVCAPPr__c, 
               CompanyParticipation__c, CompanyParticipationAmountUSD__c, CompanyIRR__c, 
               //CompanyNPVUSD__c, 
               CompanyDiscountPaybackPeriodYears__c, CompanyInvestmentAmortizationYears__c, CashflowAnalysisYears__c, CompanyWACC__c, CompanyLocalEffectiveTaxRate__c, 
               //CompanyROINPVCAPPr__c, 
               	(Select id,X3YearCashSpendFunc__c,
               		//X3YearCashSpendUSD__c, 
               		Year__c from Three_Year_Cash_Spend__r),
               	(Select 
               		//Level__c,
               		id, UserName__c, UserName__r.Name, UserName__r.Email,
               		//UserName__r.FederationIdentifier, 
               		Agent1__c, Agent1__r.Name, Agent2__c, Agent2__r.Name, Agent3__c, 
               		Agent3__r.Name, ApprovalProcess__c, RecordType.DeveloperName, TECH_IsComplete__c, ApprovalRecommendation__c, ApprovalRecievedDateTime__c, 
               		ApprovedBy__c, ApprovedBy__r.Name, ApprovedBy__r.email,
               		//ApprovedBy__r.FederationIdentifier, 
               		ApprovalComments__c 
               		from RFA_User_Roles__r 
               		//ORDER BY Level__c DESC NULLS LAST 
               	),
               	(Select id,name from Attachments) 
               FROM RFA__c where Id = :rfaId Limit 1];
    }
    
    /* @Method <This method return the details of an RFAUserRole__c record given the SFDC Id of UserRoleRecordId as Input>
        @param <Id - SFDC Id of the RFAUserRole__c> 
        @return RFAUserRole__c - Return data of sObjetc type RFAUserRole__c
        @Called from - <RFA_WS04>
    */
    
    public RFAUserRole__c getUserRole(id workItemId)
    {
        return [
        	Select id, ApprovalRecievedDateTime__c, TECH_IsComplete__c, 
        	RFA__c, 
        	//RFA__r.Level__c, 
        	RFA__r.Stage__c, ApprovalRecommendation__c, ApprovalComments__c 
        	from RFAUserRole__c where Id =:workItemId];
        
    }
    
    //removed by Jia Hu on 2013/11/14
    /* @Method <This method return the details of an User record given the SFDC federation Id of as Input>
        @param <String - SFDC federationId of the User Object> 
        @return User - Return data of sObjetc type User
        @Called from - <RFA_WS04>
    */
    /*
    public User getUserDetails(String federatedId)
    {
        return [Select id,Email,
        	FederationIdentifier 
        	from user where FederationIdentifier=:federatedId limit 1];        
    }
    */
    
    //removed by Jia Hu on 2013/11/14
    /* @Method <This method return grouped Approvers based on the RFA Ids and Status>
        @param <Set - RFA Ids, String - Status of Approval process.> 
        @return AggregateResult
        @Called from - 
    */
    /*
    public List<AggregateResult> getGroupedApprovers(Set<Id> rfaIds, String status)
    {
        AggregateResult[] results = [
        	Select Max(ApprovalOrder__c) maxOrder, RFA__c rfa,
        			ApprovalProcess__c processInstance                                                                                                           
                                     FROM RFAUserRole__c
                                     WHERE ApprovalProcess__r.Status__c = : status
                                     AND RFA__c IN : rfaIds
                                     GROUP BY RFA__c, ApprovalProcess__c                                  
                                     LIMIT : (limits.getLimitQueryRows() - limits.getQueryRows())];
                                     
        return results;                              
    }
    */

    //removed by Jia Hu on 2013/11/14
    /*  @Method <This method return RFA details with user role object which will having approval awating status >
         
         @return <List - RFA__c>
         @Called from - WS02 
    */ 
    /*
    public List<RFA__c> getAllRFADetailsForAwaitingApprovers()
    {
        List<RFA__c> rfalist = [
        	Select id,Level__c,RequestTitle__c ,CreatedDate,
        		(Select id from Attachments),
        		(Select id,UserName__C,UserName__r.Email,
        			//UserName__r.FederationIdentifier,
        			Agent1__c,Agent2__c,Agent3__c,Agent1__r.Email,
        			//Agent1__r.FederationIdentifier,
        			Agent2__r.Email,
        			//Agent2__r.FederationIdentifier,
        			Agent3__r.Email //,
        			//Agent3__r.FederationIdentifier 
        		from RFA_User_Roles__r where ApprovalRecommendation__c='Awaiting Approval') 
        		from RFA__c];
        
        return rfaList;                                                                                          
    }    
    */
       
}