MilestoneRFA_CM01/src/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ActiveInactive__c</fullName>
        <label>Active/Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Agents_Name__c</fullName>
        <label>Agents Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalLetterComments__c</fullName>
        <inlineHelpText>Comments describing conditional approval requirements.</inlineHelpText>
        <label>Follow-up: Approver Comments/Conditions</label>
        <picklist>
            <picklistValues>
                <fullName>The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The requesting party must fully comply with the above approval conditions, although explicit communication or follow up with these approvers is not required.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <label>Approver Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCEmailAddressCM__c</fullName>
        <label>CCEmailAddressCM</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CommentsConditions__c</fullName>
        <inlineHelpText>Text provided by approvers of approval condition that must be accomplished before transaction initiation.</inlineHelpText>
        <label>Comments/Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DataClassification__c</fullName>
        <inlineHelpText>Select the appropriate Data Classification for this request. Note: Highly Restricted information cannot be entered into the sytem. If your request is Highly Restricted  or contains Highly Restricted information please contact your Location Coordinator.</inlineHelpText>
        <label>Data Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOC_Name__c</fullName>
        <label>LOC Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>POC_Name__c</fullName>
        <label>POC Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theapprovalstatusofyourrequestis__c</fullName>
        <description>Approval Status of the RFA Request</description>
        <inlineHelpText>Displays the approval status of the RFA (unconditionally approved, conditionally approved, etc.)</inlineHelpText>
        <label>This request has been</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed / Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / Not Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thefollowingitem__c</fullName>
        <inlineHelpText>Select level/stage the RFA was approved through according to the DOA/LCOA.</inlineHelpText>
        <label>This request was circulated to</label>
        <picklist>
            <picklistValues>
                <fullName>Approval and / or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Directors for approval as required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ToEmailAddressCM__c</fullName>
        <label>ToEmailAddressCM</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullSandCoke/src/classes/RFA_WS04_PDFGeneratorCM_Test.cls
/**
    updated by Jia Hu on 2013/11/12
 */
@isTest(SeeAllData=false) 
public class RFA_WS04_PDFGeneratorCM_Test {
    static testMethod void myUnitTest() {
        /*
        RFATestData testData = new RFATestData();
        String rt = RFAConstants.getRecordType('General Request', 'RFA__c');
        RFA__c testRFA = new RFA__c();
        testRFA.RequestTitle__c = 'testtitle';
        testRFA.DataClassification__c = 'Restricted';
        //testRFA.RequestAmountFunctionalCurrency__c = '10';
        //testRFA.Functional_Currency__c = '100';
        //testRFA.AREMonth__c = 'January';
        testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
        testRFA.RecordTypeId =   rt;
        testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
        testRFA.Stage__c = 'Draft';
        try{
            insert testRFA;
           }
        catch(System.DMLException e) {}


        // POC 
        User testUserPOC = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'ppoc', 'ppoc');
        String utPOC = RFAConstants.getRecordType('Primary Point of Contact', 'RFAUserRole__c');
        RFAUserRole__c TestURPOC = new RFAUserRole__c();
        TestURPOC.UserName__c = testUserPOC.id;
        TestURPOC.RecordTypeId =   utPOC;
        TestURPOC.RFA__c = testRFA.id;
        insert TestURPOC; 

        // Co-Creater 
        User testUserCOC = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'Co-Cre', 'Co-Cre');
        String utCOC = RFAConstants.getRecordType('Co-Creator', 'RFAUserRole__c');
        RFAUserRole__c TestURCOC = new RFAUserRole__c();
        TestURCOC.UserName__c = testUserCOC.id;
        TestURCOC.RecordTypeId =   utCOC;
        TestURCOC.RFA__c = testRFA.id;
        insert TestURCOC; 
        
        // Approver 
        //User testUserApprover = new User();
        //RFATestData.rfaStandardUserProfile  -> RFAConstants.getRFAStandardUserProfileId()
        User testUserApprover = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'Approver', 'Approver');
        String utApp = RFAConstants.getRecordType('Approver', 'RFAUserRole__c');
        RFAUserRole__c TestURApp = new RFAUserRole__c();
        TestURApp.UserName__c = testUserApprover.id;
        TestURApp.RecordTypeId =   utApp;
        TestURApp.Agent1__c = testUserCOC.id;
        TestURApp.RFA__c = testRFA.id;
        insert TestURApp; 
        
        // LOC 
        ProfitCenter__c testProfitCenter = new ProfitCenter__c();
        //testProfitCenter.Business_Unit_Name__c = 'Coca-Cola USA Industries';
        //testProfitCenter.GroupName__c = 'Bottling Investments';
        //testProfitCenter.KeyOperationName__c = 'Coca Cola NA';
        testProfitCenter.ProfitCenterName__c = 'Test Coke PC';
        testProfitCenter.ActiveInactive__c = 'Active';
        insert testProfitCenter;
        
        User testUserLOCA = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'LOC', 'LOC');
        
        ProfitCenterUserRole__c PCUR = new ProfitCenterUserRole__c();
        //PCUR.Level__c = 'CCEJ'; //1. Key Operations
        PCUR.ProfitCenter__c = testProfitCenter.id;
        PCUR.UserName__c = testUserLOCA.Id;
        PCUR.UserType__c = 'Coordinator'; //Location Coordinator
        insert PCUR;
        */
        /*
        //RFA__c testRFA = RFATestData.buildRFACapital();
        RFA__c testRFA = RFATestData.buildRFAGeneral();
        
        testRFA.ToEmailAddressCM__c = 'bisht Sanjeev';
        testRFA.CCEmailAddressCM__c = 'bisht Sanjeev';
        
        //testRFA.POC_Name__c = TestURPOC.UserName__r.Name;
        //testRFA.CO_CREATOR_Name__c = TestURCOC.UserName__r.Name;
        //testRFA.Approver_Name__c = TestURApp.UserName__r.Name;
        //testRFA.Agents_Name__c = TestURApp.Agent1__c;
        //testRFA.LOC_Name__c = PCUR.UserName__r.Name;
        
        testRFA.Thefollowingitem__c = 'Key operation level for Approval and/or for information as requied';
        testRFA.Theapprovalstatusofyourrequestis__c = 'Conditionally Approved';
        testRFA.ApprovalLetterComments__c = 'Not Applicable';
        testRFA.CommentsConditions__c = 'Test';
    
        try{
            update testRFA;
           }
        catch(System.DMLException e) {}
        */
    }
        
    static testMethod void testAttachments()
    {
            //RFA__c testRFA = new RFA__c();
            //insert testRFA;
            
            //RFA__c testRFA = RFATestData.buildRFACapital();
            RFA__c testRFA = RFATestData.buildRFAGeneral();
     
            Attachment attach = new Attachment();     
            attach.Name = 'Unit Test Attachment';
            Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
            attach.body = bodyBlob;
            attach.parentId = testRFA.id;
            insert attach;
            
            List<Attachment> attachments=[select id, name from Attachment where parent.id=:testRFA.id];
            //System.assertEquals(1, attachments.size());
    }
    
    static testMethod void myUnitTest1() {
        //RFA__c rfa = RFATestData.buildRFACapital();
        RFA__c rfa = RFATestData.buildRFAGeneral();
        RFA_WS04_PDFGeneratorCM.PDFGenerator(rfa.Id, Userinfo.getSessionId());
    }
}