MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>RM_Invest_Total__c</fullName>
        <label>Invest. Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Investment_Amounts__c</fullName>
        <label>Investment Amounts(Per \1,000 JPY)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_L3_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>L3 Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>This field is used in VF Page (RFA-VFP03-ApprovalRouting) to show the field name correctly.</description>
        <formula>RecordType.Name</formula>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_RFA_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA 1</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Related RFA</relationshipLabel>
        <relationshipName>Related_RFA_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RM_Milestone_Synergy_Management_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>1.Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Category_Detail__c</fullName>
        <label>Asset Category Detail</label>
        <picklist>
            <controllingField>RM_Asset_Category__c</controllingField>
            <picklistValues>
                <fullName>01.Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings - Plant/Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings - Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Water Supply/Electrical Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Air Conditioning Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Partition/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures - Drain Ditch/Concrete Pavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures - Signboard/Asphalt Pavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery - Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery - Beverage Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.Sales Equipment - Can/Cup VM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07.Sales Equipment - Coolers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.Sales Equipment - Dispensers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09.Sales Equipment - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.IT Hardware - Server/PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Desk/Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Locker/Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Refrigerator/Air Conditioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Coin Counting Machine/Inspection Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.Fleet - Automobiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.Fleet - Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.Fleet - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.IT Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.Other (Not Fixed Assets)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Category__c</fullName>
        <label>Asset Category</label>
        <picklist>
            <picklistValues>
                <fullName>01.Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.Buildings &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery &amp; Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.Sales Equipment - Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07.Sales Equipment - Coolers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.Sales Equipment - Dispensers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09.Sales Equipment - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.IT Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture &amp; Fixtures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.Fleet - Automobiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.Fleet - Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.Fleet - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.IT Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.Other (Not Fixed Assets)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Name__c</fullName>
        <label>Asset Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_Depreciation_Rule__c</fullName>
        <label>Depreciation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New straight-line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>straight-line(5 years)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Detail__c</fullName>
        <label>Detail</label>
        <picklist>
            <picklistValues>
                <fullName>test1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>test2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Entity__c</fullName>
        <label>Entity</label>
        <picklist>
            <picklistValues>
                <fullName>test1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>test2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Invest_Total__c</fullName>
        <formula>RM_This_Year__c +  RM_Next_Year__c + RM_The_Year_After_Next__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invest. Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_Next_Year__c</fullName>
        <label>Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA No.</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Milestone Synergy Management History</relationshipLabel>
        <relationshipName>Milestone_Synergy_Management_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RM_Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_The_Year_After_Next__c</fullName>
        <label>The Year After Next</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Formula__c</fullName>
        <formula>IF(OR(ISBLANK(RM_This_Year__c),RM_This_Year__c==0,RM_This_Year__c == null),
RM_This_Year_Q1__c +  RM_This_Year_Q2__c +  RM_This_Year_Q3__c +  RM_This_Year_Q4__c,
RM_This_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>This Year(Formula)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q1__c</fullName>
        <label>This Year Q1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q2__c</fullName>
        <label>This Year Q2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q3__c</fullName>
        <label>This Year Q3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q4__c</fullName>
        <label>This Year Q4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year__c</fullName>
        <label>This Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Total__c</fullName>
        <formula>RM_This_Year_Formula__c  +  RM_Next_Year_Formula__c + RM_The_Year_After_Next__c  +   RM_Three_Years_Later__c + RM_Four_Years_Later__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Useful_Life__c</fullName>
        <label>Useful Life</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Milestone Synergy Management History</label>
    <nameField>
        <displayFormat>Milestone-Synergy-{0000000000}</displayFormat>
        <label>Milestone Synergy Management History No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/classes/RFA_TriggerHandler_Helper_CapitalBudget.cls
public without sharing class RFA_TriggerHandler_Helper_CapitalBudget {


    /*
        ============ isBefore & isInsert ============ 
    */

    public static void processRFAsInBeforeInsertTrigger(List<RFA__c> listNewRFAs) {
            
        
    }
    
    
    /*
        ============ isAfter & isInsert ============ 
    */

    public static void processCapitalBudgetInitiateRFAsInAfterInsertTrigger(List<RFA__c> listNewRFAs) {
         system.debug('●rfa.listNewRFAs●' + listNewRFAs);
    for(RFA__c rfa :listNewRFAs) {
        system.debug('●rfa.Record_Type__c●' + rfa.Record_Type__c);
        if(rfa.Record_Type__c == '04. Capital Budget Initial Request' && rfa.RM_L3_Approved__c == true){
            
            //List<RM_Milestone_Synergy_Management_History__c> oldMsmhList = new List<RM_Milestone_Synergy_Management_History__c>();
            List<RM_Milestone_Synergy_Management_History__c> newMsmhList = new List<RM_Milestone_Synergy_Management_History__c>();
            for (RM_Milestone_Synergy_Management_History__c r:[SELECT 
                            RM_Year__c,
                            RM_Name__c,
                            RM_Asset_Name__c,
                            RM_Asset_Category__c,
                            RM_Asset_Category_Detail__c,
                            RM_Entity__c,
                            RM_Detail__c,
                            RM_Acquisition_Method__c,
                            RM_Depreciation_Rule__c,
                            RM_Useful_Life__c,
                            RM_This_Year__c,
                            RM_Next_Year__c,
                            RM_The_Year_After_Next__c,
                            RM_Invest_Total__c,
                            CreatedDate,
                            RM_RFA__c,
                            RM_This_Year_Q1__c,
                            RM_This_Year_Q2__c,
                            RM_This_Year_Q3__c,
                            RM_This_Year_Q4__c,
                            RM_This_Year_Formula__c,
                            RM_Total__c,
                            RM_Remarks__c
                        from
                            RM_Milestone_Synergy_Management_History__c
                        where
                            RM_RFA__c = :rfa.Related_RFA_1__c]){
                            
                            RM_Milestone_Synergy_Management_History__c newMsmh = new RM_Milestone_Synergy_Management_History__c();
                            
                            r.RM_RFA__c = rfa.Id;
                            newMsmh = r.clone();

                                newMsmhList.add(newMsmh);
                                
                            }
            
            system.debug('●newMsmhList●:' + newMsmhList);
            insert newMsmhList;
    

        }
    }
        
        
    }

    
    /*
        ============ isBefore & isUpdate ============ 
    */
	public static void processCapitalBudgetInitiateRFAsInAfterUpdate(		
		List<RFA__c> listNewRFAs, 
		Map<Id, RFA__c> mapOldRFAs
	) {		
		for(RFA__c rfa : listNewRFAs) {
			//Capital Budget Initiate Request need to check Attachment Status!
			if(
				(
				rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION 
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_DRAFT
				&& ( 
					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Budget_Initiate_REQUEST)
				   )											
				)	
				||
				(
				rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION 
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_ReturnToRequester
				&& ( 
 					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Budget_Initiate_REQUEST)	
				   )	
				)									
			) {
				
				//if(rfa.RM_Investment_Amounts__c != rfa.RM_Invest_Total__c) {
				//	rfa.addError('Investment Amounts not equals to Investment Total!');	
				//}
				
				//Invest. Total in Table (CAPEX and Cash Spend Schedule (Per \1,000 JPY)) should be same with Investment Amounts(Per \1,000 JPY)
				Decimal decInvestmentTotal = 0;
				for(RM_Milestone_Synergy_Management_History__c child : [
					Select Id, RM_Total__c, RM_Invest_Total__c 
					from RM_Milestone_Synergy_Management_History__c 
					where RM_RFA__c =: rfa.Id
					]
				) {
					system.debug('------- child.RM_Invest_Total__c: ' + child.RM_Invest_Total__c);
					//decInvestmentTotal = decInvestmentTotal + child.RM_Total__c;
					decInvestmentTotal = decInvestmentTotal + child.RM_Invest_Total__c;
				}

				if(rfa.RM_Investment_Amounts__c != decInvestmentTotal) {
					rfa.addError(
						Label.RM_Imvestment_AmountsError
						//'Investment Amounts not equals to Investment Total!'
					);	
				}				
				
				system.debug('------- rfa.RM_Investment_Amounts__c: ' + rfa.RM_Investment_Amounts__c);
				system.debug('------- decInvestmentTotal: ' + decInvestmentTotal);
				
				List<Attachment> listAttachments = [Select Id from Attachment where ParentId =: rfa.Id];

				if(listAttachments == null || (listAttachments != null && listAttachments.size() == 0)) {

					rfa.addError(
						Label.RM_Attached_File
						//'No attachments !'
						);	

				}				
								
			}//end of if();
			
		}//end of for(RFAs);		
		
		
		
		
	}
    
    
    /*
        ============ isAfter & isUpdate ============ 
    */

    
    
    /*
        ============ isBefore & isDelete ============ 
    */


    
    
    /*
        ============ isAfter & isDelete ============ 
    */



    /*
        ============ isAfter & isUnDelete ============ 
    */  



}