MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/classes/RFA_AP04_UTIL_PdfCompletionMemo_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
@isTest(SeeAllData=false) 
private class RFA_AP04_UTIL_PdfCompletionMemo_Test {

    static testMethod void myUnitTest() {
    	/*
        // TO DO: implement unit test
		String rt = RFAConstants.getRecordType('General Request', 'RFA__c');
      
        RFA__c testRFA = new RFA__c();
      	testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
      	testRFA.RecordTypeId =   rt;
      
      	testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
      	//testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
      	testRFA.Stage__c = 'Draft';
      	insert testRFA;
      	*/
      	
        RFATestData inst = new RFATestData();
        inst.buildCostCenter('Finance');
        inst.buildProfitCenter();
        inst.buildTaxRate();
        
        RFA__c testRFA = RFATestData.createTestRFAwithType('Draft', 'General Request', 1200);      	
      
        RFA_AP04_UTIL_PdfCompletionMemo.savePDF(testRFA.Id);
    }
}