MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Seal_Name_CCEJ_Company_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Seal_Name_CCEJ_Company_Check</description>
        <label>CCEJ Company Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seal_Name_CCEJ_Function_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Seal_Name_CCEJ_Function_Check</description>
        <label>CCEJ Function Check</label>
        <type>Checkbox</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RFAStage__c</fullName>
        <formula>TEXT(RFA__r.Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RFAStage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM01_04/src/objects/RM_Milestone_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Related_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>Milestone-History-{0000000000}</displayFormat>
        <label>Milestone History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CokeFull/src/classes/RFA_TriggerHandler_RFAUserRole_SealReqt.cls
public with sharing class RFA_TriggerHandler_RFAUserRole_SealReqt {
	
	/*
		============ isBefore & isInsert ============ 
	*/

	
	
	/*
		============ isAfter & isInsert ============ 
	*/


	
	/*
		============ isBefore & isUpdate ============ 
	*/

	
	
	/*
		============ isAfter & isUpdate ============ 
	*/
	public static void checkFinalApproverOrderInAfterUpdate(
		List<RFAUserRole__c> listPaperlessApprovers, 
		Map<Id, RFAUserRole__c> mapOldRFAUserRoles
	) {
		//can not target stage change from Draft -> Circulation from RFAUserRole__c
		//make sure no null ApprovalOrder__c in approver list!
		for(RFAUserRole__c approver :  listPaperlessApprovers) {
			if(approver.RFAStage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION 
				&& approver.ApprovalOrder__c != mapOldRFAUserRoles.get(approver.Id).ApprovalOrder__c
			) {
				List<RFAUserRole__c> listFinalApprovers = [
					Select Id, UserName__c, UserName__r.Name, ApprovalOrder__c, 
						RFA__r.Seal_Name_CCEJ_Company_Check__c, RFA__r.Seal_Name_CCEJ_Function_Check__c 
					from RFAUserRole__c 
					where RFA__c =: approver.RFA__c 
						and RecordTypeId =: Utility_Helper_RecordType.mapRFAUserRoleRecordTypeAPINameToIds.get(
							RFA_Utility_Constants.RFAUserRole_RTAPIName_Approver)
					order by ApprovalOrder__c desc limit 3
				];
				
				//Last two and last three may have the same order
				if(listFinalApprovers != null) {
					if(listFinalApprovers.size() == 0 || listFinalApprovers.size() == 1) {
						approver.addError(
							Label.Seal_Trigger_Info_Approver_Order_Error
						);						
					} else if(listFinalApprovers.size() == 2) {
						
						checkApproverOrder(approver, listFinalApprovers);
						
					} else if(listFinalApprovers.size() == 3) {
						
						if(listFinalApprovers[0].ApprovalOrder__c == listFinalApprovers[1].ApprovalOrder__c
							|| listFinalApprovers[0].ApprovalOrder__c == listFinalApprovers[2].ApprovalOrder__c
							|| listFinalApprovers[1].ApprovalOrder__c == listFinalApprovers[2].ApprovalOrder__c													
						) {
							approver.addError(
								Label.Seal_Trigger_Info_Approver_Order_Error
							);		
												
						} else if(listFinalApprovers[0].ApprovalOrder__c < listFinalApprovers[1].ApprovalOrder__c 
							&& listFinalApprovers[0].ApprovalOrder__c < listFinalApprovers[2].ApprovalOrder__c
						) {
							
							List<RFAUserRole__c> listFinalApproversNew = new List<RFAUserRole__c>();
							listFinalApproversNew.add(listFinalApprovers[1]);
							listFinalApproversNew.add(listFinalApprovers[2]);
							checkApproverOrder(approver, listFinalApproversNew);
							
						} else if(listFinalApprovers[1].ApprovalOrder__c < listFinalApprovers[0].ApprovalOrder__c 
							&& listFinalApprovers[1].ApprovalOrder__c < listFinalApprovers[2].ApprovalOrder__c
						) {
							List<RFAUserRole__c> listFinalApproversNew = new List<RFAUserRole__c>();
							listFinalApproversNew.add(listFinalApprovers[0]);
							listFinalApproversNew.add(listFinalApprovers[2]);
							checkApproverOrder(approver, listFinalApproversNew);
							
						} else if(listFinalApprovers[2].ApprovalOrder__c < listFinalApprovers[0].ApprovalOrder__c 
							&& listFinalApprovers[2].ApprovalOrder__c < listFinalApprovers[1].ApprovalOrder__c
						) {
							List<RFAUserRole__c> listFinalApproversNew = new List<RFAUserRole__c>();
							listFinalApproversNew.add(listFinalApprovers[0]);
							listFinalApproversNew.add(listFinalApprovers[1]);
							checkApproverOrder(approver, listFinalApproversNew);							
						}												
					}
					
				} else {
					approver.addError(
						Label.Seal_Trigger_Info_Approver_Order_Error
					);
				}
				/*
				system.debug('----- current Approvers order : ' + approver.ApprovalOrder__c + '  User: ' + approver.UserName__c);	
				system.debug('----- Final Approvers: ' + listFinalApprovers);								
				system.debug('----- a: ' + listFinalApprovers[0].ApprovalOrder__c 
					+ ' Name: ' + listFinalApprovers[0].UserName__r.Name);
				system.debug('----- b: ' + listFinalApprovers[1].ApprovalOrder__c 
					+ ' Name: ' + listFinalApprovers[1].UserName__r.Name);
				system.debug('----- c: ' + listFinalApprovers[0].ApprovalOrder__c 
					+ ' Name: ' + listFinalApprovers[0].RFA__r.Seal_Name_CCEJ_Company_Check__c);
				system.debug('----- d: ' + listFinalApprovers[1].ApprovalOrder__c 
					+ ' Name: ' + listFinalApprovers[1].RFA__r.Seal_Name_CCEJ_Function_Check__c);				
				*/												
			}//end of if();
		}//end of for(Approvers);		
	}
			
	private static void checkApproverOrder(RFAUserRole__c approver, List<RFAUserRole__c> listFinalApprovers) {
		if(listFinalApprovers != null && listFinalApprovers.size() == 2) {
								
			if(listFinalApprovers[0].RFA__r.Seal_Name_CCEJ_Company_Check__c == true 
				|| listFinalApprovers[0].RFA__r.Seal_Name_CCEJ_Function_Check__c == true
			) {
						
				if(listFinalApprovers[0].ApprovalOrder__c < listFinalApprovers[1].ApprovalOrder__c) {
					if(
						listFinalApprovers[0].UserName__c == Label.Seal_Second_To_Final_Approver_of_CCEJ_Company
							//RFA_Utility_Configure.idSealAdmin //'005N0000000tPNB' 
						&& 
						listFinalApprovers[1].UserName__c == Label.Seal_Final_Approver_of_CCEJ_Company
							//RFA_Utility_Configure.idKawamotoNaruhiko //'00510000001rhvJ'
					) {
								
						system.debug('-----e 1: ' + listFinalApprovers[0].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[0].UserName__r.Name);
						system.debug('-----e 2: ' + listFinalApprovers[1].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[1].UserName__r.Name);
								
					} else {
								
						system.debug('-----e 3: ' + listFinalApprovers[0].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[0].UserName__r.Name);
						system.debug('-----e 4: ' + listFinalApprovers[1].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[1].UserName__r.Name);
																
						approver.addError(
							Label.Seal_Trigger_Info_Approver_Order_Error
									//'Approval Order is not right 1 !'
						);								
					}							
				} else if(listFinalApprovers[0].ApprovalOrder__c > listFinalApprovers[1].ApprovalOrder__c) {
					if(
						listFinalApprovers[0].UserName__c == Label.Seal_Final_Approver_of_CCEJ_Company
							//RFA_Utility_Configure.idKawamotoNaruhiko //'00510000001rhvJ' 
						&& 
						listFinalApprovers[1].UserName__c == Label.Seal_Second_To_Final_Approver_of_CCEJ_Company
							//RFA_Utility_Configure.idSealAdmin //'005N0000000tPNB'
					) {
								
						system.debug('-----e 5: ' + listFinalApprovers[0].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[0].UserName__r.Name);
						system.debug('-----e 6: ' + listFinalApprovers[1].ApprovalOrder__c 
							+ ' Name: ' + listFinalApprovers[1].UserName__r.Name);								
								
					} else {
						system.debug('-----e 7: ');
						approver.addError(
							Label.Seal_Trigger_Info_Approver_Order_Error
									//'Approval Order is not right 1 !'
						);								
					}								
				} else if(listFinalApprovers[0].ApprovalOrder__c == listFinalApprovers[1].ApprovalOrder__c) {
					system.debug('-----e 8: ');
					approver.addError(
						Label.Seal_Trigger_Info_Approver_Order_Error
								//'Approval Order is not right 1 !'
					);
				}
						
			} else { //need to update !  List order
						
				if(listFinalApprovers[0].ApprovalOrder__c < listFinalApprovers[1].ApprovalOrder__c) {
					if(
						listFinalApprovers[0].UserName__c == Label.Seal_Second_To_Final_Approver_of_Sub_Company						
							//RFA_Utility_Configure.idSealAdmin //'005N0000000tPNB' 
						&& 
						listFinalApprovers[1].UserName__c == Label.Seal_Final_Approver_of_Sub_Company
							//RFA_Utility_Configure.idNakanoToshio //'00510000001rhvi'
					) {

					} else {
						system.debug('-----e 9: ');
						approver.addError(
							Label.Seal_Trigger_Info_Approver_Order_Error
									//'Approval Order is not right 2 !'
						);								
					}	
																				
				} else if(listFinalApprovers[0].ApprovalOrder__c > listFinalApprovers[1].ApprovalOrder__c) {
					if(
						listFinalApprovers[0].UserName__c == Label.Seal_Final_Approver_of_Sub_Company
							//RFA_Utility_Configure.idNakanoToshio //'00510000001rhvi' 
						&& 
						listFinalApprovers[1].UserName__c == Label.Seal_Second_To_Final_Approver_of_Sub_Company
							//RFA_Utility_Configure.idSealAdmin //'005N0000000tPNB'
					) {

					} else {
						system.debug('-----e 10: ');
						approver.addError(
							Label.Seal_Trigger_Info_Approver_Order_Error
							//'Approval Order is not right 2 !'
						);								
					}								
				} else if(listFinalApprovers[0].ApprovalOrder__c == listFinalApprovers[1].ApprovalOrder__c) {
					system.debug('-----e 11: ');
					approver.addError(
						Label.Seal_Trigger_Info_Approver_Order_Error
						//'Approval Order is not right 2 !'
					);
				}											
			}
					
		} else {
			system.debug('-----e 12: ');
			approver.addError(
				Label.Seal_Trigger_Info_Approver_Order_Error
				//'Approval Order is not right 0 !'
			);
		}		
	}

	
	
	/*
		============ isBefore & isDelete ============ 
	*/


	
	
	/*
		============ isAfter & isDelete ============ 
	*/



	/*
		============ isAfter & isUnDelete ============ 
	*/		
	
}