MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ApprovalRequestedOn__c</fullName>
        <description>RFA R1 - Field to track when Approval is requested to the Approver</description>
        <label>Approval Requested On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM01_04/src/objects/RM_Milestone_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Related_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>Milestone-History-{0000000000}</displayFormat>
        <label>Milestone History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CocaColaProject07/src/classes/RFA_AP11_BatchReminderSchedulable.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_AP11_BatchReminderSchedulable
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 07/05/2012
 *  Assumptions      : N/A
 *  Description      : This class implements the Schedulable interface. This class is scheduled from Salesforce.com interface and executes
                       the batch class RFA_AP10_BatchReminder
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
 
global class RFA_AP11_BatchReminderSchedulable implements Schedulable{
    
    // base query String
    global String queryString = 'Select Agent1__c, Agent2__c, Agent3__c, UserName__c, RFA__c, RFA__r.Name, RFA__r.RequestTitle__c, ApprovalProcess__c FROM RFAUserRole__c WHERE' + ' ';
    
    global static final Integer scope = 400;
    
    global static String CRON_EXP = '0 0 0 3 9 ? 2022';
    
    private String REMINDER_THRESHOLD = RFA_BatchReminder__c.getInstance('Approval Reminder').ReminderThreshold__c;    
    
    //constructor for the class 
    global RFA_AP11_BatchReminderSchedulable() 
    {   
        if(Test.isRunningTest())
        {
            this.queryString = queryString + ' RecordType.Name=' +'\'' + RFAConstants.RTLabel_RFAUserRole_Approver + '\'';
            this.queryString = queryString + ' ' + ' AND ApprovalRecommendation__c=' + '\'' 
            	+ RFAConstants.ApproverRecommend_AwaitingApproval
            	//RFAGlobalConstants.PROCESS_PENDING_RECOMMENDATION 
            	+ '\'';
            this.queryString = queryString + ' ' + ' ORDER BY UserName__c LIMIT 20';     
        }
        else
        {
            this.queryString = queryString + ' RecordType.Name=' +'\'' + RFAConstants.RTLabel_RFAUserRole_Approver + '\'';
            this.queryString = queryString + ' ' + ' AND ApprovalRecommendation__c=' + '\'' 
            	+ RFAConstants.ApproverRecommend_AwaitingApproval
            	//RFAGlobalConstants.PROCESS_PENDING_RECOMMENDATION 
            	+ '\'';
            this.queryString = queryString + ' ' + ' AND ApprovalRequestedOn__c < NEXT_N_DAYS:' + REMINDER_THRESHOLD ;
            this.queryString = queryString + ' ' + ' ORDER BY UserName__c';   
            System.debug('\n Query prepared : ' + queryString);    
        }
                                     
    }
    
    /**
     *  execute Method
     *  @param SchedulableContext sc
     */
    global void execute(SchedulableContext sc)
    {
        System.debug('\n Query prepared : ' + queryString); 
        // create a new instance of RFA_AP10_BatchReminder
        RFA_AP10_BatchReminder batchReminder = new RFA_AP10_BatchReminder(queryString);
        //execute batch
        database.executebatch(batchReminder);       
    }
    
    
}