MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>BudgetType__c</fullName>
        <inlineHelpText>&quot;Initial&quot; is used for projects that are still in the preliminary stages of planning and evaluation when details are not complete,&quot;Formal&quot; is used for projects for which implementation plans and cost assumptions are final or nearly final.</inlineHelpText>
        <label>Budget Type</label>
        <picklist>
            <picklistValues>
                <fullName>Formal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataClassification__c</fullName>
        <inlineHelpText>Select the appropriate Data Classification for this request. Note: Highly Restricted information cannot be entered into the sytem. If your request is Highly Restricted  or contains Highly Restricted information please contact your Location Coordinator.</inlineHelpText>
        <label>Data Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InitialBudgetYear__c</fullName>
        <inlineHelpText>The year the capital / small project is expected to begin spending.</inlineHelpText>
        <label>Initial Budget Year</label>
        <picklist>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsthisanAnnualCapitalPlanrequest__c</fullName>
        <inlineHelpText>Used to flag annual capital plan requests for reporting purposes.</inlineHelpText>
        <label>Is this an Annual Capital Plan request?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CocaColaProject07/src/classes/RFA_AP17_RemoteActionController_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
//@isTest(SeeAllData=true)
@isTest(SeeAllData=false) 
private class RFA_AP17_RemoteActionController_Test {

    static testMethod void sendRFAToKeyOpsCoordinator() {
    	/*
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Draft';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);            
        }
        */
        
        RFA__c testRFA = RFATestData.buildRFACapital();
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Coordinator'); 
        //should change to Send to Coordinator
        
        RFA__c validateRFA = [Select 
        	//Level__c, 
        	Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        //System.assertEquals('CCEJ', validateRFA.Level__c);//1. Key Operations
        
    }
  
	/*  
    static testMethod void sendRFAToBusinessUnitCoordinator() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Pre-Circulation';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);
            
        }
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Business Unit Coordinator');
        
        RFA__c validateRFA = [Select Level__c, Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        System.assertEquals('2. Business Unit', validateRFA.Level__c);
        
    }
    
    static testMethod void sendRFAToGroupCoordinator() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Pre-Circulation';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);
            
        }
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Group Coordinator');
        
        RFA__c validateRFA = [Select Level__c, Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        System.assertEquals('3. Group', validateRFA.Level__c);
        
    }
    
    static testMethod void sendRFAToCorpCoordinator() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Pre-Circulation';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);
            
        }
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Corporate Coordinator');
        
        RFA__c validateRFA = [Select Level__c, Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        System.assertEquals('4. Corporate', validateRFA.Level__c);
        
    }
    
    static testMethod void sendRFAToExecCoordinator() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Pre-Circulation';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);
            
        }
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Executive Coordinator');
        
        RFA__c validateRFA = [Select Level__c, Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        System.assertEquals('5. Executive', validateRFA.Level__c);
        
    }
    
    static testMethod void sendRFAToSrExecCoordinator() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAConstants.getRecordType('Capital Project Request', 'RFA__c');
        RFA__c testRFA; 
        Test.startTest();
        System.runAs(RFATestData.requester)
        {
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Pre-Circulation';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            RFATestData.updateThreeYearCashSpentForRFA(testRFA, 1200);
            RFATestData.updateCapitalExpenditure(testRFA, 1200);
            
        }
        
        RFA_AP17_RemoteActionController.performAction(testRFA.Id, 'Send to Senior Executive Coordinator');
        
        RFA__c validateRFA = [Select Level__c, Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        
        System.assertEquals('6. Senior Executive', validateRFA.Level__c); 
        
    }
    */
}