MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Close_Reason__c</fullName>
        <description>Close Reason by Requester, only available on Draft or Return To Sender</description>
        <label>Close Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CocaColaProjectBidev_2/src/classes/RFA_VFC_RequesterCloseController.cls
//Controller for VF page: RFA_Requester_Close
public class RFA_VFC_RequesterCloseController extends RFA_Util_SecurityMatrix {

    /*~~~~Start of Variable Initialization~~~~*/
    public RFA__c rfaObj {get; set;}    

    //public String selectedStage{get;set;} 
    public String selectedLevel {get; set;}    
    //private Boolean allowAccess = false;
    public boolean hasError {get; private set;}    
    //public String returnReason{get; set;}   
    public String closeReason {get; set;} 
    //private String currentLevel;  
    public String currentStage;   
    //private String lc; //Added by BSA for INC0346541 - 14-Feb-2013  
    /*~~~~End of Variable Initialization~~~~*/
       
    // constructor for the class.
    public RFA_VFC_RequesterCloseController(ApexPages.StandardController controller) 
    {
        super(controller);
        rfaObj = (RFA__c)controller.getRecord();
        
        if(rfaObj.Id <> null)
        {         
            this.currentStage = rfaObj.Stage__c;
        }
    }
    
    public List<SelectOption> getLevel()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(
        	new SelectOption(
        		//RFAGlobalConstants.RFA_STAGE_CLOSED
        		RFAConstants.RFA_STATUS_CLOSED
        		, 
        		RFAConstants.RFA_STATUS_CLOSED
        		//RFAGlobalConstants.RFA_STAGE_CLOSED
        	));  
        /*
        List<Schema.PicklistEntry> ple = RFA__c.Level__c.getDescribe().getPicklistValues();
        for(Schema.Picklistentry entry : ple)
        {
            options.add(new SelectOption(entry.getLabel(), entry.getValue()));
        }*/               
        return options; 
    }
          
    //Close RFA button on VF page: RFA_Requester_Close (Requester Action Button)
    public pageReference updateRFA()
    {
                //reset error variable
                hasError = false;
                // User query to fetch profile Name for logged In user to bypass the custom validation
               // User usr = [Select Profile.Name, id from User where id =: UserInfo.getUserId() Limit 1]; 
                //need support for Japanese here
              //  String UserNameProfile = usr.Profile.Name;
                //System.debug('\n Selected level : ' + selectedLevel + RFAGlobalConstants.RETURN_TO_SENDER);
                //System.debug('\n Selected Stage : ' + selectedStage);
                System.debug('\n returned reason from db : ' + rfaObj.Close_Reason__c);
                System.debug('\n returned reason from ui : ' + closeReason);
 
                //this.profitCenterId = rfaObj.ProfitCenterNumber__c;                
                //Map<Id, List<ProfitCenterUserRole__c>> profitCenterMap 
                //    = new Map<Id, List<ProfitCenterUserRole__c>>();
               
                if(ApexPages.hasMessages()) 
                {
                    hasError = true;
                    return null;                                       
                }
                
                if(
                	(
                    currentStage == RFAConstants.RFA_STATUS_ReturnToRequester
                    	//RFAGlobalConstants.RETURN_TO_SENDER
                    ||
                    currentStage == RFAConstants.RFA_STATUS_DRAFT
                    	//RFAGlobalConstants.RFA_STAGE_DRAFT
                    )
                    &&
                    selectedlevel == RFAConstants.RFA_STATUS_CLOSED
                    	//RFAGlobalConstants.RFA_STAGE_CLOSED
                )
                {                 
                    system.debug('------- closeReason: ' + closeReason);
                    if(
                    	RFAConstants.isBlank(closeReason)
                    	//closeReason == null || closeReason == ' ' || closeReason.length() == 0
                    	) {
                    	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                    		Label.RFA_Msg_CloseReason
                    		//'クローズ理由を入力してください! / Please input Close Reason!'
                    	));
                    	hasError = true;
                    } else {                 
                    	rfaObj.Stage__c = RFAConstants.RFA_STATUS_CLOSED; //'Closed';   	
                    	rfaObj.Close_Reason__c = closeReason;  
                    	update rfaObj;
                    	//hasError = false;
                    	//return new PageReference('javascript:window.close()'); 
                    	new PageReference('/'+rfaObj.Id);
                    }                     
                } 
               
            return null;
    }

}