MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Entertainment</description>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_RFA_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA 1</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Related RFA</relationshipLabel>
        <relationshipName>Related_RFA_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_RFA_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA 2</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Related RFA 2</relationshipLabel>
        <relationshipName>Related_RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_RFA_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA 3</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Related RFA 3</relationshipLabel>
        <relationshipName>Related_RFA_3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>This field is used to sequence the order of approvals during circulation.  Notifications will be sent to approvers in order from the lowest to highest number.  Approvers with the same order number will receive notifications at the same time.</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>COA_Acronym__c</fullName>
        <formula>UserName__r.COA_Acronym__c</formula>
        <label>COA Acronym</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COA_Group__c</fullName>
        <formula>Text(UserName__r.COA_Group__c)</formula>
        <label>COA Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <formula>UserName__r.CompanyName</formula>
        <label>Company Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <formula>UserName__r.Department</formula>
        <label>Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2_Function__c</fullName>
        <formula>UserName__r.L2_Function_E__c</formula>
        <label>L2 Function</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>UserName__r.Title</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>COA_Acronym__c</fullName>
        <label>COA Acronym</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COA_Group__c</fullName>
        <label>COA Group</label>
        <picklist>
            <picklistValues>
                <fullName>Gr.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gr.6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

MilestoneRFA_CM01/src/classes/CM_RFA_RelatedListController.cls
public with sharing class CM_RFA_RelatedListController {
    
public RFA__c RFA    {get;set;}
//public List<RFA__c> RFAList1    {get;set;}
//public List<RFA__c> RFAList2    {get;set;}
//public List<RFA__c> RFAList3    {get;set;}
public List<RFAUserRole__c> RFAUserRoleList    {get;set;}

    public CM_RFA_RelatedListController(ApexPages.StandardController sc)
    {
        RFA = new RFA__c();
        RFA = (RFA__c) sc.getrecord();
//      RFAList1 = new List<RFA__c>();
//      RFAList2 = new List<RFA__c>();
//      RFAList3 = new List<RFA__c>();
        RFAUserRoleList = new List<RFAUserRole__c>();
/*      
        if(RFA.Related_RFA_1__c != null){
        
            RFAList1 = [SELECT Name,RecordType.Name,RequestTitle__c,
                    RequestAmountFunctionalCurrency__c,Stage__c,
                    CreatedBy.Name,CreatedDate,LastModifiedBy.Name,
                    LastModifiedDate 
                    FROM RFA__c 
                    WHERE ID=:RFA.Related_RFA_1__c
                    Order By Name];
            
        }

        if(RFA.Related_RFA_2__c != null){
            RFAList2 = [SELECT Name,RecordType.Name,RequestTitle__c,
                        RequestAmountFunctionalCurrency__c,Stage__c,
                        CreatedBy.Name,CreatedDate,LastModifiedBy.Name,
                        LastModifiedDate 
                        FROM RFA__c 
                        WHERE ID=:RFA.Related_RFA_2__c
                        Order By Name]; 
        }

        if(RFA.Related_RFA_3__c != null){
            RFAList3 = [SELECT Name,RecordType.Name,RequestTitle__c,
                        RequestAmountFunctionalCurrency__c,Stage__c,
                        CreatedBy.Name,CreatedDate,LastModifiedBy.Name,
                        LastModifiedDate 
                        FROM RFA__c 
                        WHERE ID=:RFA.Related_RFA_3__c
                        Order By Name]; 
        }
*/
        RFAUserRoleList = [SELECT RecordTypeId,ApprovalOrder__c,UserName__r.Name,
                            L2_Function__c,Department__c,Company_Name__c,COA_Group__c,
                            COA_Acronym__c,ApprovalRecommendation__c , Title__c
                            FROM RFAUserRole__c 
                            WHERE RFA__c=:RFA.ID
                            Order By RecordTypeId,ApprovalOrder__c];
    }
}