MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM01_04/src/objects/RM_Milestone_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Related_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>Milestone-History-{0000000000}</displayFormat>
        <label>Milestone History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CocacolaProjectBackUp07/src/classes/RFA_VFC04_ApprovalProcessController_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
//@isTest(SeeAllData=true)
@isTest(SeeAllData=false) 
private class RFA_VFC04_ApprovalProcessController_Test
{
    static testmethod void RFA_VFC04_ApprovalProcess_Test1()
    {
    	RFATestData testData = new RFATestData();
    	/*
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt 
    		= RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	RFA__c testRFA;	
    	User approverUser;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    		
    	}
    	*/
    	/*
    	RFA__c testRFA = RFATestData.buildRFACapital();
    	
    	//System.runAs(RFATestData.levelLCUserMap.get(testRFA.Level__c))
    	//{
    		User approverUser = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app1', 'app1');
    		RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser
    			//, testRFA.level__c
    			);
    		//insert approver;
    		ApprovalProcess__c testProcess = new ApprovalProcess__c();
    		Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    		if(upsertResult.isSuccess())
    		{
    			approver.ApprovalProcess__c = upsertResult.getId();
    			approver.ApprovalOrder__c = 1;
    			approver.ApprovalRecommendation__c = 'Awaiting Approval';
    			update approver;	
    		}
    		RFA__c rfaVsal = [Select Id, 
    			//Level__c, 
    			Stage__c FROM RFA__c where Id =: testRFA.Id];
    		//System.assertEquals('CCEJ', rfaVsal.Level__c);
    		//System.assertEquals('Circulation', rfaVsal.Stage__c);
    	//} 
    	//Test.startTest();
    	ApexPages.Standardcontroller stdController;
    	RFA_VFC04_ApprovalProcessController controller;
    	System.runAs(approverUser)
    	{
    		Map<String, String> urlParams = new Map<String, String>{
    			'Id' => testRFA.Id
    		};
    		Test.setCurrentPage(getPageReference('RFA_VFP02_Override', urlParams));
    		
    		stdController = new ApexPages.Standardcontroller(testRFA);
    		controller = new RFA_VFC04_ApprovalProcessController(stdController);
    		controller.prepareWorkItem();
    		List<SelectOption> recomOptions = controller.recommendationOptions;
    		controller.selectedRecommendation = 'Unconditionally Approved';
    		controller.selectedWorkItem = controller.workItemOptions[0].getValue();
    		
    		
    	}
    	controller.submitRecommendation();
    	ApprovalProcess__c processVal = [
    		Select 
    		//ApprovalProcessLevel__c, 
    		//RFA__r.Level__c, 
    		RFA__r.Stage__c, Status__c FROM ApprovalProcess__c WHERE RFA__c =: testRFA.Id];
    	//System.assertEquals('Completed', processVal.Status__c);
    	//System.assertEquals('CCEJ', processVal.RFA__r.Level__c);
    	//System.assertEquals('Post-Circulation', processVal.RFA__r.Stage__c);  	 
    	//Test.StopTest();
    	
    	*/
    }
    
    /*
    static testmethod void RFA_VFC04_ApprovalProcess_Test2()
    {
    	RFATestData testData = new RFATestData();

    	RFA__c testRFA = RFATestData.buildRFACapital();
    	
    	//System.runAs(RFATestData.levelLCUserMap.get(testRFA.Level__c))
    	//{
    		User approverUser = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app1', 'app1');
    		RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser
    			//, testRFA.level__c
    			);
    		//insert approver;
    		ApprovalProcess__c testProcess = new ApprovalProcess__c();
    		Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    		if(upsertResult.isSuccess())
    		{
    			approver.ApprovalProcess__c = upsertResult.getId();
    			approver.ApprovalOrder__c = 1;
    			approver.ApprovalRecommendation__c = 'Awaiting Approval';
    			update approver;	
    		}
    		RFA__c rfaVsal = [Select Id, 
    			//Level__c, 
    			Stage__c FROM RFA__c where Id =: testRFA.Id];
    		//System.assertEquals('CCEJ', rfaVsal.Level__c); //1. Key Operations
    		//System.assertEquals('Circulation', rfaVsal.Stage__c);
    	//} 
    	//Test.startTest();
    	ApexPages.Standardcontroller stdController;
    	RFA_VFC04_ApprovalProcessController controller;
    	System.runAs(approverUser)
    	{
    		Map<String, String> urlParams = new Map<String, String>{
    			'Id' => testRFA.Id
    		};
    		Test.setCurrentPage(getPageReference('RFA_VFP02_Override', urlParams));
    		
    		stdController = new ApexPages.Standardcontroller(testRFA);
    		controller = new RFA_VFC04_ApprovalProcessController(stdController);
    		controller.prepareWorkItem();
    		List<SelectOption> recomOptions = controller.recommendationOptions;
    		controller.selectedRecommendation = 'Unconditionally Approved';
    		//controller.selectedWorkItem = controller.workItemOptions[0].getValue();
    		
    		
    	}
    	controller.submitRecommendation();
    	ApprovalProcess__c processVal = [
    		Select 
    		//ApprovalProcessLevel__c, 
    		//RFA__r.Level__c, 
    		RFA__r.Stage__c, Status__c FROM ApprovalProcess__c WHERE RFA__c =: testRFA.Id];
    	
    	//Test.StopTest();
    }*/
    
    static PageReference getPageReference(String page, Map<String, String> params) {
        String url = '/apex/'+page+'?';
        for (String param : params.keySet()) {
            url += param + '=' + params.get(param) + '&';
        }
        PageReference p = new PageReference(url);
        return p;
    }

}