MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CM02/src/classes/RFA_AP14_DraftRFAReminderSchedulable.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_AP14_DraftRFAReminderSchedulable
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 07/11/2012
 *  Assumptions      : N/A
 *  Description      : This class implements the schedulable interface and schedules Draft RFA batchable class to run quarterly.
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
 

global class RFA_AP14_DraftRFAReminderSchedulable implements Schedulable{
    
    global static String CRON_EXP = '0 0 0 3 9 ? 2022';
    
    global string baseQuery = 'Select Name, ProfitCenterNumber__c, Id, CreatedById, Stage__c, RequestTitle__c FROM RFA__c WHERE';
     
    global RFA_AP14_DraftRFAReminderSchedulable()
    {
        
        //this.baseQuery = baseQuery + ' ' + 'createdDate > LAST_QUARTER';
        //this.baseQuery = baseQuery + ' ' + 'createdDate < NEXT_N_DAYS:1';
        this.baseQuery = baseQuery + ' ' + 'Stage__c =' + '\'' 
        	//+ RFAConstants.RFA_STATUS_DRAFT
        	+ RFAConstants.RFA_STATUS_ReturnToRequester
        	//RFAGlobalConstants.RFA_STAGE_DRAFT 
        	+ '\' And LastModifiedDate < LAST_N_DAYS:5 ';    
        this.baseQuery = baseQuery + ' ' + ' ' + ' ORDER BY CreatedById';    
                
    }
    
      /**
     *  execute Method
     *  @param SchedulableContext sc
     */
    global void execute(SchedulableContext sc)
    {
        System.debug('\n ------ Query prepared : ' + baseQuery); 
        // create a new instance of RFA_AP10_BatchReminder
        RFA_AP15_RFADraftReminderBatchable draftBatchReminder 
        	= new RFA_AP15_RFADraftReminderBatchable(baseQuery);
        //execute batch
        database.executebatch(draftBatchReminder);       
    }

}