MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CocaColaProjectJar_New/src/classes/RFA_VFC13_New_Approver_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
@isTest(SeeAllData=false) 
private class RFA_VFC13_New_Approver_Test {

    static testMethod void myUnitTest() {
    	/*
        // TO DO: implement unit test
        RFA__c testRFA = new RFA__c();
        testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
        RFATestData rtTest = new RFATestData();
         rtTest.buildProfitCenter();
        
        testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
        testRFA.Stage__c = 'Draft';
        insert testRFA;
        
        
        string profile = RFAConstants.getRFAStandardUserProfileId();
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;
        
        //testRFARole.Level__c = 'CCEJ'; //1. Key Operations
        insert testRFARole;
        */
        
        //RFA__c testRFA = RFATestData.buildRFACapital();
        RFA__c testRFA = RFATestData.buildRFAGeneral();
        RFAUserRole__c testRFARole = [Select Id, UserName__c, RFA__c 
        	from RFAUserRole__c where RFA__c =: testRFA.ID limit 1];

        PageReference pageRef = Page.RFA_VFP13_New_Approver;
        Test.setCurrentPage(pageRef); 
        System.currentPageReference().getParameters().put('id', testRFARole.id); 
        ApexPages.Standardcontroller stdController1 = new ApexPages.Standardcontroller(testRFARole);
        RFA_VFC13_New_Approver controller1 = new RFA_VFC13_New_Approver(stdController1); 
            
           //controller1.rfaUserObj.UserName__c = grUser2.Id;
           controller1.doSaveAndNew();
       
        PageReference pageRef1 = Page.RFA_VFP13_New_Approver;
        Test.setCurrentPage(pageRef1);     
        ApexPages.Standardcontroller stdController2 = new ApexPages.Standardcontroller(testRFARole);
        RFA_VFC13_New_Approver controller2 = new RFA_VFC13_New_Approver(stdController2); 

    }
    
    /*
     static testMethod void myUnitTest2() {
        // TO DO: implement unit test
 
        RFA__c testRFA = new RFA__c();
        testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
        RFATestData rtTest = new RFATestData();
         rtTest.buildProfitCenter();
        
        testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
        testRFA.Stage__c = 'Draft';
        insert testRFA;
        
        
        string profile = RFAConstants.getRFAStandardUserProfileId();
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;
        
        //testRFARole.Level__c = 'CCEJ'; //1. Key Operations
        insert testRFARole;

       

        PageReference pageRef = Page.RFA_VFP13_New_Approver;
        Test.setCurrentPage(pageRef); 
        System.currentPageReference().getParameters().put('id', testRFARole.id); 
        ApexPages.Standardcontroller stdController1 = new ApexPages.Standardcontroller(testRFARole);
        RFA_VFC13_New_Approver controller1 = new RFA_VFC13_New_Approver(stdController1); 
            
           controller1.rfaUserObj.UserName__c = grUser2.Id;
           controller1.doSave();
           
        PageReference pageRef1 = Page.RFA_VFP13_New_Approver;
        Test.setCurrentPage(pageRef1);     
        ApexPages.Standardcontroller stdController2 = new ApexPages.Standardcontroller(testRFARole);
        RFA_VFC13_New_Approver controller2 = new RFA_VFC13_New_Approver(stdController2); 

    }
    */
}