MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>BudgetType__c</fullName>
        <inlineHelpText>&quot;Initial&quot; is used for projects that are still in the preliminary stages of planning and evaluation when details are not complete,&quot;Formal&quot; is used for projects for which implementation plans and cost assumptions are final or nearly final.</inlineHelpText>
        <label>Budget Type</label>
        <picklist>
            <picklistValues>
                <fullName>Formal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataClassification__c</fullName>
        <inlineHelpText>Select the appropriate Data Classification for this request. Note: Highly Restricted information cannot be entered into the sytem. If your request is Highly Restricted  or contains Highly Restricted information please contact your Location Coordinator.</inlineHelpText>
        <label>Data Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InitialBudgetYear__c</fullName>
        <inlineHelpText>The year the capital / small project is expected to begin spending.</inlineHelpText>
        <label>Initial Budget Year</label>
        <picklist>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsthisanAnnualCapitalPlanrequest__c</fullName>
        <inlineHelpText>Used to flag annual capital plan requests for reporting purposes.</inlineHelpText>
        <label>Is this an Annual Capital Plan request?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An organization unit designated as a separate entity for revenue generation and cost collection. Select the PC primarily responsible for the transaction.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnReason__c</fullName>
        <description>Comments to be entered by a Location Coordinator or Capital Management team member when an RFA is placed into Return to Sender Stage.</description>
        <label>Return Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM01_04/src/objects/RM_Milestone_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Related_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>Milestone-History-{0000000000}</displayFormat>
        <label>Milestone History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CocacolaProjectJar/src/classes/RFA_VFC01_ActionButtons_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
//@isTest(SeeAllData=true)
@isTest(SeeAllData=false) 
private class RFA_VFC01_ActionButtons_Test {

    static testMethod void testActionButtonAsRequester() {
        RFATestData testData = new RFATestData();
        //testData.buildProfitCenter();
        //testData.createRequester();
        //String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        
        //RFA__c testRFA;
        
        //System.runAs(RFATestData.requester)
        //{
        	/*
            testRFA = new RFA__c();
            testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA.RecordTypeId =  rt;
            testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
            //testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA.Stage__c = 'Draft';
            testRFA.RequestAmountFunctionalCurrency__c = 1200;      
            //testRFA.Functional_Currency__c = RFATestData.testARE.Id;
            //testRFA.Stage__c = 'Pre-Circulation';
            testRFA.Level__c = 'Draft';
            testRFA.DataClassification__c = 'Internal Use';
            //testRFA.AREMonth__c = 'February';
            testRFA.InitialBudgetYear__c = '2013';
            testRFA.BudgetType__c = 'Formal';
            testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
            //testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
            //testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA;
            */
            
            RFA__c testRFA = RFATestData.buildRFACapital();
            
            Map<String, String> urlParams = new Map<String, String>{
                'Id'    => testRFA.Id    
            };
            
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);
        //}
    }
    
     static testMethod void testActionButtonAsLocalCoordinator1() {
        RFATestData testData = new RFATestData();
        
        //testData.buildProfitCenter();
        //testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(
        	RFAConstants.RECORDTYPE_SMALL_PROJECT_REQUEST
        	).Id;
        
        RFA__c testRFA;
        
        //System.runAs(RFATestData.requester)
        //{
        	//testRFA = RFATestData.buildRFACapital();
        	testRFA = RFATestData.buildRFAGeneral();
            //testRFA = RFATestData.buildTestRFA(testRFA, rt);
            /*
            Map<String, String> urlParams = new Map<String, String>{
                'Id'    => testRFA.Id    
            };
            
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);*/
        //}
        
        
        RFA__c validateRFA = [Select 
        	//Level__c, 
        	//PreviousLevel__c, 
        	Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        //System.runAs(RFATestData.levelLCUserMap.get(validateRFA.Level__c))
        //{
            Map<String, String> urlParams = new Map<String, String>{
                'Id'    => testRFA.Id    
            };
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);   
        //}
    }
    
    static testMethod void testActionButtonAsLocalCoordinator2() {
    	/*
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(
        	Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        */
        
        RFA__c testRFA;
        
        //System.runAs(RFATestData.requester)
        //{
            //testRFA = RFATestData.buildTestRFA(testRFA, rt);
            testRFA = RFATestData.buildRFACapital();
        //}
        RFA__c validateRFA = [Select 
        	//Level__c, 
        	//PreviousLevel__c, 
        	Stage__c FROM RFA__c WHERE Id = : testRFA.Id];
        //System.runAs(RFATestData.levelLCUserMap.get(validateRFA.Level__c))
        //{
            testRFA.Stage__c = 'Post-Circulation';
            update testRFA;
            
            Map<String, String> urlParams = new Map<String, String>{
                'Id'    => testRFA.Id    
            };
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);   
            
        //}
    }
    
    static testMethod void testActionButtonAsAdmin() {
    	/*
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        */
        RFA__c testRFA;
        
        //System.runAs(RFATestData.requester)
        //{
            //testRFA = RFATestData.buildTestRFA(testRFA, rt);
            //testRFA = RFATestData.buildRFACapital();
            testRFA = RFATestData.buildRFAGeneral();
            /*
            Map<String, String> urlParams = new Map<String, String>{
                'Id'    => testRFA.Id    
            };
            
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);*/
        //}
        /*
        testRFA.Stage__c = RFAConstants.RFA_STATUS_ReturnToRequester; //'Return To Sender';
        testRFA.ReturnReason__c = 'This is for the purpose of testing';
        update testRFA;     
        
        Map<String, String> urlParams = new Map<String, String>{
            'Id'    => testRFA.Id    
        };
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
        ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);
        */
        
        /*
        testRFA.Level__c = 'Capital Management Hold';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController1 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller1  = new RFA_VFC01_ActionButtons(stdController1);
        
        testRFA.Level__c = 'Pending Board Review';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController2 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller2  = new RFA_VFC01_ActionButtons(stdController2);
        
        testRFA.Stage__c = 'Approved';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController3 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller3  = new RFA_VFC01_ActionButtons(stdController3);
        */
        
        //Test.startTest();
        
        /*
        testRFA.Level__c = '2. Business Unit';
        testRFA.Stage__c = 'Pre-Circulation';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController4 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller4  = new RFA_VFC01_ActionButtons(stdController4);
        
        testRFA.Level__c = '3. Group';
        testRFA.Stage__c = 'Pre-Circulation';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController5 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller5  = new RFA_VFC01_ActionButtons(stdController5);
        
        testRFA.Level__c = '4. Corporate';
        testRFA.Stage__c = 'Pre-Circulation';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController6 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller6  = new RFA_VFC01_ActionButtons(stdController6);
        
        testRFA.Level__c = '5. Executive';
        testRFA.Stage__c = 'Pre-Circulation';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController7 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller7  = new RFA_VFC01_ActionButtons(stdController7);
        
        testRFA.Level__c = '6. Senior Executive';
        testRFA.Stage__c = 'Pre-Circulation';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController8 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller8  = new RFA_VFC01_ActionButtons(stdController8);
        */
        //Test.stopTest();
    }
    
    static testMethod void testActionButtonAsAdmin_step2() {
        RFA__c testRFA = RFATestData.buildRFACapital();      
        Map<String, String> urlParams = new Map<String, String>{
            'Id'    => testRFA.Id    
        };
        
        //testRFA.Level__c = 'Capital Management Hold';
        //update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController1 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller1  = new RFA_VFC01_ActionButtons(stdController1);
    }    
    
    static testMethod void testActionButtonAsAdmin_step3() {
        RFA__c testRFA = RFATestData.buildRFACapital();      
        Map<String, String> urlParams = new Map<String, String>{
            'Id'    => testRFA.Id    
        };
        //testRFA.Level__c = 'Pending Board Review';
        //update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController2 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller2  = new RFA_VFC01_ActionButtons(stdController2);
             
    }        
    /*
    static testMethod void testActionButtonAsAdmin_step4() {
        //RFA__c testRFA = RFATestData.buildRFACapital();    
        RFA__c testRFA = RFATestData.buildRFAGeneral();    
        Map<String, String> urlParams = new Map<String, String>{
            'Id'    => testRFA.Id    
        };
        
        testRFA.Stage__c = 'Approved';
        update testRFA;
        Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));  
        ApexPages.Standardcontroller stdController3 = new ApexPages.StandardController(testRFA);
        RFA_VFC01_ActionButtons controller3  = new RFA_VFC01_ActionButtons(stdController3);      
    }     
    */
    
    /*
    static testMethod void testActionButtonAtCirculaitionStage() {
    	
        RFATestData testData = new RFATestData();
        
        //testData.buildProfitCenter();
        //testData.createRequester();
       // String rt = RFAGlobalConstants.RECORDTYPESMAP.get(
       // 	Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        
        
        RFA__c testRFA;
        
        //System.runAs(RFATestData.requester)
        //{
            //testRFA = RFATestData.buildTestRFA(testRFA, rt);
            testRFA = RFATestData.buildRFACapital();
            
           // Map<String, String> urlParams = new Map<String, String>{
           //     'Id'    => testRFA.Id    
          //  };
            
          //  Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
          //  ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
          //  RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);
            
        //}   
        User approver1 = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app1', 'app1');
        
        User approver2 = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app2', 'app2');
        
        RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1
        	//, 'CCEJ'
        	);
        RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2
        	//, 'CCEJ'
        	);
        //insert rfaApprover2;
        //insert rfaApprover1;
        
        //Test.startTest();
        //System.runAs(RFATestData.levelLCUserMap.get('CCEJ'))
        //{
            Map<String, String> urlParams = new Map<String, String>
            {
                'Id' => testRFA.Id
            };
            Test.setCurrentPageReference(getPageReference('RFA_VFP03_ApprovalRouting', urlParams));
            ApexPages.standardController stdController = new ApexPages.Standardcontroller(testRFA);
            RFA_VFC02_ApprovalRoutingController controller = new RFA_VFC02_ApprovalRoutingController(stdController);
  
            controller.sequenceList[0].sequence = 1;
            controller.sequenceList[1].sequence = 1;
            controller.submitForApproval();
        //}
         RFAUserRole__c[] validateUserRole = [
         	Select UserName__c, ApprovalRecommendation__c, 
         	//Level__c, 
         	//RFA__r.Level__c, 
         	RFA__r.Stage__c 
                                              FROM RFAUserRole__c 
                                              WHERE RFA__c =: testRFA.Id 
                                              AND RecordTypeId =: RFAGlobalConstants.RECORDTYPESMAP.get(Schema.sObjectType.RFAUserRole__c.getName()).get(RFAConstants.RTLabel_RFAUserRole_Approver).Id];
         
         //System.assertEquals('CCEJ', validateUserRole[0].RFA__r.Level__c); //1. Key Operations
         System.debug('\n RFA Stage :'+validateUserRole[0].RFA__r.Stage__c);
         //System.assertEquals('Circulation', validateUserRole[0].RFA__r.Stage__c);
                                              
         for(RFAUserRole__c approver : validateUserRole)
         {
            //System.assertEquals('Awaiting Approval', approver.ApprovalRecommendation__c);
         }
         
         //Map<String, String> urlParams = new Map<String, String>{
         urlParams = new Map<String, String>{	
                'Id'    => testRFA.Id    
         };
         
         System.runAs(approver1)
         {
                        
            Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
            //ApexPages.Standardcontroller stdController = new ApexPages.StandardController(testRFA);
            stdController = new ApexPages.StandardController(testRFA);
            //RFA_VFC01_ActionButtons controller  = new RFA_VFC01_ActionButtons(stdController);   
            //controller  = new RFA_VFC01_ActionButtons(stdController);   
         }  
         Test.setCurrentPage(getPageReference('RFA_VFP08_ActionButtonTop', urlParams));
         ApexPages.Standardcontroller stdController1 = new ApexPages.StandardController(testRFA);
         RFA_VFC01_ActionButtons controller2  = new RFA_VFC01_ActionButtons(stdController1);
         //Test.stopTest();
        
    }
    */
    
    static PageReference getPageReference(String page, Map<String, String> params) {
        String url = '/apex/'+page+'?';
        for (String param : params.keySet()) {
            url += param + '=' + params.get(param) + '&';
        }
        PageReference p = new PageReference(url);
        return p;
    }
    
}