MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>ApprovalLetterComments__c</fullName>
        <inlineHelpText>Comments describing conditional approval requirements.</inlineHelpText>
        <label>Follow-up: Approver Comments/Conditions</label>
        <picklist>
            <picklistValues>
                <fullName>The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The requesting party must fully comply with the above approval conditions, although explicit communication or follow up with these approvers is not required.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CommentsConditions__c</fullName>
        <inlineHelpText>Text provided by approvers of approval condition that must be accomplished before transaction initiation.</inlineHelpText>
        <label>Comments/Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theapprovalstatusofyourrequestis__c</fullName>
        <description>Approval Status of the RFA Request</description>
        <inlineHelpText>Displays the approval status of the RFA (unconditionally approved, conditionally approved, etc.)</inlineHelpText>
        <label>This request has been</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed / Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / Not Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thefollowingitem__c</fullName>
        <inlineHelpText>Select level/stage the RFA was approved through according to the DOA/LCOA.</inlineHelpText>
        <label>This request was circulated to</label>
        <picklist>
            <picklistValues>
                <fullName>Approval and / or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Directors for approval as required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

本番20140705/src/classes/RFA_VFC04_CompletionMemoController_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
//@isTest(SeeAllData=true)
@isTest(SeeAllData=false) 
private class RFA_VFC04_CompletionMemoController_Test
{

    static testmethod void RFA_VFC04_Completion_Test()
    {
    	/*
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(
    		Schema.Sobjecttype.RFA__c.getName()).get(
    			RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;    	
    	RFA__c testRFA;
    	    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);    		
    	}
    	*/
    	
    	RFA__c testRFA = RFATestData.buildRFACapital();
    	
    	ApexPages.Standardcontroller stdController1 
    		= new ApexPages.Standardcontroller(testRFA);
    	RFA_VFC04_CompletionMemoController controller1 
    		= new RFA_VFC04_CompletionMemoController(stdController1);
    		
    	List<SelectOption> options = controller1.getSelectableUsers();
    	
    	controller1.selectedRecipients.add(options[0]);
    	controller1.selectedCCusers = 'test@coke.com';
    	controller1.rfaObj.Thefollowingitem__c 
    		= 'Key Operation level for approval and/or for information only as required';
    	controller1.rfaObj.Theapprovalstatusofyourrequestis__c = RFAConstants.ApproverRecommend_UnconditionalApproved; //'Unconditionally Approved';
    	controller1.rfaObj.CommentsConditions__c = 'This is for the purpose of testing';
    	controller1.rfaObj.ApprovalLetterComments__c 
    		= 'The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions. Any failure to fully address these conditions will be subject to Audit review.';
    	controller1.sendEmail();
    
    }

}