MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM02/src/classes/RFA_AP11_BatchReminderSchedulable_Test.cls
/**
	updated by Jia Hu on 2013/11/08
 */
//@isTest(SeeAllData=true)
@isTest(SeeAllData=false) 
private class RFA_AP11_BatchReminderSchedulable_Test {

    static testMethod void testBatchReminder() {
    	// TO DO: implement unit test
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
    	RFATestData testData = new RFATestData();
    	
    	//testData.buildProfitCenter();
    	testData.createRequester();
    	
    	//String rt = RFAGlobalConstants.RECORDTYPESMAP.get(
    	//	Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	//System.runAs(RFATestData.requester)
    	//{
    		//updated by Jia Hu on 2013/11/12
    		//testRFA = RFATestData.buildTestRFA(testRFA, rt);
    		testRFA = RFATestData.buildRFACapital();
    		
    		
    	//}
    	
    	/*
    	User approver1 = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app1', 'app1');
    	
    	User approver2 = testData.createUser(RFAConstants.getRFAStandardUserProfileId(), 'app2', 'app2');
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1
    		//, 'CCEJ'
    		);//CCEJ
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2
    		//, 'CCEJ'
    		); //1. Key Operations
    	*/	
    	
    	//removed by Jia Hu on 2013/11/12	
    	//approverLevelMap.put('CCEJ', new List<RFAUserRole__c>{rfaApprover1, rfaApprover2}); //1. Key Operations
    	//insert approverlevelMap.get('CCEJ'); //1. Key Operations
    	
    	/*
    	System.runAs(RFATestData.levelLCUserMap.get('CCEJ')) //1. Key Operations
    	{
    		Map<String, String> urlParams = new Map<String, String>
    		{
    			'Id' => testRFA.Id
    		};
    		Test.setCurrentPageReference(getPageReference('RFA_VFP03_ApprovalRouting', urlParams));
    		ApexPages.standardController stdController = new ApexPages.Standardcontroller(testRFA);
    		RFA_VFC02_ApprovalRoutingController controller = new RFA_VFC02_ApprovalRoutingController(stdController);
  
    		controller.sequenceList[0].sequence = 1;
    		controller.sequenceList[1].sequence = 1;
    		controller.submitForApproval();
    	}
    	*/
    	
    	//Test.StartTest();
    	
    	RFA_BatchReminder__c reminder = new RFA_BatchReminder__c();
    	reminder.Name = 'Approval Reminder';
    	reminder.ReminderThreshold__c = '3';
    	insert reminder;
    	
    	String jobId = System.schedule('testBatchReminderApex',
        	RFA_AP11_BatchReminderSchedulable.CRON_EXP, 
        	new RFA_AP11_BatchReminderSchedulable());
        
        
    	String queryString = 'Select Agent1__c, Agent2__c, Agent3__c, UserName__c, RFA__c, ApprovalProcess__c FROM RFAUserRole__c WHERE' + ' ';
    	queryString = queryString + 'RecordType.Name=' +'\'' + RFAConstants.RTLabel_RFAUserRole_Approver + '\'';
    	queryString = queryString + ' ' + 'AND ApprovalRecommendation__c=' + '\'' 
    		+ RFAConstants.ApproverRecommend_AwaitingApproval
    		//RFAGlobalConstants.PROCESS_PENDING_RECOMMENDATION 
    		+ '\'';
    	queryString = queryString + ' ' + 'ORDER BY UserName__c LIMIT 20';	
    	
    	RFA_AP10_BatchReminder batchReminder = new RFA_AP10_BatchReminder(queryString);
    	database.executebatch(batchReminder);              
    	
    	//Test.stopTest();
    }
    
    static PageReference getPageReference(String page, Map<String, String> params) {
        String url = '/apex/'+page+'?';
        for (String param : params.keySet()) {
            url += param + '=' + params.get(param) + '&';
        }
        PageReference p = new PageReference(url);
        return p;
    }
}