MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>Request Amount is based on COA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amount, etc.</inlineHelpText>
        <label>Request Amount (JPY)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnReason__c</fullName>
        <description>Comments to be entered by a Location Coordinator or Capital Management team member when an RFA is placed into Return to Sender Stage.</description>
        <label>Return Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <description>IF($RecordType.Name == &apos;Info Copy Only&apos;, &quot;Info Copy Only&quot;, &quot;&quot;)</description>
        <inlineHelpText>Add comment in both Japanese and English, if any non-Japanese recipient is involved in the approval process (either approver or info copy).</inlineHelpText>
        <label>Condition / Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CocaColaProjectBIDev/src/classes/RFATestData_Capital.cls
@isTest(SeeAllData=true) 
public with sharing class RFATestData_Capital {
	
	//static testmethod void RFA_Test_Capital_1(){
	//	RFATestData.buildRFACapital();
	//}
	
	public static RFA__c getDraftRFAwithApprover() {
		RFA__c rfawithApp;
		
		Id generalRFAId = RFAConstants.getRecordType('General Request', 'RFA__c');
		Id approverRTId = RFAConstants.getRecordType('Approver', 'RFAUserRole__c');
		

		for(RFA__c rfa : [Select Id, Stage__c, RequestTitle__c, 
			ReturnReason__c, RequestAmountFunctionalCurrency__c,
			(Select Id from RFA_User_Roles__r where RecordTypeId =: approverRTId) 
			from RFA__c 
			where Stage__c =: RFAConstants.RFA_STATUS_DRAFT //AND RequestTitle__c = 'test_class_data'
			AND RecordTypeId =: generalRFAId
			order by CreatedDate Desc
			limit 1
			]
		) {
			
			List<RFAUserRole__c> approverList = rfa.RFA_User_Roles__r;
			if(approverList != null && approverList.size() > 0) {
				return rfa;
			}				
		}
			
		return rfawithApp;	
		
	}
	
	static testmethod void RFA_Test_General_1(){
		
		/*
		RFA__c rfa = [Select Id, Stage__c, RequestTitle__c, 
			ReturnReason__c, RequestAmountFunctionalCurrency__c 
			from RFA__c 
			where Stage__c =: RFAConstants.RFA_STATUS_DRAFT //AND RequestTitle__c = 'test_class_data'
			order by CreatedDate Desc
			limit 1
			];*/
		
		RFA__c rfa = getDraftRFAwithApprover();
		
		if(rfa != null) {
		rfa.Stage__c = RFAConstants.RFA_STATUS_CIRCULATION;
		update rfa;
		
		rfa.Stage__c = RFAConstants.RFA_STATUS_ReturnToRequester;
		rfa.ReturnReason__c = 'Return Reason';
		update rfa;
		
		rfa.Stage__c = RFAConstants.RFA_STATUS_CIRCULATION;
		update rfa;
		}
	
	}	
	
	static testmethod void RFA_Test_General_2(){
		
		RFA__c rfa = getDraftRFAwithApprover();
		
		if(rfa != null) {
		rfa.Stage__c = RFAConstants.RFA_STATUS_CIRCULATION;
		update rfa;
		
		List<RFAUserRole__c> approvers = [
			Select Id, ApprovalComments__c, ApprovalRecommendation__c from RFAUserRole__c 
			where RFA__c =: rfa.Id And ApprovalRecommendation__c = : RFAConstants.ApproverRecommend_AwaitingApproval
		];
		
		for(RFAUserRole__c approver : approvers) {
			approver.ApprovalComments__c = 'Conditional Approved';
			approver.ApprovalRecommendation__c = RFAConstants.ApproverRecommend_ConditionalApproved;
			
		}		
		
		if(approvers != null && approvers.size() > 0) {
			update approvers;
		}
			
		}
	}		
	
	static testmethod void RFA_Test_General_3(){
		
		RFA__c rfa = getDraftRFAwithApprover();
		
		if(rfa != null) {
		rfa.Stage__c = RFAConstants.RFA_STATUS_CIRCULATION;
		update rfa;
		
		List<RFAUserRole__c> approvers = [
			Select Id, ApprovalComments__c, ApprovalRecommendation__c from RFAUserRole__c 
			where RFA__c =: rfa.Id And ApprovalRecommendation__c = : RFAConstants.ApproverRecommend_AwaitingApproval
		];
		
		if(approvers != null && approvers.size() > 0) {
			approvers[0].ApprovalComments__c  = 'ReturnToRequester';
			approvers[0].ApprovalRecommendation__c = RFAConstants.ApproverRecommend_ReturnToRequester;
			update approvers[0];
		}
		
		}
		
	}		
	
	static testmethod void RFA_Test_General_4(){
		
		RFA__c rfa = getDraftRFAwithApprover();
		
		if(rfa != null) {
		rfa.Stage__c = RFAConstants.RFA_STATUS_CIRCULATION;
		update rfa;
		
		List<RFAUserRole__c> approvers = [
			Select Id, ApprovalComments__c, ApprovalRecommendation__c from RFAUserRole__c 
			where RFA__c =: rfa.Id And ApprovalRecommendation__c = : RFAConstants.ApproverRecommend_AwaitingApproval
		];
		
		if(approvers != null && approvers.size() > 0) {
			approvers[0].ApprovalComments__c  = ';';
			approvers[0].ApprovalRecommendation__c = RFAConstants.ApproverRecommend_Rejected;
			update approvers[0];
		}
		
		}
		
	}		
	
	
	static testmethod void RFA_Test_Temp(){
		RFATestDataTemp.Method1();
		RFATestDataTemp.Method2();
		RFATestDataTemp.Method3();
		RFATestDataTemp.Method4();
		RFATestDataTemp.Method5();
		RFATestDataTemp.Method6();
		RFATestDataTemp.Method7();
		RFATestDataTemp.Method8();
		RFATestDataTemp.Method9();
		RFATestDataTemp.Method10();
		RFATestDataTemp.Method11();
	}
	static testmethod void RFA_Test_Temp2(){
		RFATestDataTemp.Method12();
		RFATestDataTemp.Method13();
		RFATestDataTemp.Method14();
	}	
	
	static testmethod void RFA_Test_Temp3(){
		RFATestDataTemp.Method21();
		RFATestDataTemp.Method22();
		RFATestDataTemp.Method23();
		RFATestDataTemp.Method24();
		RFATestDataTemp.Method25();
		RFATestDataTemp.Method26();
		RFATestDataTemp.Method27();
		RFATestDataTemp.Method28();
		RFATestDataTemp.Method29();
		RFATestDataTemp.Method30();
		RFATestDataTemp.Method31();
	}	
	
	static testmethod void RFA_Test_Temp4(){
		RFATestDataTemp.Method32();
		RFATestDataTemp.Method33();
		RFATestDataTemp.Method34();
	}			

}