MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <description>IF($RecordType.Name == &apos;Info Copy Only&apos;, &quot;Info Copy Only&quot;, &quot;&quot;)</description>
        <inlineHelpText>Add comment in both Japanese and English, if any non-Japanese recipient is involved in the approval process (either approver or info copy).</inlineHelpText>
        <label>Condition / Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved / 承認（条件なし）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved / 承認（条件付き）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / 否認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval / 承認待ち</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester / 差し戻し</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DoNotSendEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Send E-mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NotifyUsers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NotifyUsers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notifyuserfirsttime__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notifyuserfirsttime</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFA_Agent_1__c</fullName>
        <label>RFA Agent 1</label>
        <relationshipName>RFA_Agent_1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>RFA_Agent_2__c</fullName>
        <label>RFA Agent 2</label>
        <relationshipName>RFA_Agent_2</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>RFA_Agent_3__c</fullName>
        <label>RFA Agent 3</label>
        <relationshipName>RFA_Agent_3</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

CocaColaProjectJar_New/src/classes/RFA_VFC13_New_Approver.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_VFC13_New_Approver
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 28/5/2013 
 *  Assumptions      : N/A
 *  Description      : Class to implement the logic on the New Approver Page. 
 *
 *  updated by Jia Hu on 2013/11/06
 *  called from VF page: RFA_VFP13_New_Approver
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
public with sharing class  RFA_VFC13_New_Approver {
    
    public RFAUserRole__c rfaUserObj { get; set; }
    private String oldUsername;
    
    // instantiate new rfa_AP02_ShareUtil
    private RFA_AP02_Shareutil shareUtil=new RFA_AP02_Shareutil();
    
    // Get RecordTypes associated to RFAUser Role
    public static Map<String, RecordType> approverRecordTypeMap = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.sObjectType.RFAUserRole__c.getName());
    
    
    public RFA_VFC13_New_Approver(ApexPages.StandardController controller) {

          //Query the record values in case Edit page is opened

          ID  id = ApexPages.currentPage().getParameters().get('id');
          if(ID<>NULL)
              rfaUserObj = [Select UserName__c,RecordTypeId,
              	//Level__c,
              	RFA__c, DoNotSendEmail__c, Notifyuserfirsttime__c, NotifyUsers__c, 
              	ApprovalRecommendation__c, ApprovalComments__c, Agent1__c, Agent2__c, Agent3__c, 
              	Name, ApprovalOrder__c 
              	from RFAUserRole__c where Id =:id] ;
          
          else
              rfaUserObj = (RFAUserRole__c)controller.getRecord();
          
          oldUsername = rfaUserObj.Username__c;
          
          /* GA 5/20/13 : 2013 Q1 Enhancement FR 1.22
           * The following is logic to handle changing RFA Approver/User object record type but this is now commented out.
           * The reason this code is commented out is because Record Type updating should not be supported per object validation rule RUR_VR09_Lock_RecordType.
           
          String pageRecordTypeId = ApexPages.currentPage().getParameters().get('RecordType');
          String rfaUserRecordTypeId = rfaUserObj.RecordTypeId;
          
          if (!rfaUserRecordTypeId.contains(pageRecordTypeId))
          {
                system.debug('enter update record type');
                rfaUserObj.RecordTypeId = (Id)pageRecordTypeId;
          }
           
          system.debug('Page Record Type Id: ' + pageRecordTypeId);
          system.debug('rfaUserRecordTypeId:' + rfaUserRecordTypeId);
          
          */
          
          system.debug('constructor: ' + rfaUserObj);
    }
    
    public PageReference dosave()
    {    
        try
        {
            // to handle if the return (Enter) key is pressed or save is clicked before queryAction can be invoked
            if (oldUsername != rfaUserObj.Username__c)
            {
                queryAgents();
            }
        
            upsert rfaUserObj ;
        }
        catch(exception e)
        {
           ApexPages.addMessages(e);
           return null;
        }  

        return new Pagereference('/' + rfaUserObj.get('Id'));
    }
    
    public PageReference doSaveAndNew()
    {
        try
        {
            if (oldUsername != rfaUserObj.Username__c)
            {
                queryAgents();
            }
            
            upsert rfaUserObj;
        }
        catch(exception e)
        {
           ApexPages.addMessages(e);
           return null;
        }  

        // string s = '/' + ('' + rfaUserObj.get('Id')).subString(0, 3) + '/e';
        string s = '/setup/ui/recordtypeselect.jsp?ent='+System.Label.RFA_CL145+'&retURL=%2F'+rfaUserObj.id+'&save_new_url=%2Fa0E%2Fe%3FCF'+System.Label.RFA_CL144+'%3DRFA%2523-0007566%26CF'+System.Label.RFA_CL144+'_lkid%3D'+rfaUserObj.rfa__c+'%26scontrolCaching%3D1%26retURL%3D%252F'+rfaUserObj.rfa__c;
        return new Pagereference(s);
    }
    
    public PageReference queryAgents()
    {
        try
        {
            oldUsername = rfaUserObj.Username__c;
            system.debug('QueryAgent() rfaUserObj.Username__c: ' + rfaUserObj.Username__c);
            User usr = [Select RFA_Agent_1__r.Name, RFA_Agent_2__r.Name , RFA_Agent_3__r.Name From User where Id = :rfaUserObj.Username__c];
            rfaUserObj.Agent1__c = usr.RFA_Agent_1__c;
            rfaUserObj.Agent2__c = usr.RFA_Agent_2__c;
            rfaUserObj.Agent3__c = usr.RFA_Agent_3__c;
            system.debug('User Agents 1  ' +usr.RFA_Agent_1__c);
            system.debug('User Agents 2  ' +usr.RFA_Agent_2__c);
            system.debug('User Agents 3  ' +usr.RFA_Agent_3__c);
        }
        catch(exception e)
        {
           ApexPages.addMessages(e);
        }  

        return null;
    }
    
 
    
}