MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>RM_Function_L2__c</fullName>
        <label>Function (L2)</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ST - CokeOne+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Investment_Amounts__c</fullName>
        <label>Investment Amounts(Per \1,000 JPY)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Objectives__c</fullName>
        <label>Objectives</label>
        <picklist>
            <picklistValues>
                <fullName>法律/法的規制対応 </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>更新投資(老朽に伴う入替) </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>品質基準対応（環境負荷軽減・労働安全衛生含む） </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>効率性/生産性向上 </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>顧客ニーズへの対応 </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>販売機材戦略 </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>売上成長/営業力強化 </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>その他の戦略的対応</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Project_Classification_Capital__c</fullName>
        <inlineHelpText>Describe the category name that you want to manage with each Function Example: Project-CokeOne , Project-SWAN, etc.</inlineHelpText>
        <label>Project Classification</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>RFA承認申請</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RM_Request_Record_Type__c</fullName>
        <label>Request Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase (e.g., Write-off 5 non-working vending machines in Tokai Division).</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/RM_Milestone_Synergy_Management_History__c.object
<CustomObject>
    <fields>
        <fullName>RM_Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>1.Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Category_Detail__c</fullName>
        <label>Asset Category Detail</label>
        <picklist>
            <controllingField>RM_Asset_Category__c</controllingField>
            <picklistValues>
                <fullName>01.Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings - Plant/Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings - Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Water Supply/Electrical Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Air Conditioning Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.B&amp;A - Partition/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures - Drain Ditch/Concrete Pavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures - Signboard/Asphalt Pavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery - Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery - Beverage Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.Sales Equipment - Can/Cup VM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07.Sales Equipment - Coolers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.Sales Equipment - Dispensers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09.Sales Equipment - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.IT Hardware - Server/PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Desk/Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Locker/Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Refrigerator/Air Conditioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture - Coin Counting Machine/Inspection Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.Fleet - Automobiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.Fleet - Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.Fleet - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.IT Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.Other (Not Fixed Assets)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Category__c</fullName>
        <label>Asset Category</label>
        <picklist>
            <picklistValues>
                <fullName>01.Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03.Buildings &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.Structures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05.Machinery &amp; Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.Sales Equipment - Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07.Sales Equipment - Coolers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.Sales Equipment - Dispensers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09.Sales Equipment - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.IT Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.Furniture &amp; Fixtures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.Fleet - Automobiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.Fleet - Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.Fleet - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.IT Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.Other (Not Fixed Assets)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Asset_Name__c</fullName>
        <label>Asset Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_Depreciation_Rule__c</fullName>
        <label>Depreciation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New straight-line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>straight-line(5 years)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_Next_Year__c</fullName>
        <label>Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA No.</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Milestone Synergy Management History</relationshipLabel>
        <relationshipName>Milestone_Synergy_Management_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RM_The_Year_After_Next__c</fullName>
        <label>The Year After Next</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Formula__c</fullName>
        <formula>IF(OR(ISBLANK(RM_This_Year__c),RM_This_Year__c==0,RM_This_Year__c == null),
RM_This_Year_Q1__c +  RM_This_Year_Q2__c +  RM_This_Year_Q3__c +  RM_This_Year_Q4__c,
RM_This_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>This Year(Formula)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q1__c</fullName>
        <label>This Year Q1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q2__c</fullName>
        <label>This Year Q2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q3__c</fullName>
        <label>This Year Q3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year_Q4__c</fullName>
        <label>This Year Q4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_This_Year__c</fullName>
        <label>This Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RM_Useful_Life__c</fullName>
        <label>Useful Life</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Milestone Synergy Management History</label>
    <nameField>
        <displayFormat>Milestone-Synergy-{0000000000}</displayFormat>
        <label>Milestone Synergy Management History No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/classes/RM_VFC_Quantitative_Benefit_Capital_Test.cls
/**

 */
@isTest
private class RM_VFC_Quantitative_Benefit_Capital_Test {

    static testMethod void quantitativeBenefitCapitalTest() {
    	
        //Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        //Id pId = createProject();
        //RFATestData td = new RFATestData();
        //td.buildProfitCenter();
        //td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        //pageRef.getParameters().put('Id', rId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        cls.editCancel();
        cls.changeYear();        
        cls.saveSynergy();
        
        
        Test.stopTest();
        
    }
    /*
    static testMethod void quantitativeBenefitCapitalSaveError01Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList01Error(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        cls.editCancel();
        cls.changeYear();
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
    
    static testMethod void quantitativeBenefitCapitalSaveError02Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList03Error(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
    /*
    static testMethod void quantitativeBenefitCapitalSaveError03Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList04Error(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
    
     static testMethod void quantitativeBenefitCapitalSaveError04Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList05Error(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
    
    static testMethod void quantitativeBenefitCapitalSaveOK01Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList02OK(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
    
    static testMethod void quantitativeBenefitCapitalSaveOK03Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList06OK(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        //cls.quantitativeSynergyHistory
        cls.saveSynergy();
        
        Test.stopTest();
        
    }
*/
    static testMethod void quantitativeBenefitCapitalSaveOK04Test() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList07OK(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.editCancel();
        cls.changeYear();        
        cls.saveSynergy();
        
        Test.stopTest();
        
    }

    /*
    static testMethod void quantitativeBenefitCapitalCancelTest() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        Id pId = createProject();
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        
        cls.editCancel();

        Test.stopTest();
        
    }
    
    static testMethod void quantitativeBenefitCapitalYearSelectTest() {
    	
        Id rId = Utility_Helper_RecordType.getRecordTypeIdByAPIName(RFA_Utility_Constants.sObj_RFA_APIName, RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST);
        RFATestData td = new RFATestData();
        td.buildProfitCenter();
        td.buildTaxRate();
        
        PageReference pageRef = Page.Milestone_RFA_02_Quantitative_Benefit;
        pageRef.getParameters().put('Id', rId);
        
        Id proId = createProject();
        Id rfaId = createRFA(proId);
        createSynergyHistoryList01Error(rfaId);
        
        Test.startTest();
        
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(new RFA__c());
        RM_VFC_Quantitative_Benefit_Capital cls = new RM_VFC_Quantitative_Benefit_Capital(sc);
        cls.editCancel();
        cls.changeYear();
        
        Test.stopTest();
        
    }
    */
    static void createSynergyHistoryList01Error(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh = new RM_Milestone_Synergy_Management_History__c();
    	msmh.RM_Name__c = 'テスト予算';
    	msmh.RM_RFA__c = rfaId;
    	msmh.RM_This_Year_Q1__c = 100;
    	msmh.RM_This_Year_Q2__c = 100;
    	msmh.RM_This_Year_Q3__c = 100;
    	msmh.RM_This_Year_Q4__c = 200;
    	//msmh.RM_This_Year_Formula__c
    	msmh.RM_This_Year__c = 500;
    	msmh.RM_Next_Year__c = 500;
    	msmh.RM_The_Year_After_Next__c = 500;
    		
    	msmhList.add(msmh);
    		
	    RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
	    
	    msmh2.RM_Acquisition_Method__c = '2.リース';
		msmh2.RM_Asset_Category__c = '02.建物';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
	    msmh2.RM_This_Year__c = 30000;
	    msmh2.RM_Next_Year__c = 10000;
	    msmh2.RM_The_Year_After_Next__c = 10000;    	
	    
	    msmhList.add(msmh2);	
    	
    	insert msmhList;
    }
    
    static void createSynergyHistoryList02OK(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh1 = new RM_Milestone_Synergy_Management_History__c();
    	msmh1.RM_Name__c = 'テスト予算';
    	msmh1.RM_RFA__c = rfaId;
    	msmh1.RM_This_Year_Q1__c = 10000;
    	msmh1.RM_This_Year_Q2__c = 10000;
    	msmh1.RM_This_Year_Q3__c = 10000;
    	msmh1.RM_This_Year_Q4__c = 20000;
    	//msmh.RM_This_Year_Formula__c
    	msmh1.RM_This_Year__c = 30000;
    	msmh1.RM_Next_Year__c = 10000;
    	msmh1.RM_The_Year_After_Next__c = 10000;
    		
    	msmhList.add(msmh1);	
    	
    	RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
    	
    	msmh2.RM_Acquisition_Method__c = '2.リース';
		msmh2.RM_Asset_Category__c = '02.建物';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
    	msmh2.RM_This_Year__c = 30000;
    	msmh2.RM_Next_Year__c = 30000;
    	msmh2.RM_The_Year_After_Next__c = 40000;    	
    	
    	msmhList.add(msmh2);	
    	system.debug('●●' + msmhList);
    	insert msmhList;
    }
    
    static void createSynergyHistoryList03Error(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh1 = new RM_Milestone_Synergy_Management_History__c();
    	msmh1.RM_Name__c = 'テスト予算';
    	msmh1.RM_RFA__c = rfaId;
    	msmh1.RM_This_Year_Q1__c = 10000;
    	msmh1.RM_This_Year_Q2__c = 10000;
    	msmh1.RM_This_Year_Q3__c = 10000;
    	msmh1.RM_This_Year_Q4__c = 20000;
    	//msmh.RM_This_Year_Formula__c
    	msmh1.RM_This_Year__c = 30000;
    	msmh1.RM_Next_Year__c = 10000;
    	msmh1.RM_The_Year_After_Next__c = 10000;
    		
    	msmhList.add(msmh1);	
    	
    	RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
    	
    	msmh2.RM_Acquisition_Method__c = '2.リース';
		msmh2.RM_Asset_Category__c = '';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
    	msmh2.RM_This_Year__c = 30000;
    	msmh2.RM_Next_Year__c = 10000;
    	msmh2.RM_The_Year_After_Next__c = 10000;    	
    	
    	msmhList.add(msmh2);	
    	
    	insert msmhList;
    }
    
    static void createSynergyHistoryList04Error(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh1 = new RM_Milestone_Synergy_Management_History__c();
    	msmh1.RM_Name__c = 'テスト予算';
    	msmh1.RM_RFA__c = rfaId;
    	msmh1.RM_This_Year_Q1__c = 10000;
    	msmh1.RM_This_Year_Q2__c = 10000;
    	msmh1.RM_This_Year_Q3__c = 10000;
    	msmh1.RM_This_Year_Q4__c = 20000;
    	//msmh.RM_This_Year_Formula__c
    	msmh1.RM_This_Year__c = 30000;
    	msmh1.RM_Next_Year__c = 10000;
    	msmh1.RM_The_Year_After_Next__c = 10000;
    		
    	msmhList.add(msmh1);	
    	
    	RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
    	
    	msmh2.RM_Acquisition_Method__c = '';
		msmh2.RM_Asset_Category__c = '';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
    	msmh2.RM_This_Year__c = 30000;
    	msmh2.RM_Next_Year__c = 10000;
    	msmh2.RM_The_Year_After_Next__c = 10000;    	
    	
    	msmhList.add(msmh2);	
    	
    	insert msmhList;
    }
    
    static void createSynergyHistoryList05Error(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh1 = new RM_Milestone_Synergy_Management_History__c();
    	msmh1.RM_Name__c = '';
    	msmh1.RM_RFA__c = rfaId;
    	msmh1.RM_This_Year_Q1__c = 10000;
    	msmh1.RM_This_Year_Q2__c = 10000;
    	msmh1.RM_This_Year_Q3__c = 10000;
    	msmh1.RM_This_Year_Q4__c = 20000;
    	//msmh.RM_This_Year_Formula__c
    	msmh1.RM_This_Year__c = 30000;
    	msmh1.RM_Next_Year__c = 10000;
    	msmh1.RM_The_Year_After_Next__c = 10000;
    		
    	msmhList.add(msmh1);	
    	
    	RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
    	
    	msmh2.RM_Acquisition_Method__c = '';
		msmh2.RM_Asset_Category__c = '';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
    	msmh2.RM_This_Year__c = 30000;
    	msmh2.RM_Next_Year__c = 10000;
    	msmh2.RM_The_Year_After_Next__c = 10000;    	
    	
    	msmhList.add(msmh2);	
    	
    	insert msmhList;
    }
    
    static void createSynergyHistoryList06OK(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh1 = new RM_Milestone_Synergy_Management_History__c();
    	msmh1.RM_Name__c = '';
    	msmh1.RM_RFA__c = rfaId;
    	msmh1.RM_This_Year_Q1__c = 10000;
    	msmh1.RM_This_Year_Q2__c = 10000;
    	msmh1.RM_This_Year_Q3__c = 10000;
    	msmh1.RM_This_Year_Q4__c = 20000;
    	//msmh.RM_This_Year_Formula__c
    	msmh1.RM_This_Year__c = 30000;
    	msmh1.RM_Next_Year__c = 10000;
    	msmh1.RM_The_Year_After_Next__c = 10000;
    		
    	msmhList.add(msmh1);	
    	
    	insert msmhList;
    }
    
    static void createSynergyHistoryList07OK(Id rfaId) {
    	List<RM_Milestone_Synergy_Management_History__c> msmhList = new List<RM_Milestone_Synergy_Management_History__c>();
    	
    	RM_Milestone_Synergy_Management_History__c msmh2 = new RM_Milestone_Synergy_Management_History__c();
    	
    	msmh2.RM_Acquisition_Method__c = '';
		msmh2.RM_Asset_Category__c = '';
		msmh2.RM_Asset_Category_Detail__c = '02.建物 - 営業拠点';
		msmh2.RM_Asset_Name__c = 'テストリース';
		msmh2.RM_Useful_Life__c = 31;
		msmh2.RM_Depreciation_Rule__c = '定額法';
    	msmh2.RM_This_Year__c = 30000;
    	msmh2.RM_Next_Year__c = 10000;
    	msmh2.RM_The_Year_After_Next__c = 10000;    	
    	
    	msmhList.add(msmh2);	
    	
    	insert msmhList;
    }

    
    static Id createRFA(Id proId) {
		
		RFA__c rfa = new RFA__c(RM_Related_Project__c = proId,
								RM_Request_Record_Type__c = 'Capital',
								RequestTitle__c = 'テスト案件',
								RM_Project_Classification_Capital__c = 'テストClass',
								RM_Objectives__c = '更新投資(老朽に伴う入替) ',
								RM_Function_L2__c = 'Finance',
								RM_Investment_Amounts__c = 100000,
								RM_Function_L3__c = 'Finance Integration',
								RM_Background_Current_Issue__c = 'テストIssue',
								RM_Project_Objectives__c = 'テストObjectives',
								RM_Estimated_Benefit_Overview__c = 'テストOverView'
								); 
			Database.SaveResult sr = database.insert(rfa,false);
			system.debug('●●' + rfa);
		return sr.getId();
		
    }

    
    static Id createProject() {
    	
    	Milestone1_Project__c p = createProject(false);
    	return p.Id;
    	
    	return null;
    }
    
    static Milestone1_Project__c createProject(boolean exe) {
    	
    	Milestone1_Project__c p = new Milestone1_Project__c();
    	p.Name = 'test Method';
    	if (exe) {
    		insert p;
    	}
    	return p;
    	
    	return null;
    }
}