MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>Seal_Name_CCEJ_Company_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Seal_Name_CCEJ_Company_Check</description>
        <label>CCEJ Company Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seal_Name_CCEJ_Function_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Seal_Name_CCEJ_Function_Check</description>
        <label>CCEJ Function Check</label>
        <type>Checkbox</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approver_Source__c</fullName>
        <label>Approver Source</label>
        <picklist>
            <picklistValues>
                <fullName>Requester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Mgmt.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treasury Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix Asset Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CokeOne Gr.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy - BOD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

本番20140705/src/classes/COA_Handler_Other_SealRequest.cls
public with sharing class COA_Handler_Other_SealRequest {
	
	public static void addApproversForNewRFAs(List<RFA__c> listNewRFAs) {
		
		List<RFAUserRole__c> listRFAApproverToInsert = new List<RFAUserRole__c>();
		
		for(RFA__c rfa : listNewRFAs) {
			
			//IT Support Shared User
			RFAUserRole__c approver1 = new RFAUserRole__c();
			approver1.UserName__c = Label.Seal_Second_To_Final_Approver_of_CCEJ_Company; //'005N0000000tPNB';
			approver1.RFA__c = rfa.Id;						
			approver1.RecordTypeId = Utility_Helper_RecordType.mapRFAUserRoleRecordTypeAPINameToIds.get(
				RFA_Utility_Constants.RFAUserRole_RTAPIName_Approver); //'01210000000QsJj';
			approver1.Approver_Source__c = RFA_Utility_Constants.Approver_Source_Seal;
			//approver.ApprovalOrder__c = appprover_order;
			listRFAApproverToInsert.add(approver1);
			
			/*
				if Seal Name CCEJ Company Check or Seal Name CCEJ Function Check is checked, select Kawamoto-san,
				all other cases, select Nakano-san
			*/
			if(rfa.Seal_Name_CCEJ_Company_Check__c == true || rfa.Seal_Name_CCEJ_Function_Check__c == true) {
				//川本　成彦       Kawamoto Naruhiko 00510000001rhvJ
				RFAUserRole__c approver2 = new RFAUserRole__c();
				approver2.UserName__c = Label.Seal_Final_Approver_of_CCEJ_Company; //'00510000001rhvJ';
				approver2.RFA__c = rfa.Id;						
				approver2.RecordTypeId = Utility_Helper_RecordType.mapRFAUserRoleRecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RFAUserRole_RTAPIName_Approver);
				approver2.Approver_Source__c = RFA_Utility_Constants.Approver_Source_Seal;
				//approver.ApprovalOrder__c = appprover_order;
				listRFAApproverToInsert.add(approver2);				
			} else {
				//Nakano Toshio 中野 宗夫 00510000001rhvi
				RFAUserRole__c approver2 = new RFAUserRole__c();
				approver2.UserName__c = Label.Seal_Final_Approver_of_Sub_Company; //'00510000001rhvi';
				approver2.RFA__c = rfa.Id;						
				approver2.RecordTypeId = Utility_Helper_RecordType.mapRFAUserRoleRecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RFAUserRole_RTAPIName_Approver);
				approver2.Approver_Source__c = RFA_Utility_Constants.Approver_Source_Seal;
				//approver.ApprovalOrder__c = appprover_order;
				listRFAApproverToInsert.add(approver2);					
			}
			
		}
		
		if(listRFAApproverToInsert != null && listRFAApproverToInsert.size() > 0) {
			insert listRFAApproverToInsert;
		}
	}
	

}