RFA_MilestoneRM01/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectLeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Sponsor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectSponsor</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Accountable_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accountable/Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverAll_PickList_Status__c</fullName>
        <label>OverAll_PickList_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late &amp; Blocked In Progress</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late &amp; Blocked Not Yet Started</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late &amp; Blocked Deferred</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late &amp; Blocked Resolved</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late &amp; Blocked</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late In Progress</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late Not Yet Started</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late Deferred</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late Resolved</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Late</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked In Progress</fullName>
                <color>#F96FB7</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked Not Yet Started</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked Deferred</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked Resolved</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open In Progress</fullName>
                <color>#66FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open Not Yet Started</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open Deferred</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open Resolved</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <formula>if ( Complete__c == true, &apos;Complete&apos;,
  if ( and( Days_Late_Formula__c &gt; 0,  Blocked__c  ),
    if(Len( Text(Task_Stage__c))&gt;0 , &apos;Late &amp; Blocked &apos; &amp; Text(Task_Stage__c), &apos;Late &amp; Blocked&apos;),
    if (Days_Late_Formula__c &gt; 0,  
      if(Len( Text(Task_Stage__c))&gt;0, &apos;Late &apos; &amp; text(Task_Stage__c), &apos;Late&apos;),
      if(Blocked__c == true, 
        if(Len( Text(Task_Stage__c))&gt;0, &apos;Blocked &apos; &amp; text(Task_Stage__c), &apos;Blocked&apos;), 
        if(Len( Text(Task_Stage__c))&gt;0, &apos;Open &apos; &amp; Text(Task_Stage__c), &apos;Open&apos;) 
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated field indicating if the task is complete, open, late, blocked or late and blocked.</inlineHelpText>
        <label>Overall Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>Project_Milestone__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>Milestone the task is assigned</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>タスク</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CocaColaProjectBIDev/src/classes/Milestone1_MSCharts_ExtensionController.cls
global class Milestone1_MSCharts_ExtensionController {

    private final Milestone1_Milestone__c milestone;
    public ID targetMilestone {get; set;}
    
    public Milestone1_Settings__c settings = Milestone1_Settings__c.getInstance();
    
     public Milestone1_MSCharts_ExtensionController(ApexPages.StandardController stdController) {
        this.milestone = (Milestone1_Milestone__c)stdController.getRecord();
        targetMilestone = this.milestone.Id;
    }
    
    public String simplifyOverallStatus(String status)
    {
        if (status == 'Late In Progress')
        {
            return status;      
        } else if (status.contains('Late')) {
            return 'Late';
        } else if (status == 'Complete') {
            return status;
        } else if (status.contains('Open')) {
            return 'Open';
        }
        
        return '';
    }
    
    public String getTaskStatusForOwners() {
        return getTaskStatusForOwners(this.milestone.Id, '');
    }
    
    public String getTaskStatusForProjectLeaders() {
        return getTaskStatusForOwners(this.milestone.Id, 'projectLeader');
    }
    
    public String getTaskStatusForProjectSponsors() {
        return getTaskStatusForOwners(this.milestone.Id, 'projectSponsor');
    }
    
    public String getTaskStatusForAssigned() {
        return getTaskStatusForOwners(this.milestone.Id, 'projectAssigned');
    }
    
    public String getTaskStatusForOwners(String milestoneId, String queryType) {
        List<Milestone1_Task__c> tasks = [SELECT Milestone1_Task__c.Name, Accountable_Owner__c, OverAll_PickList_Status__c, Overall_Status__c, ProjectId__c, Project_Milestone__c, Assigned_To__c FROM Milestone1_Task__c ORDER BY Accountable_Owner__c, Overall_Status__c ];

        System.debug('getTaskStatusForOwners: ' + targetMilestone + ', tasks ' + tasks);

        Map<Id, String> usernames = new Map<Id, String>();
        Map<Id, Milestone1_Project__c> projects = new Map<Id, Milestone1_Project__c>();

        List<Milestone1_Project__c> allProjects = [SELECT Id, Name, Project_Sponsor__c, Project_Leader__c FROM Milestone1_Project__c ];
        for (Milestone1_Project__c p : allProjects)
        {
            projects.put(p.Id, p);
        }

        // Collect all usernames
        for(Milestone1_Task__c task : tasks) {
        
            Milestone1_Project__c project = projects.get(task.ProjectId__c);
            
            if (queryType == 'projectSponsor') {
                if ((project.Project_Sponsor__c != null) && !usernames.containsKey(project.Project_Sponsor__c)) {
                    usernames.put(project.Project_Sponsor__c, '');
                }
            } else if (queryType == 'projectLeader') {
                if ((project.Project_Leader__c != null) && !usernames.containsKey(project.Project_Leader__c)) {
                    usernames.put(project.Project_Leader__c, '');
                }
            } else if (queryType == 'projectAssigned') {
                if ((task.Assigned_To__c != null) && !usernames.containsKey(task.Assigned_To__c)) {
                    usernames.put(task.Assigned_To__c, '');
                }      
            } else {
                if ((task.Accountable_Owner__c != null) && !usernames.containsKey(task.Accountable_Owner__c)) {
                    usernames.put(task.Accountable_Owner__c, '');
                }            
            }
        }
        
        // Create a map with empty count values
        // OwnerId --> Status --> Count
        Map<String, Map<String, Integer>> theMap = new Map<String, Map<String, Integer>>();
        for (String key : usernames.keySet())
        {
            theMap.put(key, new Map<String, Integer>());
            theMap.get(key).put('Open', 0);
            theMap.get(key).put('Late In Progress', 0);
            theMap.get(key).put('Late', 0);
            theMap.get(key).put('Complete', 0);
        }
        
        for(Milestone1_Task__c task : tasks) 
        {
        
            Milestone1_Project__c project = projects.get(task.ProjectId__c);
            
            System.debug('Task [' + task.Name + '] Sponsor: [' + project.Project_Sponsor__c + '] Leader: [' + project.Project_Leader__c + ']');
            
            if (queryType == 'projectSponsor') {
                if ((project.Project_Sponsor__c != null) && theMap.containsKey(project.Project_Sponsor__c)
                    && (task.Project_Milestone__c == targetMilestone)) {
                    Map<String, Integer> mapForUser = theMap.get(project.Project_Sponsor__c);

                    // Get status
                    if (mapForUser != null)
                    {
                        Integer currentCount = mapForUser.get(simplifyOverallStatus((String)task.OverAll_PickList_Status__c));
                        System.debug('' + mapForUser + ', Overall status: ' + task.Overall_Status__c + ', ' + currentCount);
                        if (currentCount != null)
                            mapForUser.put(simplifyOverallStatus((String)task.Overall_Status__c), (currentCount+1));
                    }
                }
            } else if (queryType == 'projectLeader') {
                if ((project.Project_Leader__c != null) && theMap.containsKey(project.Project_Leader__c)
                    && (task.Project_Milestone__c == targetMilestone)) {
                    Map<String, Integer> mapForUser = theMap.get(project.Project_Leader__c);

                    // Get status
                    if (mapForUser != null)
                    {
                        Integer currentCount = mapForUser.get(simplifyOverallStatus((String)task.OverAll_PickList_Status__c));
                        System.debug('' + mapForUser + ', Overall status: ' + task.Overall_Status__c + ', ' + currentCount);
                        if (currentCount != null)
                            mapForUser.put(simplifyOverallStatus((String)task.Overall_Status__c), (currentCount+1));
                    }
                } 
            } else if (queryType == 'projectAssigned') {
                if ((task.Assigned_To__c != null) && theMap.containsKey(task.Assigned_To__c)
                    && (task.Project_Milestone__c == targetMilestone)) {
                    Map<String, Integer> mapForUser = theMap.get(task.Assigned_To__c);

                    // Get status
                    if (mapForUser != null)
                    {
                        Integer currentCount = mapForUser.get(simplifyOverallStatus((String)task.OverAll_PickList_Status__c));
                        System.debug('' + mapForUser + ', Overall status: ' + task.Overall_Status__c + ', ' + currentCount);
                        if (currentCount != null)
                            mapForUser.put(simplifyOverallStatus((String)task.Overall_Status__c), (currentCount+1));
                    }
                }                                
            }
            else // default is task.Accountable_Owner__c
            {
                if ((task.Accountable_Owner__c != null) && theMap.containsKey(task.Accountable_Owner__c)
                    && (task.Project_Milestone__c == targetMilestone)) {
                    Map<String, Integer> mapForUser = theMap.get(task.Accountable_Owner__c);

                    // Get status
                    if (mapForUser != null)
                    {
                        Integer currentCount = mapForUser.get(simplifyOverallStatus((String)task.OverAll_PickList_Status__c));
                        System.debug('' + mapForUser + ', Overall status: ' + task.Overall_Status__c + ', ' + currentCount);
                        if (currentCount != null)
                            mapForUser.put(simplifyOverallStatus((String)task.Overall_Status__c), (currentCount+1));
                    }
                }
            }
        }
        
        Map<String, Map<String, Integer>> outMap = new Map<String, Map<String, Integer>>();
        for(String userKey : usernames.keySet()) {
            User user = [SELECT Id, Name FROM User Where Id = :userKey];
            outMap.put(user.Name, theMap.get(userKey));
        }
        
        Integer keySet = outMap.keySet().size();
        if (keySet == 0) {
            return '{}';
        }
        
        String ret = '';
        for (String key : outMap.keySet())
        {
            Map<String, Integer> statusMap = outMap.get(key);
            Integer open = statusMap.get('Open');
            Integer late = statusMap.get('Late');
            Integer lateInProgress = statusMap.get('Late In Progress');
            Integer complete = statusMap.get('Complete');
                
            // Only return this person if they have tasks        
            if (open > 0 || lateInProgress > 0 || late > 0 || complete > 0)
                ret += '[\'' + key + '\', ' + open + ',' + late + ',' + lateInProgress + ',' + complete + ', \'\' ],';
        }
        
        return ret;
    }
}