RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Approval_Status__c</fullName>
        <label>Approval Step</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charter Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close-Out Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/RFA__c.object
<CustomObject>
    <description>Request For Authorization</description>
    <fields>
        <fullName>RM_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_Detail_Document_Attached_Y_N_1__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When there is an attached file, please indicate attachment reference etc. in a text.</inlineHelpText>
        <label>Detail Document Attached Y/N</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RM_Detail_Document_Attached_Y_N_2__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When there is an attached file, please indicate attachment reference etc. in a text.</inlineHelpText>
        <label>Detail Document Attached Y/N</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RM_Detail_Document_Attached_Y_N_3__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When there is an attached file, please indicate attachment reference etc. in a text.</inlineHelpText>
        <label>Detail Document Attached Y/N</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RM_Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>RFA承認申請</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_RFA_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related RFA 1</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Related RFA</relationshipLabel>
        <relationshipName>Related_RFA_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the status of the RFA approval.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Requester</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{00000000}</displayFormat>
        <label>RFA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>null</defaultValue>
        <description>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0) will get error in VF page</description>
        <inlineHelpText>回覧の承認順序です。数字の小さい順に承認待ち通知メールが配信されます。同じ番号の場合は同時に通知を受け取ります。</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>RFA Approvers/Users</relationshipLabel>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

本番20140705/src/classes/RFA_TriggerHandler_Helper_ProjectRequest.cls
/*
	without sharing is needed, 
	since when the last approver approved RFA, at the same time, related Project need to be updated,
	since the last approver don't have the permission to access Project, it need System permission to do this.
	put it into another independent class in future.
*/
public without sharing class RFA_TriggerHandler_Helper_ProjectRequest {

	/*
		============ isBefore & isInsert ============ 
	*/
	public static void processMilestoneRFAsInBeforeInsert(List<RFA__c> listNewRFAs) {
		
		List<RFA__c> listProjectInitiateRFAs = new List<RFA__c>();		
		List<RFA__c> listProjectCharterRFAs = new List<RFA__c>();		
		List<RFA__c> listProjectCloseOutRFAs = new List<RFA__c>();				
		
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Initiate_REQUEST)) {
				
				listProjectInitiateRFAs.add(rfa);
				
			} else if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)) {
				
				listProjectCharterRFAs.add(rfa);
				
			} else if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST)) {
				
				listProjectCloseOutRFAs.add(rfa); 				
			}		
		}//end of for(RFAs);
		
		if(listProjectInitiateRFAs != null && listProjectInitiateRFAs.size() > 0) {
			confirmProjectInitiateStatus(listProjectInitiateRFAs);
		}	
		
		if(listProjectCharterRFAs != null && listProjectCharterRFAs.size() > 0) {
			confirmProjectCharterStatus(listProjectCharterRFAs);
		}
		
		if(listProjectCloseOutRFAs != null && listProjectCloseOutRFAs.size() > 0) {
			confirmProjectCloseOutStatus(listProjectCloseOutRFAs);
		}				
	}	
	
	//In Project Initiate request, the related Project can't be in Initiate承認済み, Charter承認済み, CloseOut承認済み,
	//should be in a clean status
	private static void confirmProjectInitiateStatus(List<RFA__c> listNewRFAs) {
		Map<RFA__c, Id> mapRFAToRelatedProjectId = new Map<RFA__c, Id>();
		
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RM_Related_Project__c != null) {
				mapRFAToRelatedProjectId.put(rfa, rfa.RM_Related_Project__c);
			}
		}
		
		if(mapRFAToRelatedProjectId != null 
			&& mapRFAToRelatedProjectId.keySet() != null 
			&& mapRFAToRelatedProjectId.keySet().Size() > 0
			&& mapRFAToRelatedProjectId.values() != null
			&& mapRFAToRelatedProjectId.values().Size() > 0
		) {
			for(Milestone1_Project__c project : [
				Select Id, RM_Approval_Status__c 
				from Milestone1_Project__c 
				where Id IN: mapRFAToRelatedProjectId.values()
				]
			) {
				if(project.RM_Approval_Status__c != null) {
					for(RFA__c rfa : mapRFAToRelatedProjectId.keySet()) {
						if(mapRFAToRelatedProjectId.get(rfa) == project.Id) {
							rfa.addError('Approval Status in related Project is not right !');
						}
					}
				}
			}
		}		
	}
	//can only be  Initiate承認済み not Charter承認済み or CloseOut承認済み,
	private static void confirmProjectCharterStatus(List<RFA__c> listNewRFAs) {
		Map<RFA__c, Id> mapRFAToRelatedProjectId = new Map<RFA__c, Id>();
		
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RM_Related_Project__c != null) {
				mapRFAToRelatedProjectId.put(rfa, rfa.RM_Related_Project__c);
			}
		}
		
		if(mapRFAToRelatedProjectId != null 
			&& mapRFAToRelatedProjectId.keySet() != null 
			&& mapRFAToRelatedProjectId.keySet().Size() > 0
			&& mapRFAToRelatedProjectId.values() != null
			&& mapRFAToRelatedProjectId.values().Size() > 0
		) {
			for(Milestone1_Project__c project : [
				Select Id, RM_Approval_Status__c 
				from Milestone1_Project__c 
				where Id IN: mapRFAToRelatedProjectId.values()
				]
			) {
				if(project.RM_Approval_Status__c != RFA_Utility_Configure.RM_Initiate_Approved) {
					for(RFA__c rfa : mapRFAToRelatedProjectId.keySet()) {
						if(mapRFAToRelatedProjectId.get(rfa) == project.Id) {
							rfa.addError('Approval Status in related Project is not right !');
						}
					}
				}
			}
		}		
	}	
	
	private static void confirmProjectCloseOutStatus(List<RFA__c> listNewRFAs) {
		Map<RFA__c, Id> mapRFAToRelatedProjectId = new Map<RFA__c, Id>();
		
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RM_Related_Project__c != null) {
				mapRFAToRelatedProjectId.put(rfa, rfa.RM_Related_Project__c);
			}
		}
		
		if(mapRFAToRelatedProjectId != null 
			&& mapRFAToRelatedProjectId.keySet() != null 
			&& mapRFAToRelatedProjectId.keySet().Size() > 0
			&& mapRFAToRelatedProjectId.values() != null
			&& mapRFAToRelatedProjectId.values().Size() > 0
		) {
			for(Milestone1_Project__c project : [
				Select Id, RM_Approval_Status__c 
				from Milestone1_Project__c 
				where Id IN: mapRFAToRelatedProjectId.values()
				]
			) {
				if(project.RM_Approval_Status__c != RFA_Utility_Configure.RM_Charter_Approved) {
					for(RFA__c rfa : mapRFAToRelatedProjectId.keySet()) {
						if(mapRFAToRelatedProjectId.get(rfa) == project.Id) {
							rfa.addError('Approval Status in related Project is not right !');
						}
					}
				}
			}
		}		
	}		
	
	/*
		============ isAfter & isInsert ============ 
	*/
	public static void processMilestoneRFAsInAfterInsert(List<RFA__c> listNewRFAs) {
		/*
		for(RFA__c rfa : listNewRFAs) {
			if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Initiate_REQUEST)) {
				
			} else if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)) {
				
			} else if(rfa.RecordTypeId == 
				Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST)) {
				if(rfa.Related_RFA_1__c != null) {
					copyApproversFromRelatedRFA(rfa);
				}
				
			}
		
		}//end of for(RFAs);	
		*/		
	}
	
	public static void copyApproversFromRelatedRFA(RFA__c rfa) {
		List<RFAUserRole__c> listNewRFAApprovers = new List<RFAUserRole__c>();
		
		for(RFAUserRole__c rfaApprover : [
			Select Id, RecordTypeId, UserName__c, ApprovalOrder__c 
				from RFAUserRole__c 
				where RFA__c =: rfa.Id 
				and RecordTypeId =: Utility_Helper_RecordType.mapRFAUserRoleRecordTypeAPINameToIds.get(
					RFA_Utility_Constants.RFAUserRole_RTAPIName_Approver)
			]
		) {
			RFAUserRole__c approver = new RFAUserRole__c();
			approver.RecordTypeId = rfaApprover.RecordTypeId;
			approver.RFA__c = rfa.Id;
			approver.ApprovalOrder__c = rfaApprover.ApprovalOrder__c;
			approver.userName__c =  rfaApprover.UserName__c;
			
			listNewRFAApprovers.add(approver);
		}
		
		if(listNewRFAApprovers != null && listNewRFAApprovers.size() > 0) {
			insert listNewRFAApprovers;
		}
		
	}

	
	/*
		============ isBefore & isUpdate ============ 
	*/

	
	
	/*
		============ isAfter & isUpdate ============ 
	*/
	public static void processMilestoneRFAsInAfterUpdate(		
		List<RFA__c> listNewRFAs, 
		Map<Id, RFA__c> mapOldRFAs
	) {		
		
		Email_Handler_RFA inst = new Email_Handler_RFA();
		
		
		/*
			In h. 02. Project Charter Reques request, if
			Detail Document Attached Y/N or
			Detail Document Attached Y/N or
			Detail Document Attached Y/N is checked, 
			there should be some attachment attached.
		*/
		for(RFA__c rfa : listNewRFAs) {
			//Project Charter and Close Out need to check Attachment Status!
			if(
				(
				rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION 
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_DRAFT
				&& ( 
					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)
 					||
 					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST)	
				   )											
				)	
				||
				(
				rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION 
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_ReturnToRequester
				&& ( 
					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)
 					||
 					rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST)	
				   )	
				)									
			) {
				if(rfa.RM_Detail_Document_Attached_Y_N_1__c == true 
					|| rfa.RM_Detail_Document_Attached_Y_N_2__c == true
					|| rfa.RM_Detail_Document_Attached_Y_N_3__c == true
				) {
					List<Attachment> listAttachments = [Select Id from Attachment where ParentId =: rfa.Id];

					if(listAttachments == null || (listAttachments != null && listAttachments.size() == 0)) {
						//throw new RFA_AP19_RFAValidationException('No attachments !');

						//throw new Utility_Helper_Exception('No attachments !');

						rfa.addError(
							Label.RM_Attached_File
							//'No attachments !'
						);	

					}
				}
			}//end of if(attachment check);
			
			if(rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_APPROVED
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION																
			) {
				if(rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Initiate_REQUEST)) {
				
					//Send Email to Team Members when RFA is approved
					inst.sendEmail_TeamMembers_AfterInitiate(rfa);	
					
				} else if(rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)) {
							
					//Send Email to Team Members when RFA is approved
					inst.sendEmail_TeamMembers_AfterCharter(rfa);						
				}				
				
			}									
		}//end of for(RFAs);
		
		updateRelatedProjectStatus(listNewRFAs, mapOldRFAs);
		
	}	
	
	
	//Need to develop
	/*
	public static void checkAttachmentStatus(
		List<RFA__c> listNewRFAs, 
		Map<Id, RFA__c> mapOldRFAs
	) {	
								
	}
	*/
	
	/*
		Field Label	Approval Status
		Field Name	RM_Approval_Status
		API Name	RM_Approval_Status__c
	*/
	public static void updateRelatedProjectStatus(
		List<RFA__c> listNewRFAs, 
		Map<Id, RFA__c> mapOldRFAs
	) {
		for(RFA__c rfa : listNewRFAs) {		
			if(rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_APPROVED
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION
				&& rfa.RM_Related_Project__c != null
				&& rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Initiate_REQUEST)
				) {	
					
				Milestone1_Project__c project = [
					Select Id, RM_Approval_Status__c from Milestone1_Project__c where Id =: rfa.RM_Related_Project__c
				];
				project.RM_Approval_Status__c = RFA_Utility_Configure.RM_Initiate_Approved; //'Initiate承認済み';
				update project;
				
			} else if(rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_APPROVED
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION
				&& rfa.RM_Related_Project__c != null
				&& rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Charter_REQUEST)
			) {	

				Milestone1_Project__c project = [
					Select Id, RM_Approval_Status__c from Milestone1_Project__c where Id =: rfa.RM_Related_Project__c
				];
				project.RM_Approval_Status__c = RFA_Utility_Configure.RM_Charter_Approved; //'Chater承認済み';
				update project;
				
			} else if(rfa.Stage__c == RFA_Utility_Constants.RFA_STATUS_APPROVED
				&& mapOldRFAs.get(rfa.Id).Stage__c == RFA_Utility_Constants.RFA_STATUS_CIRCULATION
				&& rfa.RM_Related_Project__c != null
				&& rfa.RecordTypeId == 
					Utility_Helper_RecordType.mapRFARecordTypeAPINameToIds.get(
						RFA_Utility_Constants.RECORDTYPE_Project_Close_Out_REQUEST)
			) {	
				Milestone1_Project__c project = [
					Select Id, RM_Approval_Status__c from Milestone1_Project__c where Id =: rfa.RM_Related_Project__c
				];
				project.RM_Approval_Status__c = RFA_Utility_Configure.RM_Close_Approved; //'CloseOut承認済み';
				update project;				
			}
		}							
		
	}
	
	
	
	/*
		============ isBefore & isDelete ============ 
	*/


	
	
	/*
		============ isAfter & isDelete ============ 
	*/



	/*
		============ isAfter & isUnDelete ============ 
	*/	


}