RFA_MilestoneRM01/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>マイルストーンが完了したかどうか</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>このプロジェクトが割り当てられるプロジェクトです。もしこのプロジェクトが子プロジェクトの場合は空白になります。</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>Project_Milestone__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>Milestone the task is assigned</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(&apos;../&apos; + Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>タスク</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/Milestone_Permission__c.object
<CustomObject>
    <description>プロジェクトやマイルストーンのアクセス権限管理をするオブジェクトである</description>
    <fields>
        <fullName>ProjectRole__c</fullName>
        <description>プロジェクトロールからアクセス権限にラベル名を変更</description>
        <label>Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>Modify All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Editable(Non-Members)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>プロジェクト名</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Milestone_Permission</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ユーザ名</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Milestone_Permission</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>プロジェクトチームメンバー</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>チーム No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CM02/src/classes/Milestone_Task_Delete_Controller.cls
global class Milestone_Task_Delete_Controller {
	private final static String TYPE_MILESTONE = 'milestone';
	private final static String TYPE_TASK = 'task';
	webservice static boolean deleteConfirm(String strId, String strType ) { 
        system.debug('strId : ' + strId + '     strType : ' + strType);
        String profileId = Userinfo.getProfileId();
        String loginUserId = Userinfo.getUserId();
        //システム管理者
		Integer adminSize = [SELECT count() FROM Profile WHERE Id = :profileId AND (Name = 'システム管理者' OR Name = 'System Administrator')];
        
        if(strType == TYPE_MILESTONE){
        	//PMの場合
        	Integer mpSize  = [SELECT count() FROM Milestone_Permission__c 
								WHERE Project__c = :[SELECT Project__c FROM Milestone1_Milestone__c WHERE Id =:strId].Project__c 
								AND UserName__c = :loginUserId
								AND ProjectRole__c = :system.Label.Custom_Milestone_Role_PM];
        	
        	//所有者リスト
        	//Integer ownerSize = [SELECT count() FROM Milestone1_Project__c 
        	//						WHERE Id = :[SELECT Project__c FROM Milestone1_Milestone__c WHERE Id =:strId].Project__c 
        	//					 	AND OwnerId = :loginUserId];
        	Integer ownerSize = [SELECT count() FROM Milestone1_Milestone__c WHERE Id =:strId AND OwnerId = :loginUserId];
        	if(mpSize != 0 || ownerSize != 0 || adminSize != 0){
        		delete [SELECT id FROM Milestone1_Milestone__c WHERE id =:strId];
	        	return true;
        	}
        } else if(strType == TYPE_TASK){
        	Integer mpSize  = [SELECT count() FROM Milestone_Permission__c 
        									WHERE Project__c = :[SELECT ProjectId__c FROM Milestone1_Task__c WHERE Id =:strId].ProjectId__c 
        									AND UserName__c = :loginUserId
        									AND ProjectRole__c = :system.Label.Custom_Milestone_Role_PM];
        	
        	//所有者リスト
        	//Integer ownerSize = [SELECT count() FROM Milestone1_Project__c 
        	//						WHERE Id = :[SELECT ProjectId__c FROM Milestone1_Task__c WHERE Id =:strId].ProjectId__c 
        	//					 	AND OwnerId = :loginUserId];
        	Integer ownerSize = [SELECT count() FROM Milestone1_Task__c WHERE Id = :strId AND Project_Milestone__r.OwnerId = : loginUserId];
    		if(mpSize != 0 || ownerSize != 0 || adminSize != 0){
    			//2013.12.26 追加作業 start
    			//delete [SELECT id FROM Milestone1_Task__c WHERE id =:strId];
	        	Milestone1_Task__c deleteTask = [SELECT id, Complete__c, Project_Milestone__c FROM Milestone1_Task__c WHERE id =:strId];
	        	
	        	//タスクが削除された場合、同一マイルストーンの他のタスクの「完了チェック」データを判定
	        	Milestone1_Milestone__c dummyMilestone = [SELECT id, Complete__c, (Select id, Complete__c  From Project_Tasks__r) FROM Milestone1_Milestone__c WHERE Id = :deleteTask.Project_Milestone__c];
	        	boolean isOtherTask = false;
	        	boolean isAllComplete = true;
	        	for(Milestone1_Task__c mt : dummyMilestone.Project_Tasks__r){
	        		isOtherTask = true;
	        		if(mt.Complete__c == false) {
	        			isAllComplete = false;
	        			break;
	        		}
	        	}
	        	delete deleteTask;
	        	if(isOtherTask && isAllComplete){
	        		dummyMilestone.Complete__c = true;
	        		update dummyMilestone;
	        	}
	        	//2013.12.26  追加作業 end
	        	return true;
	        }
        }
        return false; 
    }

}