RFA_MilestoneRM01/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <label>CompletedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>期限日</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>このプロジェクトが割り当てられるプロジェクトです。もしこのプロジェクトが子プロジェクトの場合は空白になります。</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>BI 専用のフィールドである</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <recordTypes>
        <fullName>Finance</fullName>
        <active>true</active>
        <description>Finance専用</description>
        <label>Finance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>プロジェクトの完了期限</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Key</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Specific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>プロジェクトの状態</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Function__c</fullName>
        <label>Sub Function</label>
        <picklist>
            <controllingField>Function__c</controllingField>
            <picklistValues>
                <fullName>Controller&apos;s Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BP&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(VM) Vending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Commercial Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Excellence &amp; Package Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Strategy, Shared Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(EOSH)Environmentand Occupational Safetyand Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning &amp; SC Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Drink Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics_Pr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-corporate Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactuaring (BSC)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Finance</fullName>
        <active>true</active>
        <description>Finance専用</description>
        <label>Finance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CocaColaProjectBidev_2/src/classes/Milestone_CokeOne_MatrixReportCtrlTest.cls
@isTest
private class Milestone_CokeOne_MatrixReportCtrlTest {
	static testMethod void myUnitTest() {
    	Test.startTest();
    	//Project_Type__c : Key, Integration, Finance Specific, ERP
    	//Sub_Function__c : Controller's Group, BP&A, Commercial Finance, Supply Chain Finance, M&A, Finance Integration, Investor Relations, Internal Audit, Corporate Administrator

        Milestone1_Project__c p1 = new Milestone1_Project__c(Name = 'Project1', Sub_Function__c='Commercial Finance', Project_Type__c='Integration',Function__c='Finance', Project_Status__c='Green', Status__c = 'Active' );
        insert p1;
        List<Milestone1_Milestone__c> mileList = new List<Milestone1_Milestone__c>();
        for(integer i=0; i<10; i++){
        	Milestone1_Milestone__c m = new Milestone1_Milestone__c(Name='Test'+i,
								Deadline__c=System.today(),
								CompletedDate__c=System.today(),
								Project__c = p1.Id, RecordTypeId =system.Label.Milestone_RecordType_CokeOne);
			mileList.add(m);
        }
        insert mileList;
        Milestone_CokeOne_MatrixReportCtrl matrix = new Milestone_CokeOne_MatrixReportCtrl();
        
        //マップキー確認
        system.debug('projectMap : '+matrix.projectMap);
        System.assertEquals(true, matrix.projectMap.containsKey('Project1'));
        System.assertEquals(true, matrix.statusMap.containskey('Green'));
        
        //設定したPickListサイズチェック
        List<SelectOption> statusFilter = matrix.getFilterStatus();
        System.assertEquals(5, statusFilter.size());
        Test.stopTest();
    }
}