RFA_MilestoneRM01/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>期限日</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>マイルストーンの開始日</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>このプロジェクトが割り当てられるプロジェクトです。もしこのプロジェクトが子プロジェクトの場合は空白になります。</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Milestone__c.object
    <fields>
        <fullName>RM_Actual_Date__c</fullName>
        <label>Actual Date</label>
        <type>Date</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Milestone__c.object
    <fields>
        <fullName>RM_Adjustment_Date__c</fullName>
        <label>Adjustment Date</label>
        <type>Date</type>
    </fields>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>プロジェクトの完了期限</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>プロジェクトの開始日</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectLeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Sponsor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectSponsor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Actual_Date__c</fullName>
        <label>Actual Date</label>
        <type>Date</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Issues_For_Escalation_Recovery_plan__c</fullName>
        <label>Issues For Escalation/Recovery Plan</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Key_Events_For_Next_Week__c</fullName>
        <label>Key Events For Next Week</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Key_Events_From_This_Week__c</fullName>
        <label>Key Events From This Week</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Leader_discussion__c</fullName>
        <label>Leader discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Sponsor_discussion__c</fullName>
        <label>Sponsor discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Team_Member_discussion__c</fullName>
        <label>Team Member discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

RFA_MilestoneRM01/src/objects/Milestone_Synergy_Management__c.object
<CustomObject>
    <fields>
        <fullName>ABP__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ABP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Day1_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Day1 Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Depreciation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Depreciation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_OPEX__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Other OPEX</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Milestone_Synergy_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RE__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>予算管理</label>
    <nameField>
        <label>年度</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_Actual_Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual_Pr_Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_Actual_Opex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual_Pr_Opex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_Plan_ABP_Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ABP_Pr_Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_Plan_ABP_Opex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ABP_Pr_Opex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_RE_Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE_Pr_Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>POV_RE_Opex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE_Pr_Opex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>RM_RE_lower_Pr_Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE (lower)_Pr_Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>RM_RE_lower_Pr_Opex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE (lower)_Pr_Opex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>RM_RE_upper_Pr_Capex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE (upper)_Pr_Capex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

MilestoneRFAFullSandBox/src/objects/Milestone_Synergy_Management__c.object
    <fields>
        <fullName>RM_RE_upper_Pr_Opex__c</fullName>
        <defaultValue>0</defaultValue>
        <label>RE (upper)_Pr_Opex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>

CM01/src/classes/Milestone_ProjectExecuteCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Milestone_ProjectExecuteCtrlTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Test.startTest();
    	User u = [SELECT Id FROM User limit 1];
    	//Project Insert
    	Milestone1_Project__c insertP = new Milestone1_Project__c(Name = 'Test',Function__c = 'HR',Project_Status__c='Green',
															Project_Sponsor__c=u.id, Project_Leader__c=u.id,
															RM_Key_Events_From_This_Week__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ',
															RM_Key_Events_For_Next_Week__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ',
															RM_Issues_For_Escalation_Recovery_plan__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ',
															RM_Sponsor_discussion__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ',
															RM_Leader_discussion__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ',
															RM_Team_Member_discussion__c = 'ああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああいいいいいいいいいいいいいいいいいいいいああああああああああああああああああああ');
    	insert insertP;
        
        //Milestone Insert
        List<Milestone1_Milestone__c> mileList = new List<Milestone1_Milestone__c>();
        for(integer i=0; i<30; i++){
        	Milestone1_Milestone__c m = new Milestone1_Milestone__c(Name='Test'+i,
        						Kickoff__c = system.today(),
								Deadline__c=System.today(),
								 RM_Adjustment_Date__c = system.today(), RM_Actual_Date__c=system.today(),
								Project__c = insertP.Id);
			mileList.add(m);
        }
        insert mileList;
        
        //yosan Insert
        List<Milestone_Synergy_Management__c> sList = new List<Milestone_Synergy_Management__c>();
        for(integer i=1;i<13;i++){
        	String tempName = '' + i;
			if(i < 10) tempName = '0' + i;
        	Milestone_Synergy_Management__c sObj = new Milestone_Synergy_Management__c(Name='2014_'+tempName,
								POV_Plan_ABP_Opex__c = 10,
								POV_RE_Opex__c = 10,
								RM_RE_upper_Pr_Opex__c = 10,
								RM_RE_lower_Pr_Opex__c = 10,
								POV_Actual_Opex__c = 10,
								POV_Plan_ABP_Capex__c = 10,
								POV_RE_Capex__c = 10,
								RM_RE_upper_Pr_Capex__c = 10,
								RM_RE_lower_Pr_Capex__c = 10,
								POV_Actual_Capex__c = 10,
								Day1_Plan__c = 10,
								New_Plan__c = 10,
								ABP__c = 10,
								RE__c = 10,
								Actual__c = 10,
								Capex__c = 10,
								Depreciation__c = 10,
								Other_OPEX__c = 10,
								Project__c = insertP.Id  );
			sList.add(sObj);
        }
        insert sList;
        PageReference pageRef = Page.Milestone_ProjectExecute;
		pageRef.getParameters().put('projectId',insertP.Id);
		Test.setCurrentPage(pageRef);  
        Milestone_ProjectExecuteCtrl projectExec = new Milestone_ProjectExecuteCtrl();
        projectExec.back();
        projectExec.save();
        projectExec.PDFHistory();
        Test.stopTest();
    }
}