RFA_MilestoneRM01/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>期限日</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>マイルストーンの開始日</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_No__c</fullName>
        <formula>Project__r.Project_No__c</formula>
        <label>Project No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>このプロジェクトが割り当てられるプロジェクトです。もしこのプロジェクトが子プロジェクトの場合は空白になります。</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>BI 専用のフィールドである</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>プロジェクトの完了期限</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>プロジェクトの開始日</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectLeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_No__c</fullName>
        <label>Project No</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Sponsor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectSponsor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status_View__c</fullName>
        <formula>IMAGE( 
CASE(Project_Status__c, 
&quot;Green&quot;, &quot;/img/samples/light_green.gif&quot;, 
&quot;Yellow&quot;, &quot;/img/samples/light_yellow.gif&quot;, 
&quot;Red&quot;, &quot;/img/samples/light_red.gif&quot;, 
&quot;/s.gif&quot;), &quot;status color&quot; 
)</formula>
        <label>Project Status*</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>プロジェクトの状態</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Approval_Status__c</fullName>
        <label>Approval Step</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charter Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close-Out Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Commercial_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commercial</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Commercial_Select__c</fullName>
        <label>Commercial</label>
        <picklist>
            <picklistValues>
                <fullName>KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C7-Marketing &amp; Commercial Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C8-Commercial Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercialization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VM</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Finance_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finance</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Finance_Select__c</fullName>
        <label>Finance</label>
        <picklist>
            <picklistValues>
                <fullName>Business Planning and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F1-Controller’s group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal control compliance/J-SOX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-KO Subsidiaries and M&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain Finance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_HR_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HR</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_HR_Select__c</fullName>
        <label>HR</label>
        <picklist>
            <picklistValues>
                <fullName>BPCommercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compensation and Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H8-Shared Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H9-HRAdministration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Integration</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_IS_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IS</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Issues_For_Escalation_Recovery_plan__c</fullName>
        <label>Issues For Escalation/Recovery Plan</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Key_Events_For_Next_Week__c</fullName>
        <label>Key Events For Next Week</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Key_Events_From_This_Week__c</fullName>
        <label>Key Events From This Week</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Leader_discussion__c</fullName>
        <label>Leader discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Procurement_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Procurement</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Procurement_Select__c</fullName>
        <label>Procurement</label>
        <picklist>
            <picklistValues>
                <fullName>Cold Drink Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRO&amp;DME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Driving</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_SCM_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SCM</label>
        <type>Checkbox</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_SCM_Select__c</fullName>
        <label>SCM</label>
        <picklist>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment &amp; Occupational Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OE &amp; Package Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning &amp; SC Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Strategy, Shared Service</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Sponsor_discussion__c</fullName>
        <label>Sponsor discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

MilestoneRFA_CM01/src/objects/Milestone1_Project__c.object
    <fields>
        <fullName>RM_Team_Member_discussion__c</fullName>
        <label>Team Member discussion</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>

RFA_MilestoneRM01/src/objects/Milestone_Synergy_Management__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Milestone_Synergy_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>予算管理</label>
    <nameField>
        <label>年度</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

本番20140705/src/classes/Milestone_ProjectExecuteCtrl.cls
/**
*	このクラスはProject Execute画面制御するクラスである。
*	Target Object　：　Project, Milestone, 予算管理である。
*
*/

public class Milestone_ProjectExecuteCtrl {
	//View＆Updateに使用する変数
	public Milestone1_Project__c projectObj{get;set;}
	public List<Milestone_Synergy_Management__c> procurementObjs {get;set;}
	public List<Milestone_Synergy_Management__c> synergyObjs {get;set;}
	public List<Milestone_Synergy_Management__c> budgetObjs {get;set;}
	public Milestone1_Milestone__c tempMilestone {get;set;}
	
	//パラメータで受け取ったProjectID
	public String projectId {get;set;}
	//予算管理の総計変数を定義
	//Synergy Managementセッション
	public Decimal Total_Day1_Plan {get;set;}
	public Decimal Total_New_Plan  {get;set;}
	public Decimal Total_ABP  {get;set;}
	public Decimal Total_RE {get;set;}
	public Decimal Total_Actual {get;set;}
	//Investment/Budgetセッション
	public Decimal Total_Capex  {get;set;}
	public Decimal Total_Depreciation  {get;set;}
	public Decimal Total_Other_OPEX  {get;set;}
	//Only Procurement Synergy
	//public Decimal Total_New_Plan_before_Risk_Opex {get;set;}			2014/6/3 削除
	public Decimal Total_POV_Plan_ABP_Opex  {get;set;}
	public Decimal Total_POV_RE_Opex {get;set;}
	public Decimal Total_RE_upper_Pr_Opex {get;set;}				//2014/6/3新規追加
	public Decimal Total_RE_lower_Pr_Opex {get;set;}				//2014/6/3新規追加
	public Decimal Total_POV_Actual_Opex {get;set;}
	//public Decimal Total_New_Plan_before_Risk_Pr_Capex {get;set;}			2014/6/3 削除
	public Decimal Total_POV_Plan_ABP_Capex  {get;set;}
	public Decimal Total_POV_RE_Capex {get;set;}
	public Decimal Total_RE_upper_Pr_Capex {get;set;}				//2014/6/3新規追加
	public Decimal Total_RE_lower_Pr_Capex {get;set;}				//2014/6/3新規追加
	public Decimal Total_POV_Actual_Capex  {get;set;}
	//予算管理情報をPDFに出力するかしないかのフラグ
	public boolean pdf_flag {get;set;}
	
	
	
	//コンストラクタ
	public Milestone_ProjectExecuteCtrl(){
		//Project詳細画面から受け取るProjectId
		projectId = ApexPages.currentPage().getParameters().get('projectId');
		system.debug('Project Id : '+projectId);
		//各Object初期化
		projectObj = new Milestone1_Project__c();
		synergyObjs = new List<Milestone_Synergy_Management__c>();
		tempMilestone = new Milestone1_Milestone__c();
		pdf_flag = false;
		//初期データロード
		init();
	}
	
	//初期データロードメソッド
	public void init(){
		pdf_flag = false;
		//合計変数を初期化
		doTotalResetAmount();
		
		//Project Data取得後、設定
		List<Milestone1_Project__c> resultProject = [SELECT Id,
															Name,
															Project_No__c,
															RM_Approval_Status__c,
															Kickoff__c,
															Deadline__c,
															Function__c,
															Project_Sponsor__c,
															Project_Leader__c,
															Status__c,
															Project_Status__c,
															Project_Status_View__c,
															RM_Key_Events_From_This_Week__c,
															RM_Key_Events_For_Next_Week__c,
															RM_Issues_For_Escalation_Recovery_plan__c,
															RM_Sponsor_discussion__c,
															RM_Leader_discussion__c,
															RM_Team_Member_discussion__c,
															RM_Commercial_Check__c,
															RM_Commercial_Select__c,
															RM_SCM_Check__c,
															RM_SCM_Select__c,
															RM_Procurement_Check__c,
															RM_Procurement_Select__c,
															RM_HR_Check__c,
															RM_HR_Select__c,
															RM_Finance_Check__c,
															RM_Finance_Select__c,
															RM_IS_Check__c,
															RM_IS_Select__c,
															RM_Legal_Check__c,
															RM_Legal_Select__c,
															RM_PAC_Check__c,
															RM_PAC_Select__c,
															RM_BI_Check__c,
															RM_BI_Select__c
													FROM Milestone1_Project__c
													WHERE Id=:projectId
													];
		if(resultProject != null && resultProject.size() > 0) projectObj = resultProject.get(0);
		//予算管理を取得して設定
		//Only Procurement Synergyデータ
		procurementObjs = [SELECT Id, Name,
								//New_Plan_before_Risk_Opex__c,			2014/6/3 削除
								POV_Plan_ABP_Opex__c,
								POV_RE_Opex__c,
								RM_RE_upper_Pr_Opex__c,				//2014/6/3新規追加
								RM_RE_lower_Pr_Opex__c,				//2014/6/3新規追加
								POV_Actual_Opex__c,
								//New_Plan_before_Risk_Pr_Capex__c,			2014/6/3 削除
								POV_Plan_ABP_Capex__c,
								POV_RE_Capex__c,
								RM_RE_upper_Pr_Capex__c,				//2014/6/3新規追加
								RM_RE_lower_Pr_Capex__c,				//2014/6/3新規追加
								POV_Actual_Capex__c 
					   FROM Milestone_Synergy_Management__c 
					   WHERE Project__c =:projectId
					   ORDER BY Name];
		//Synergy Managementデータ
		synergyObjs = [SELECT Id, Name,
								Day1_Plan__c,
								New_Plan__c,
								ABP__c,
								RE__c,
								Actual__c 
					   FROM Milestone_Synergy_Management__c 
					   WHERE Project__c =:projectId
					   ORDER BY Name];
		//Investment/Budgetデータ
		budgetObjs = [SELECT Id, Name,
								Capex__c,
								Depreciation__c,
								Other_OPEX__c 
					   FROM Milestone_Synergy_Management__c 
					   WHERE Project__c =:projectId
					   ORDER BY Name];
		//それぞれの合計を取得する。
		for(Milestone_Synergy_Management__c sObj1 : procurementObjs){
			//合計値を設定
			this.getTotalCalc1(sObj1);
		}
		for(Milestone_Synergy_Management__c sObj2 : synergyObjs){
			//合計値を設定
			this.getTotalCalc2(sObj2);
		}
		for(Milestone_Synergy_Management__c sObj3 : budgetObjs){
			//合計値を設定
			this.getTotalCalc3(sObj3);
		}
		
	}
	//Only Procurement Synergy合計するメソッド
	private void getTotalCalc1(Milestone_Synergy_Management__c msm){
		system.debug('*****************Start getTotalCal1');
		//Only Procurement Synergy
		//Total_New_Plan_before_Risk_Opex += msm.New_Plan_before_Risk_Opex__c;			2014/6/3 削除
		Total_POV_Plan_ABP_Opex += nullConvertZero(msm.POV_Plan_ABP_Opex__c);
		Total_POV_RE_Opex += nullConvertZero(msm.POV_RE_Opex__c);
		Total_RE_upper_Pr_Opex += nullConvertZero(msm.RM_RE_upper_Pr_Opex__c);				//2014/6/3新規追加
		Total_RE_lower_Pr_Opex += nullConvertZero(msm.RM_RE_lower_Pr_Opex__c);				//2014/6/3新規追加
		Total_POV_Actual_Opex += nullConvertZero(msm.POV_Actual_Opex__c);
		
		//Total_New_Plan_before_Risk_Pr_Capex += msm.New_Plan_before_Risk_Pr_Capex__c;			2014/6/3 削除
		Total_POV_Plan_ABP_Capex += nullConvertZero(msm.POV_Plan_ABP_Capex__c);
		Total_POV_RE_Capex += nullConvertZero(msm.POV_RE_Capex__c);
		Total_RE_upper_Pr_Capex += nullConvertZero(msm.RM_RE_upper_Pr_Capex__c);				//2014/6/3新規追加
		Total_RE_lower_Pr_Capex += nullConvertZero(msm.RM_RE_lower_Pr_Capex__c);				//2014/6/3新規追加
		Total_POV_Actual_Capex += nullConvertZero(msm.POV_Actual_Capex__c);
		system.debug('*****************End getTotalCal1');
	}
	//Synergy Management合計するメソッド
	private void getTotalCalc2(Milestone_Synergy_Management__c msm){
		system.debug('*****************Start getTotalCal2');
		//Synergy Managementセッション
		Total_Day1_Plan += nullConvertZero(msm.Day1_Plan__c);
		Total_New_Plan += nullConvertZero(msm.New_Plan__c);
		Total_ABP += nullConvertZero(msm.ABP__c);
		Total_RE += nullConvertZero(msm.RE__c);
		Total_Actual += nullConvertZero(msm.Actual__c);
		system.debug('*****************End getTotalCal2');
	}
	//Investment/Budget合計するメソッド
	private void getTotalCalc3(Milestone_Synergy_Management__c msm){
		system.debug('*****************Start getTotalCal3');
		//Investment/Budgetセッション
		Total_Capex += nullConvertZero(msm.Capex__c);
		Total_Depreciation += nullConvertZero(msm.Depreciation__c);
		Total_Other_OPEX += nullConvertZero(msm.Other_OPEX__c);
		system.debug('*****************End getTotalCal3');
	}
	
	//全ての合計金額を初期化する
	private void doTotalResetAmount(){
		//Total_New_Plan_before_Risk_Opex = 0;			2014/6/3 削除
		Total_POV_Plan_ABP_Opex = 0;
		Total_POV_RE_Opex = 0;
		Total_RE_upper_Pr_Opex = 0;				//2014/6/3新規追加
		Total_RE_lower_Pr_Opex = 0;				//2014/6/3新規追加
		Total_POV_Actual_Opex = 0;
		//Total_New_Plan_before_Risk_Pr_Capex = 0;			2014/6/3 削除
		Total_POV_Plan_ABP_Capex = 0;
		Total_POV_RE_Capex = 0;
		Total_RE_upper_Pr_Capex = 0;				//2014/6/3新規追加
		Total_RE_lower_Pr_Capex = 0;				//2014/6/3新規追加
		Total_POV_Actual_Capex = 0;
		
		Total_Day1_Plan = 0;
		Total_New_Plan = 0;
		Total_ABP = 0;
		Total_RE = 0;
		Total_Actual = 0;
		//Investment/Budgetセッション
		Total_Capex = 0;
		Total_Depreciation = 0;
		Total_Other_OPEX = 0;
	}
	
	public Pagereference back(){
		return new Pagereference('/' + projectId);
	}
	
	//Project及び予算管理データを保存するイベント
	public Pagereference save(){
		try{
			update projectObj;
			if(procurementObjs.size() > 0) update procurementObjs;
			if(synergyObjs.size() > 0) update synergyObjs;
			if(budgetObjs.size() > 0) update budgetObjs;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, system.label.RM_Saved));
			//初期データ呼出す
			init();
		}catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, system.label.RM_Save_Error));
		}
        return null; 
	}
	
	//PDFファイルを作成し、Project関連リストである「メモ＆添付ファイル」に添付するイベント
	public Pagereference PDFHistory(){
		//PDFページを呼び出す
		Pagereference pdf = Page.Milestone_ProjectExecutePDF;
        //PDFページにパラメータ設定
        pdf.getParameters().put('projectId',projectId);
        pdf.getParameters().put('pdf_flag',String.valueOf(pdf_flag));
        try{
        	//Local Timeを取得
        	Datetime nowTime = system.now();
        	//Datetime result = Datetime.newInstance(nowTime.date(),nowTime.time());
        	Datetime resultTime = nowTime.addHours(9);
        	//添付ファイル生成し、挿入処理を行う。
	        Attachment attach = new Attachment();
	        Blob body = pdf.getContent();
	        attach.Body = body;
	        attach.Name = 'Project_Update_Backup' + resultTime + '.pdf';
	        attach.IsPrivate = false;
	        attach.ParentId = projectId;
	        insert attach;
	        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, system.label.RM_PDF_Saved));
        }catch(Exception e){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, system.label.RM_Save_Error));
        }
        
		return null;
	}
	
	//数値のnullを0に変える処理
    private Decimal nullConvertZero(Decimal NumData){
        if(NumData == null){
            return 0;
        }else{
            return NumData;
        }
    }
	
}