RFA_MilestoneRM01/src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>プロジェクトの完了期限</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>プロジェクトの開始日</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

本番20140705/src/classes/Test_ChartGVM_ExtensionController.cls
@isTest
public class Test_ChartGVM_ExtensionController {

    static testMethod void testGetTaskStatusForOwners() {        
        Milestone1_Project__c ms = new Milestone1_Project__c();
        ms.Kickoff__c = Date.Today();
        ms.Deadline__c = Date.Today()+10;
        insert ms;

        List<Milestone1_Project__c> projects = [SELECT Id FROM Milestone1_Project__c LIMIT 1];
                
        String pid = null;
        Milestone1_Project__c lastProject = null;
        for (Milestone1_Project__c p : projects)
        {
            pid = p.Id;
            lastProject = p;
        }
                
        System.debug('Project ID: ' + pid);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(lastProject);
        Milestone1_ChartGVM_ExtensionController controller = new Milestone1_ChartGVM_ExtensionController(sc);

        controller.getTaskStatusForOwners();

    }

}